### ISSUE TITLE
[ObjC] improve Swift interoperability for repeated objects

### ISSUE THREAD

**Issue by Cyberbeni** [protocolbuffers/protobuf#10011]
**What language does this apply to?**

Objective-C

**Describe the problem you are trying to solve.**

Repeated values get translated into an NSMutableArray with proper type information but that type information gets lost when it is accessed from Swift code.

**Describe the solution you'd like**

It would be nice to have a getter/setter for these properties that used NSArray because that keeps the type information when accessed from Swift. (Or a getter + an insert object function to minimize the amount of copies)

**Describe alternatives you've considered**

\-

**Additional context**

\-

**Comment by jskeet** [comment]
@elharo: Was this assigned to me by mistake? I know nothing about Objective C.

**Comment by thomasvl** [comment]
For a better Swift interface, why not just use [SwiftProtobufs](https://github.com/apple/swift-protobuf)?

Adding helper methods is always tricky for ObjC because the languages doesn't dead strip. So trying to figure out what is worth while without adding a lot of bloat to applications gets complicated pretty quickly.

**Comment by Cyberbeni** [comment]
Our codebase still has a lot of Objective-C code using the protobuf types and AFAIK `swift-protobuf` generates structs from the proto, which are not usable from Objective-C. (And could also introduce bugs if there are any places that rely on these being classes rather than structs)
