### ISSUE TITLE
change the size variable to long

### ISSUE THREAD

**Issue by 1zg12** [protocolbuffers/protobuf#10034]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
java

**Describe the problem you are trying to solve.**
With the size variable being `int`, it actually would make the protobuf basically not work with large data set (>2GB). 
For example, the `getSerializedSize` would give a wrong estimate of the message size. However, without a proper identification of the message size, it becomes very difficult to tell how to handle the message (for example, maybe split the large data set).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://github.com/protocolbuffers/protobuf/issues/8075
https://github.com/protocolbuffers/protobuf/issues/10033

**Comment by elharo** [comment]
Protobuf basically doesn't work with messages larger than 2 GB. I strongly recommend you not put more than a few megabytes into each message. Proto is very much not optimized or designed for large messages. 

I wish this had been explicitly planned for and either supported or forbidden when proto2 was created, but it wasn't so that's the situation we're in today and it's unlikely to change.
