### ISSUE TITLE
[C#] Generated C# File has problems

### ISSUE THREAD

**Issue by RedElectricity** [protocolbuffers/protobuf#10185]
**What version of protobuf and what language are you using?**
Version: main
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc

**What did you do?**
1. I use the command `protoc --proto_path ./protos --csharp_out ./Generated/cs ./protos/*.proto` to generate code    
My Protobuf File:    
```
syntax = "proto3";

package beatmap;

option csharp_namespace = "xxx";
option go_package="xxx";

option cc_enable_arenas = true;

message BeatMapDef {
  float beat = 1;
}
```
2. Rider noticed the generated code has problems
![uTools_1656411611871](https://user-images.githubusercontent.com/75127571/176155881-31ad27c2-bc29-4a65-ae2b-de1fa2787909.png)

**What did you expect to see**
I want to generate the c# file hasn't problems

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
```
> protoc.exe --version
libprotoc 3.19.4

> dotnet --version
6.0.101
```
Project C# => .Net 6
Language Version => C# 10.0

**Comment by RedElectricity** [comment]
This is generated C# file
https://pastebin.mozilla.org/fOJQA63a

**Comment by amanda-tarafa** [comment]
I cannot reproduce your issue. See [here](https://gist.github.com/amanda-tarafa/efc9f7adbeaf8f55158f6e4126163b9f) a `BeatMap.proto` exactly as the one you have pasted in your question, and the generated C# code in `BeatMap.cs` which has no issues at all.

Looking at your generated code with the namespace `namespace Movalia.ProtoBuf.class` I'm guessing the proto file you are **really** using contains options like `option csharp_namespace = "namespace Movalia.ProtoBuf.class";` instead of `option csharp_namespace = "xxx";`. And if I use a proto file like that I get the same generated code as you do, which does not build.
This is the source of the problems in your generated code as `class` is a keyword in C# and it's not allowed in namespaces' names.

If you simply change your option to `option csharp_namespace = "namespace Movalia.ProtoBuf.Class";` (Class with a capital c) then your generated code will build.

**Comment by RedElectricity** [comment]
It works, tks
