### ISSUE TITLE
Text format support for serialized messages in bytes fields

### ISSUE THREAD

**Issue by barryam3** [protocolbuffers/protobuf#10252]
**What language does this apply to?**
This change applies to the text format.

**Describe the problem you are trying to solve.**

I have a `bytes` field whose value is expected to be a serialized message.

```proto
message MyMessage {
  // A serialized protocol buffer message.
  bytes serialized_message = 1;
}
```

The only way to specify the value of a bytes field in the text format is as a string. For example, if I want to encode a `google.protobuf.Duration` message representing 3.14 seconds, I need to write this.

```textproto
serialized_message: "\b\003\020\200\366\340B"
```

This is effectively impossible to do without specifying the message in another text format file, serializing it, and copying the result in. It's also difficult to decipher on inspection. I can add a comment, but that adds visual clutter, and comments can become out of sync.

**Describe the solution you'd like**

I'd like to be able to specify the value of a bytes field that is a serialized message using a syntax similar to `google.protobuf.Any`.

```textproto
serialized_message: [type.googleapis.com/google.protobuf.Duration] {
  seconds: 3
  nanos: 140000000
}
```

**Describe alternatives you've considered**

I'll defer to your judgment on syntax but otherwise this seems like an accept it or reject it kind of proposal.

**Additional context**

*Why not use `google.protobuf.Any` instead of `bytes`?*

I suspect my use case is rather advanced. The `bytes` field is used in a way that does not involve descriptors, so the `type_url` is irrelevant. I'm not going to expand further on GitHub, but a Googler can reach out to me within Google if they want more details.

*Couldn't you just use `Any` and ignore `type_url`?*

Yes, that would probably work, but these `bytes` fields were added years ago and will probably last for years for backwards compatibility reasons. Meanwhile, people need to fill them in test fixtures.

**Comment by acozzette** [comment]
Sorry but I'm afraid we will not be implementing this feature request. I can understand the motivation, but changing any format is a major undertaking (has to be replicated in all languages we support) and therefore has to have an extremely compelling justification.

If the field always stores the same type, then one possible workaround would be to simply update this `bytes` field to directly use the expected message type. This change would be wire-compatible because the wire format for a message field looks exactly like a bytes field containing the serialized message.

**Comment by barryam3** [comment]
The field does not always store the same type.

Thanks for the consideration.
