### ISSUE TITLE
Imports (in nested sub-directories) within compiled `*_pb2.py` and `*_pb2.pyi` cannot be resolved on Python 3

### ISSUE THREAD

**Issue by Atokulus** [protocolbuffers/protobuf#10329]
Dear Protobuf community

I hope you are all doing well 😉

## The Issue
```
Version: Protoc v3.20.1
Language: Python (Python 3.10.5)
OS: Windows/Linux/macOS
```

For quite long I have been facing a problem where imports (from and to nested sub-directories) within compiled `*_pb2.py` and `*_pb2.pyi` Protobuf files/modules generated from `protoc --python_out --mypy_out` cannot be resolved in my projects.

E.g. you might have the following file/module structure:

- `./`
  - `a_pb2.py`
  - `b_pb2.py`
  - `./sub/`
    - `c_pb2.py`
    - `./nested/`
      - `d_pb2.py`
      - `__init__.py`
    - `__init__.py`
  - `__init__.py`

Now assume, `c.proto` is importing `a.proto`, `b.proto` and `d.proto`.

`protoc` will generate the following import statements for `c_pb2.py`:

```python
# c_pb2.py

from google.protobuf import descriptor as _descriptor

import a_pb2 as a__pb2
import b_pb2 as b__pb2

from sub.nested import d_pb2 as sub_dot_nested__d__pb2

# ...
```

Using these modules will not work under Python 3, as the imports are not relative. Nested imports are working for `--dart_out` and we extensively use a nested directory structure, to cope with project complexity.

I there any way to generate *correct* imports with the Protoc Python generator in the future?

## A Workaround

As it can get quite cumbersome to fix these issues, I came up with a script that will fix the imports (https://pypi.org/project/fix-protobuf-imports/):

```bash
fix-protobuf-imports /path/to/python_out/dir
```

This will result in the following working imports:

```python
# c_pb2.py

from google.protobuf import descriptor as _descriptor

from .. import a_pb2 as a__pb2
from .. import b_pb2 as b__pb2

from ..sub.nested import d_pb2 as sub_dot_nested__d__pb2

# ...
```

## Regards

Many thanks for checking this issue and best regards to you all 😄
Markus

**Comment by kurtraschke** [comment]
See #1491, #4614, #5374, etc.

**Comment by arthur-tacca** [comment]
I don't think protbuf is trying to do anything relative (or relative-like). For example, with the files you suggested, if c.proto were to import d.proto then you'd find the generated python would look for `sub.nested.d` – not just `sub.d` as yours expect if it were attempting to do a relative import. Similar, in the actual proto, you'd need to write `import "sub/nested/d.proto"`.

Basically the whole path (relative to some root) is part of the canonical name of that file. That applies equally in both the proto and the Python. If your protoc include directory and Python path is set correctly then this all works fine. I haven't looked at your script to "fix" things

**Comment by arthur-tacca** [comment]
protobuf is not trying to do anything relative (or relative-like). It was always absolute, even in Python 2, and the changes to the import system in Python 3 have just exposed an existing mistake in the way you were using it.

For example, with the files you suggested, if c.proto were to import d.proto then you'd find the generated python would look for `sub.nested.d_pb2` – not just `nested.d_pb2` as you'd expect if it were attempting to do a relative import. Similarly, in the actual proto, you'd need to write `import "sub/nested/d.proto"`.

Perhaps your issue is that your protos are in a subdirectory of your code, and you import them with code like `import protos.a_pb2`. In that case `protos` is part of their canonical names, and so ought to be part of the path of the proto files too (relative to an include root that you pass to protoc).

Another common pitfall, which could possibly be the source of your issue, is that Python assumes that your main source root is the directory containing the file you pass on the command line, rather than the current directory. So in your example, if the current directory is your root (i.e. contains `a_pb2.py`), then `python a_pb2.py` would follow imports fine but `python ./sub/c_pb2.py` then it would fail with an `ImportError` trying to find `d_pb2`. One workaround is to move all your scripts into the conceptual root. Another is to run them as a module with the -m switch (which actually does use the current directory as a module root): for example, `python sub.c_pb2` would work.

**Comment by sbrother** [comment]
This has been a bug for [many, many years](https://github.com/protocolbuffers/protobuf/issues/1491). It comes down to the fact that the way Python (and protobufs) are used inside Google is very different from how the external world works. The solution is to use [betterproto](https://github.com/danielgtaylor/python-betterproto), or if you want to stick with the first-party python proto library, then to use [protoletariat](https://pypi.org/project/protoletariat/) to fix its output.
