### ISSUE TITLE
C++ Question: How can I get an enum's Foo_MAX value directly with reflection from it's type?

### ISSUE THREAD

**Issue by AlexEvansRaven** [protocolbuffers/protobuf#10333]
I want to add some additional c++ safety type checking for various specialized casts of enums to other fixed width integral types(ex `uint8_t`).  But I want to disallow any narrowing conversions that can't fit the max enum range.  I am grabbing the type information dynamically with the casts function template parameter as `EnumType`, checking, and then checking with a `static_assert ` if `google::protobuf::is_proto_enum<EnumType>::value == true` I get the descriptor via `google::protobuf::GetEnumDescriptor<EnumType>()`.  

From there it becomes less clear how to proceed though.  Ideally I could do something like `google::protobuf::GetEnumDescriptor<EnumType>()->getEnumMax()` and `google::protobuf::GetEnumDescriptor<EnumType>()->getEnumMin()` or even `google::protobuf::GetEnumDescriptor<EnumType>::ENUM_MAX` and `google::protobuf::GetEnumDescriptor<EnumType>::ENUM_MIN` which would just be constexpr getters or constants or something for Foo_MAX and Foo_MIN but I don't seen anything like that in the API?

Currently I have figured out I can use `EnumValueDescriptor* value(int)` to iterate over the `google::protobuf::EnumValueDescriptor`, but this is not ideal as I need to iterate over each enum value and track the min/max, so even if I cache it at least on the first use for this function, I will take a performance hit.  Additionally this bounds me to using runtime style `<cassert>` rather than compile time `static_assert()` which is undesirable as this information is known at compile time.  Is there a way to get this info at compile time?  If not can I request one?

**Comment by acozzette** [comment]
Unfortunately I don't think there is currently a better way to do this than to iterate over the `EnumValueDescriptor`s and look for the maximum.

Depending on what you're trying to do, though, it may be difficult to make assumptions about the range of an enum. Every proto enum is declared to be of size `int` (e.g. `enum MyEnum : int { ...`), so the C++ language will let you store any value that would fit in an `int`. In practice, this probably isn't something to worry about in proto2, since proto2 enums are "closed" and if you call a enum accessor on a message then you are guaranteed to get a value that's in the defined range. (This creates a whole other set of problems since unknown enum values are silently stored in the unknown field set, though.) In proto3, enums are "open" so they can actually store an arbitrary int, even if it's not explicitly named in the .proto file. So in proto3 it would generally not be safe to make any assumptions about the possible value stored in an enum.

**Comment by AlexEvansRaven** [comment]
I see.  Thank you for pointing that out.  I hadn't considered the underlying value may have enums that don't conform to the definition.  So because the underlying type may contain data not explicitly specified in the .proto ranges I would need to consider the entire width of the underlying type, which is int, and take the `numeric_limit<int>::max()` and `::min()` of that if I wanted to be safe... or discard values if `Foo_isValid()` fails and return some kind of out of bounds error... but there is no good way to get at `Foo_isValid()` here either...  I guess as I'd need the actual value that part _has_ to be runtime, or this can only be used with trusted input.... hmmm...I guess for now I'll just keep iterating over the `EnumValueDescriptor`s at runtime and add a validity check based off of that as well to verify it's in bounds.  For my particular case I fortunately don't care about skipped values...
