### ISSUE TITLE
Bazel build config is wrong for Mac OS

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#10427]
**What version of protobuf and what language are you using?**
Version: main
Language: N/A

**What operating system (Linux, Windows, ...) and version?**
Mac OS 12.5

**What did you do?**
I am trying to run tests locally, to test a patch. I am on a 2022 M1 Pro MBP.
```shell
bazel test //..
```

**What did you expect to see**
I was hoping this would run tests 😝 

**What did you see instead?**
This failed, complaining about configuration in `toolchain/BUILD.bazel`:
```
ERROR: /Users/jhumphries/src/protobuf/toolchain/BUILD.bazel:20:19: in cc_toolchain_suite rule //toolchain:clang_suite: cc_toolchain_suite '//toolchain:clang_suite' does not contain a toolchain for cpu 'darwin_arm64'
```
I was able to edit this build file a bit to get it to run successfully:
```diff
diff --git a/toolchain/BUILD.bazel b/toolchain/BUILD.bazel
index b171c227b..98927ceef 100644
--- a/toolchain/BUILD.bazel
+++ b/toolchain/BUILD.bazel
@@ -6,7 +6,8 @@ filegroup(name = "empty")
 
 TOOLCHAINS = {
     "osx-x86_64": "cc-compiler-osx-x86_64",
-    "osx-aarch_64": "cc-compiler-osx-aarch_64",
+    # "osx-aarch_64": "cc-compiler-osx-aarch_64",
+    "darwin_arm64": "cc-compiler-osx-aarch_64",
     "linux-aarch_64": "cc-compiler-linux-aarch_64",
     "linux-ppcle_64": "cc-compiler-linux-ppcle_64",
     "linux-s390_64": "cc-compiler-linux-s390_64",
@@ -89,7 +90,8 @@ cc_toolchain_config(
 )
 
 cc_toolchain_config(
-    name = "osx-aarch_64-config",
+    # name = "osx-aarch_64-config",
+    name = "darwin_arm64-config",
     extra_compiler_flags = [
         "-I/usr/tools/apple_sdks/xcode_13_0/macosx/usr/include/c++/v1",
         "-I/usr/tools/apple_sdks/xcode_13_0/macosx/usr/include"
```
I do not have an x86 Mac for testing the "osx-x86_86" configuration, but I'm sure it's wrong as well. Or maybe whatever is computing the "darwing_arm64" string is what is at fault, since it is not computing the expected "osx_aarch_64" string?

Anyhow, after the above patch, I still get errors due to other dependencies on `realpath`, `dotnet`, `phpize`, and `pcre2.h`. So the [directions for Mac OS](https://github.com/protocolbuffers/protobuf/blob/main/src/README.md?plain=1#L67) should probably also mention doing the following in order to successfully run tests (or better yet: these dependencies should somehow be captured in the Bazel configs, for maximum hermeticity):
```shell
# coreutils is for `realpath` program
brew install coreutils dotnet php pcre2 openjdk
sudo gem install rake-compiler

# this is kind of smelly, but is what I found to fix "'pcre2.h' not found" errors
PCRE2_VERSION=$(brew list --versions pcre2 | awk '{ print $2 }')
PHP_VERSION=$(brew list --versions php | awk '{ print $2 }')
ln -s /opt/homebrew/Cellar/pcre2/$PCRE2_VERSION/include/pcre2.h \
    /opt/homebrew/Cellar/php/$PHP_VERSION/include/php/ext/pcre/pcre2.h 
```
Obviously things like dotnet, PHP, and a JDK can be installed via some other mechanism. (I actually installed the JDK from an Oracle installer and am not currently using OpenJDK.)

With all of the above, I was _finally_ able to build and run all of the tests (w00t!). However, three targets failed, all for C#!
```
//csharp:conformance_test                                                FAILED in 15.9s
//csharp:tests                                                           FAILED in 0.7s
//csharp/compatibility_tests/v3.0.0:tests                                FAILED in 0.3s

Executed 228 out of 228 tests: 220 tests pass, 3 fail locally and 5 were skipped.
```

Luckily, I am not working on the C# runtime, so I'm okay with this outcome 😄

**Comment by mkruskal-google** [comment]
Hey Joshua,

I think the big issue here is that you tried to run *all* our tests via Bazel.  A lot of these are still a work in progress and require some very specific flags or environments (see our kokoro tests for some examples).  I plan to do a pass over everything so that `bazel test //...` only runs tests that are compatible, but we're not there today.  To run C++, Python, or Java tests you should scope the command to the relevant directories (e.g. `bazel test //src/...`)

**Comment by jhump** [comment]
@mkruskal-google, that's fair regarding all of the dependencies (so you'd only install the ones you need based on which tests you are trying to run). But the the toolchain stuff still looks to be broken for Mac OS.

I tried to run everything just to make sure I had a functioning install/build. (I was about to make a pull reuest, and was doing some prep to make sure I'd be able to run tests... didn't yet know what tests I'd be running.)

**Comment by mkruskal-google** [comment]
Yea the toolchain stuff is *completely* broken outside of our internal test environment!  It wasn't designed to ever be used externally, and the only reason you're trying to run those tests is because of the `...` wildcard.  I think marking some of these broken targets with a `manual` tag to prevent wildcard expansion would be reasonable.  I already made an attempt to mark `compatible_with` where appropriate, but as you've noticed I missed a lot.

Long-term, I'd like to write a test that just runs *everything* under `//...`, to keep that in a good state.  But we have a lot more work to do towards Bazelification, so that may be a while.  Until then, I would stick to top-level directories only and relying on our PR presubmits.  Ruby and C# require some awkward configuration for bazel tests, and Objective-c only runs on Mac.  But the following command should be sufficient for qualification:

`bazel test //src/... //python/... //java/...`

And maybe throw in `//objectivec/...` on mac.

**Comment by mkruskal-google** [comment]
@deannagarcia In case I'm misrepresenting the toolchain files
