### ISSUE TITLE
JSON parsing of large 32-bit floating point values fails.

### ISSUE THREAD

**Issue by jskeet** [protocolbuffers/protobuf#10509]
The proto3 JSON spec doesn't give very much guidance on *exactly* how floating point values are represented.

The maximal finite 32-bit floating point value is precisely 340282346638528859811704183484516925440. Both .NET and (I believe) Go format this as 3.4028235e+38.

Unfortunately that fails to round-trip in .NET, because of the way we handle JSON parsing of 32-bit floating point numbers:

- Parse as a 64-bit float
- Compare with the maximal 32-bit float - if it's less than or equal, proceed, otherwise throw an exception

There are 64-bit floating point values closer to 3.4028235e+38 than the max 32-bit value, so we end up throwing an exception.
We should, instead, try casting to `float` and see whether the result is infinite.

**Comment by jskeet** [comment]
@mcy: This feels like something that could usefully be in the JSON conformance test suite. (I'm adding unit tests to the C# code of course.)

**Comment by haberman** [comment]
The conformance tests already have a "max float" case, but they are testing for `3.402823e+38` rather than `3.4028235e+38`: https://github.com/protocolbuffers/protobuf/blob/f8be28167c151846a911a6b33ea35d8ea8e3990b/conformance/binary_json_conformance_suite.cc#L2085-L2088

Also it appears the min float case has a copy-and-paste bug, where it's accidentally checking the max float value again: https://github.com/protocolbuffers/protobuf/blob/f8be28167c151846a911a6b33ea35d8ea8e3990b/conformance/binary_json_conformance_suite.cc#L2089-L2092

**Comment by jskeet** [comment]
@haberman: Would you like me to make changes in that file in #10514, or should we keep that separate?
