### ISSUE TITLE
C# .NET deserialization of message that contains self-defined message type field and empty value field, decodes incorrectly

### ISSUE THREAD

**Issue by greyDoll** [protocolbuffers/protobuf#10630]
**What version of protobuf and what language are you using?**
Version: v3.5.1
Language:C++/C#

**What operating system (Linux, Windows, ...) and version?**
Win10

**What runtime / compiler are you using (e.g., python version or gcc version)**
msvc

**What did you do?**
Hi, jskeet~
The problem performed like this: i use language C++ to serialize a message to a file named 'a.label', however, when i deserialize 'a.label' to a message in language C#, i get a incorrect result, details are as follows:
the .proto file contents is:
```
syntax = "proto3";
import "google/protobuf/any.proto";

message Rect2f {
    float w= 1; 
    float h= 2;
}
message Shape{
    enum ExampleType{
        Type1= 0;
        Type2= 1;
    }

    ExampleType data_type = 1;
    Rect2f rect_size = 2;

    google.protobuf.Any origin = 3;
}
```
I serialize or deserialize Shape message in C++, the result is:
```
 {"data_type":"Type1","rect_size":{"w":300,"h":400}, "origin":{}}
```
but when i serialize Shape message in C++ and deserialize it in C#, i get this: 
```
{ "dataType": "Type1", "rectSize": { "w": 300, "h": 400 }, "origin": { "@type": "", "@value": "" }}
```
it looks like some key fields are changed: data_type-->dataType, rect_size-->rectSize, empty value field is changed: "origin":{}-->"origin": { "@type": "", "@value": "" }.
By the way, theye are many blank spaces appearing in result, i wonder the essential reason.

**What did you expect to see**
```
 {"data_type":"Type1","rect_size":{"w":300,"h":400}, "origin":{}}
```

**What did you see instead?**
```
{ "dataType": "Type1", "rectSize": { "w": 300, "h": 400 }, "origin": { "@type": "", "@value": "" }}
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

- use function SerializeToArray(...) to serialize message in C++;
- write the file as "std::ofstream::binary" in C++;
- use function Parser.ParseFrom(data_bytes) to deserialize message in C#, the type of parameter data_bytes is byte array.

Looking forward to the reply, thank you.

**Comment by jskeet** [comment]
It would really help if you could provide a sample file for me to try to parse from C#.

**Comment by greyDoll** [comment]
Of course, moments need to wait, cause there is only complete .label file for my own project, i will show you a sample .label file soon.

**Comment by greyDoll** [comment]
I'm sorry for the late uploading, sample file named "1.log" is provided. By the way, i saved this file with '.log' suffix due to github file type support.
[1.log](https://github.com/protocolbuffers/protobuf/files/9642457/1.log)

**Comment by jskeet** [comment]
Unfortunately that link gives me a 404. Are you able to upload and share a file on Google Drive?

Looking again at your question, I think this *may* just be a matter of how an `Any` is represented in JSON in C#. I don't think it's actually *decoding* the `Any` incorrectly - it just isn't showing what you'd expect in JSON.

We can look at that (encoding an `Any` without a type URL as just `{}` rather than exposing the blank type and value) but I strongly suspect that's the problem rather than the *decoding* side being wrong. That means you should be able to work with the data in C# without any problems, *other* than when you encode it as JSON (if you even need to do that).

Here's a simpler repro of it, in C#:

```csharp
using Google.Protobuf.WellKnownTypes;

var any = new Any();
Console.WriteLine(any);
```

That prints `{ "@type": "", "@value": "" }` where it sounds like you'd expect it to print `{}`.

An alternative way of addressing this is not to populate the field *at all* in the C++ code unless you have a valid value to "pack" into the `Any`. This is effectively an invalid `Any` value, given that it doesn't have a type URL or any serialized data.

**Comment by jskeet** [comment]
I'm going to close this, as internal discussions have suggested that we should really be failing to serialize an "empty" Any value to JSON entirely... so both the C++ and C# behavior here would be viewed as "wrong". That will be fixed as part of a larger JSON consistency drive.

The solution is just to not populate a field with an Any unless you have a *real* Any value.
