### ISSUE TITLE
Build error when trying to build for Android with IL2CPP in Unity 2021

### ISSUE THREAD

**Issue by boasbakker** [protocolbuffers/protobuf#10654]
[Build error Protobuf in Unity 2021 Android IL2CPP.txt](https://github.com/protocolbuffers/protobuf/files/9638531/Build.error.Protobuf.in.Unity.2021.Android.IL2CPP.txt)
This is the error

Fatal error in Unity CIL Linker
System.NullReferenceException: Object reference not set to an instance of an object.
at Unity.Linker.Analytics.AnalyticsService.RecognizedReflectionAccessPattern(IMemberDefinition source, Instruction sourceInstruction, IMetadataTokenProvider accessedItem)
The rest is in the text file
[ExampleProject.zip](https://github.com/protocolbuffers/protobuf/files/9638533/ExampleProject.zip)
I also uploaded an example project
I am using:
protobuf-net.core.3.1.22
protobuf-net.3.1.22
system.collections.immutable.6.0.0
system.runtime.compilerservices.unsafe.6.0.0
Unity 2021.3.10f1

**Comment by boasbakker** [comment]
[ExampleProject.zip](https://github.com/protocolbuffers/protobuf/files/9638540/ExampleProject.zip)
Made a mistake in the example project

**Comment by conmilo** [comment]
@boasbakker This may be a Unity issue. See [here](https://issuetracker.unity3d.com/issues/il2cpp-build-fails-with-fatal-error-in-unity-cil-linker-when-using-unitylinker) and [here](https://forum.unity.com/threads/in-14788-failed-to-build-player-when-using-il2cpp.1327230/). Maybe you can roll back to Unity 20201.3.9f1 until the fix is released

**Comment by googleberg** [comment]
Is this for protobuf? Or for protobuf-net?
