### ISSUE TITLE
Java: `getFieldOptional` for optional message fields

### ISSUE THREAD

**Issue by TheKeveloper** [protocolbuffers/protobuf#10692]
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?
**Java** 

**Describe the problem you are trying to solve.**
Currently if I want to create an `Optional<MyField>`, I usually have to do something like
```
Optional<MyField> maybeField = myMessage.hasMyField() ? Optional.of(myMessage.getMyField()) : Optional.empty();
```
which is pretty verbose.

Another, less important issue, is that it would be nice to be able to set an `Optional<Message>` for optional fields in the builder. Currently I have to do something like,

```
Optional<MyField> maybeField = ...;
MyMessage.Builder builder = MyMessage.newBuilder();
maybeField.ifPresent(builder::setMyField);
```

**Describe the solution you'd like**
Add a `getFieldOptional` that returns an optional with the value if provided and `Optional.empty()` otherwise. Then the above would become:

```
Optional<MyField> maybeField = myMessage.getMyFieldOptional();
```

To solve the builder issue, we could generate an overload of `setField(MyField field)` that is `setField(Optional<MyField> field)` that sets the field if the optional is non-empty, and unsets the field if the optional is empty. 

**Describe alternatives you've considered**

Instead of using Java optionals, we could also just do something like `getFieldOrNull` as there is currently in Kotlin and have the caller wrap with `Optional.ofNullable`, but it feels preferable to me to force the user to explicitly handle the empty case by returning an `Optional`. 

**Additional context**

This seems similar to `getFieldOrNull` recently implemented for Kotlin: https://github.com/protocolbuffers/protobuf/issues/8676.

This also should be a backwards compatible change.

**Comment by fowles** [comment]
While I understand the desire, this idea has been considered in the past and we have made a deliberate decision not to do it.  The major points in this decision are:

- Adding new methods per field has a significant cost in terms of the size of generated code.  Size of generated code is an important property for Android .apk size and thus android app start-up time.
- optional causes a double indirection since it is functionally boxing the pointers in java.  The performance negatives are not good.

Kotlin avoids the second point by having nullability in its type system.  The first point is mitigated (but not fully resolved) through tree shaking, unused method stripping, and inlining.

**Comment by fowles** [comment]
Kotlin has "inline" methods which forcibly inline into callers and don't really exist at the JVM level.
