### ISSUE TITLE
libprotobuf version mismatch

### ISSUE THREAD

**Issue by Thunder-29** [protocolbuffers/protobuf#10761]
Hi Everyone,

I am getting this error while running some testcases from my application as:

**[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/stubs/common.cc:86] This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.9.2).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/build/dldt/_deps/ext_onnx-build/onnx/onnx_ngraph_onnx-ml.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.7.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.9.2).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/build/dldt/_deps/ext_onnx-build/onnx/onnx_ngraph_onnx-ml.pb.cc".)
Aborted (core dumped)**

System Information:
OS - Ubuntu 20.04 LTS

I tried with installing both version 3.7.1 and 3.9.2 on my system, but still facing the same error.
I uninstalled both protobuf libs now for protoc --version I am getting 
**Command 'protoc' not found, but can be installed with:

sudo snap install protobuf           # version 3.14.0, or
sudo apt  install protobuf-compiler  # version 3.6.1.3-2ubuntu5

See 'snap info protobuf' for additional versions.**

How can i resolve this error.

Thank you

**Comment by mkruskal-google** [comment]
Those are both very old versions, so I could be mistaken.  However, IIUC the error you're hitting is caused by a mismatch between the C++ runtime libraries and headers.  It's actually independent of protoc, so the fact that you've managed to uninstall protoc doesn't necessarily mean you've cleaned up all the cruft.

I suspect you have libraries or headers from different versions hanging around somewhere on your path, masking the correct ones.  You could try searching for "libprotobuf" or "google/protobuf/message.h" on your computer to try to find these remnants
