### ISSUE TITLE
protoc requires files as if they were gems

### ISSUE THREAD

**Issue by kailan** [protocolbuffers/protobuf#1137]
One of my proto files contains this line: `import "api.proto";`
This gets compiled to Ruby like this: `require 'api'`

This causes an error when requiring those files because it tries to load 'api' as a gem. It would be better for the compiler to generate `require_relative 'api'` instead.

**Comment by aaomidi** [comment]
+1

**Comment by kblanks** [comment]
I'm working on a PR for this right now.

**Comment by Zhomart** [comment]
I ended up using `$:.unshift File.expand_path('../my_proto_files', __FILE__)`.

**Comment by kblanks** [comment]
Yeah, that's also what I've been doing for now.

**Comment by marcinwyszynski** [comment]
I just opened PR #2477 for that.

**Comment by djudd-stripe** [comment]
I'm pro adding a compiler option as discussed in https://github.com/google/protobuf/pull/1138 ("What if someone wants to put generated code into a gem, or install it into a system location?")

I have a use case where I'm importing a bunch of Protos and then generating Ruby for them, and I'd rather not mess with the load path because it's controlled by an autoloader. Currently I'm using a regex to replace the `require`s with `require_relative`s, but an option I can pass protoc would be nicer.

**Comment by gaffneyc** [comment]
I would like this option as well. We're using protobufs with a Rails and placing them in a subdirectory based on the package name (e.g. `lib/dms/rpc/dispatch`) for consistency with other files.

Adding a flag for switching to `require_relative` would work for us but I would like to propose another option:

```
// Use this option to control how Ruby dependencies are required. Default is
// empty which will require dependencies as if they were in the LOAD_PATH.
//
// Options
//   "path" or unset: Require dependencies on the load path
//   "relative": Use require_relative to find dependencies relative to the
//               current file.
//   "none" or false: Don't require dependencies
option ruby_require = "relative";
```

**Comment by hatstand** [comment]
I started work on this in https://github.com/protocolbuffers/protobuf/pull/6879

**Comment by elharo** [comment]
@haberman Is this still relevant?

**Comment by haberman** [comment]
I don't think we should emit `require_relative`. Protos should be given full path names just like any other source file.

It's important that these path names are unique; a filename like `api.proto` will confict if any dependency also has a filename `api.proto`. The filename should be something like `myproject/api.proto`, such that the base directory is in the load path.

**Comment by nvolker** [comment]
Hey there @haberman! I see you closed this issue, however, while compiling to ruby I've run into the same issue whereby the compiler uses `require` rather than `require_relative` which is causing my rails console/server to crash loading due to a **LoadError**:
```
/Users/username/.rvm/gems/ruby-3.0.3/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- somedir/header_pb (LoadError)
```

Given this issue was closed, what is the proposed solution here? I'm not seeing anything useful to help me overcome this issue without hacking something together in my compile script.

**Comment by haberman** [comment]
HI @nvolker. Is `somedir`contained within a directory that is in your RUBYLIB?

The protobuf language requires that all imports use full names. Protobuf does not have a concept of relative imports.

For example, if you had both `foo/somedir/header.proto` and `bar/somedir/header.proto`, both imported as `somedir/header.proto`, that would be problematic for the protobuf runtime. That's why we require full import names, and not relative.

**Comment by gaffneyc** [comment]
@haberman I believe this has to do with a misunderstanding on how / where to generate files from. If you run `protoc` in the directory that contains the `.proto` file then it generates an unpathed `require` as the generated path is relative to the current directory (or is it proto path?). I did this for a long time thinking of proto definitions as generator instead of a part of the app as a whole.

The suggestion should be to run protoc from a parent directory (e.g. root or lib) and set the proto_path. Import paths should also be relative from that top level directory.

For example, in our Rails app, we have protobuf definitions under lib which is on the load path. 
```
lib/dms/api/foo.proto
lib/dms/api/bar.proto
```

bar.proto imports foo
```
import "app/dms/foo.proto"; // Relative to lib
```

From the project root you then use protoc to generate the definitions.
```bash
protoc --proto_path=lib --ruby_out=. lib/dms/api/*.proto
```

This will create a `lib/dms/api/bar_pb.rb` file that contains an appropriate require line for the load path.
```ruby
require "dms/api/foo_pb"
```

@nvolker That looks like `somedir` is not in the load path or is in a subdirectory of the load path. For a Rails app that is `lib` and every directory in `app` by default. What are the paths relative to the root and what directory are you generating them from?

**Comment by haberman** [comment]
@gaffneyc that is an excellent summary of the situation. And I agree with your recommendation of how `protoc` should be invoked. Proto files should be thought of as part of the app as a whole.

**Comment by nvolker** [comment]
Appreciate the replies, this makes perfect sense and has resolved my issues (the adopted file structure and script were not implemented to accommodate this need). Thanks a bunch, @gaffneyc and co.

**Comment by nvolker** [comment]
@gaffneyc just as a follow-up on the question you asked about subdirectories. Yes, the output was being stored in a subdirectory, and not in `lib`, hence the issue with `require` as it would not account for the subdirectory in the `--ruby_out` argument. So, naively (protoc novice here), using your example:
```
protoc --proto_path=lib --ruby_out=. lib/dms/api/*.proto
```

Great, I get this working result:
<img width="433" alt="Screenshot 2022-01-11 at 15 27 11" src="https://user-images.githubusercontent.com/45795784/148950892-3550f6bd-1707-4a83-bf8d-be3d32c4b553.png">

However, now let's say that for whatever reason I'd like to store the compiled ruby output in a couple of subdirectories (requiring me to manually create `somedir` & `anotherdir`):
```
protoc --proto_path=lib --ruby_out=./somedir/anotherdir lib/dms/api/*.proto
```

I get this result, with the same `require 'dms/api/foo_pb'`:
<img width="1173" alt="Screenshot 2022-01-11 at 15 29 39" src="https://user-images.githubusercontent.com/45795784/148951870-0b882ea5-fe5e-4cef-9251-286ddf91c842.png">

Naively, I'd expect the `require` to account for the inclusion of subdirectories:
```ruby
require 'somedir/anotherdir/dms/api/foo_pb'
```

**Comment by gaffneyc** [comment]
@nvolker It looks like it's creating the files in the current directory instead of lib. Try using `--ruby_out=lib` instead.

I had done some testing and looks like I had old files sitting around when I used `--ruby_out=.` from the root directory. I've updated my comment above as well.

**Comment by nvolker** [comment]
Fair play, but the problem with the `require` still persists. Continuing from the same example, even if the output is stored in the `lib` directory, the `require` still runs into the same **LoadError** on application startup due to the missing of the subdirectories (L#6):
```
protoc --proto_path=lib --ruby_out=lib/somedir/anotherdir lib/dms/api/*.proto
```
<img width="1449" alt="Screenshot 2022-01-11 at 17 50 20" src="https://user-images.githubusercontent.com/45795784/148975994-c18b629f-d61b-41eb-b1b6-8fc86f586713.png">

**Comment by gaffneyc** [comment]
@nvolker That's creating `lib/somedir/anotherdir/dms/api`. Try just `--ruby_out=lib` as I suggested. At this point I don't think you're fighting with protobufs so much as understanding how Ruby finds and loads required code.

**Comment by MatthewSerre** [comment]
@gaffneyc I came across this thread after trying to understand why I couldn't load my Ruby files in irb without an error.  I tried recreating the same directory structure and files you specified above, but I am not sure where I am going wrong.  See the included screenshot.

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/18296761/192908722-f7af71b7-0e83-409c-b424-65f530a868e7.png">
