### ISSUE TITLE
we have some memoey leak in php-cli mode

### ISSUE THREAD

**Issue by zhanchao234** [protocolbuffers/protobuf#11464]
test proto message:

```proto
message MemoryLeakTestMsg {
  repeated int32 numbers = 1;
}
```

php test class:

```php
class MemoryLeaktest{
protected $_memory_leak_test_msg;
protected $_rand_arr = [];

public function __construct(){
	$this->_memory_leak_test_msg = new MemoryLeakTestMsg();

	for($i=0;$i<20;$i++){
		$this->_rand_arr[] = mt_rand(1,30000);
	}
}

public function TestProto(){
	$this->_memory_leak_test_msg->clear();
	$this->_memory_leak_test_msg->setNumbers($this->_rand_arr);
	$this->_memory_leak_test_msg->serializeToJsonString() . "\n";
	return $this->_memory_leak_test_msg;
}

public function ResetProto(){
	$this->_memory_leak_test_msg = new MemoryLeakTestMsg();
}
}
```

php script:
```php
$start = microtime(true);

$test = new MemoryLeaktest();

$cnt = 0;

while (1) {
  $rt = $test->TestProto();
  $cnt++;
  if($cnt % 100000 == 0){
    $end = microtime(true);
    echo $cnt.'use time:'.round(($end-$start)*1000,2).'ms'."\n";
    //$test->ResetProto(); //if open this code comments,the program will be ok
  }
}
```

php version is 7.4.33, protobuf version is 3.21,centos 7.9
run the script with command 'php -f test.php'
the program memoryusage will always bigger.

I run the same code in workerman https://github.com/walkor/workerman ,the process will crash with no memory to use

**Comment by zhanchao234** [comment]
the repeated field in message or nested message seems to cause the problem

**Comment by haberman** [comment]
This is an expected result of the way that the PHP extension manages memory.

In this code example we have a long-lived message object `$test->_memory_leak_test_msg`. The code repeatedly creates and destroys the `numbers` field. The PHP extension uses arenas to allocate the memory instead of GCing every object individually, so every `RepeatedField` object ends up in a single arena, the same arena used by the message. The arena is not freed until the message is freed.

The best workaround is to periodically clone the message with parse and serialize:

```php
public function ResetProto(){
        $new_Msg = new MemoryLeakTestMsg();
        $new_msg->mergeFromString($this->_memory_leak_test_msg->serializeToString());
	$this->_memory_leak_test_msg = $new_msg;
}
```

The new message will not share an arena with the old message, so the old message's data can be freed immediately.

This issue and workarounds need to be documented better: https://github.com/protocolbuffers/protobuf/issues/10359

**Comment by zhanchao234** [comment]
thanks for the suggestions
