### ISSUE TITLE
TensorFlow Object Detection API Installation doesn't work with new versions 

### ISSUE THREAD

**Issue by Leci37** [protocolbuffers/protobuf#11523]
I have followed the complete installation of 
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html 
TensorFlow Object Detection API Installation 

after 2 days I have discovered that the latest 22.x.x versions of protobuf are not compatible and give error

to install TensorFlow Object Detection API Installation **I had to install version 3.12.2 protobuf** .

**Comment by jorgbrown** [comment]
Hmm....

I went to that page, https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html , and there was an "Edit on GitHub" link at the top of it.

So i clicked it, and it took me to the  https://github.com/sglvladi/TensorFlowObjectDetectionTutorial/ repo.

But that repo hasn't been edited since Nov 2021.

Therefore, I would say this is not a protobuf bug.  It's just old documentation.
