### ISSUE TITLE
Invalid Any type reference in go

### ISSUE THREAD

**Issue by comdiv** [protocolbuffers/protobuf#11558]
All my team installs `protoc` and `protoc-gen-go` same way:

1. install `protoc` from https://grpc.io/docs/protoc-installation/, now version v3.21.12
2. install `protoc-gen-go` with `go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28`

All my teammates and CI got:
```
import(
   anypb "google.golang.org/protobuf/types/known/anypb"
)
```
but at my computer i got:
```
import (
    any1 "github.com/golang/protobuf/ptypes/any"
)
```

All checked - $GOPATH, $GOROOT, caches cleaned, mods cleaned - no existence of `github.com/golang/...` related staff on disk.
Github version protoc-gen-go was removed in 2021, no mods or bins of it in disk.

Any suggestions how could it be? Don't know if it's protoc-gen-go problem or it's of yours.

**Comment by zhangskz** [comment]
protoc-gen-go is deprecated and has been superceded by [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf).

It is recommended that you move to the new module since this one is deprecated. You can likely reach out to https://github.com/protocolbuffers/protobuf-go for additional support here.
