### ISSUE TITLE
Provide prebuilt packages for Windows arm64

### ISSUE THREAD

**Issue by ilya-lavrenov** [protocolbuffers/protobuf#12048]

**Comment by acozzette** [comment]
@ilya-lavrenov Can you provide some more detail on what kind of prebuilt packages you would like to see? Which language would these be for?

**Comment by ilya-lavrenov** [comment]
Hi @acozzette 

I expect protobuf can be released in archives https://github.com/protocolbuffers/protobuf/releases/tag/v22.0 for Windows ARM64.
I'm specifically interested in C++.

**Comment by acozzette** [comment]
`protobuf-22.0.tar.gz` and `protobuf-22.0.tar.gz` just contain source code and are not architecture- or OS-specific, so as far as I know they should work fine on Windows arm64. We don't publish a `protoc` binary for Windows arm64, but I would guess that this is fine since you would generally run `protoc` on your build machine but not your target platform. If you're working with C++ then it's easy to build protoc from source anyway.

**Comment by ilya-lavrenov** [comment]
> `protobuf-22.0.tar.gz` and `protobuf-22.0.tar.gz` just contain source code and are not architecture- or OS-specific, so as far as I know they should work fine on Windows arm64. We don't publish a `protoc` binary for Windows arm64, but I would guess that this is fine since you would generally run `protoc` on your build machine but not your target platform. If you're working with C++ then it's easy to build protoc from source anyway.

Windows ARM64 not not only target machine, but also a [development platform](https://developer.qualcomm.com/hardware/windows-on-snapdragon/windows-dev-kit-2023)
