### ISSUE TITLE
Java 3.22.1: broken pom.xml

### ISSUE THREAD

**Issue by xuwei-k** [protocolbuffers/protobuf#12170]
**What version of protobuf and what language are you using?**

Java 3.22.1

**What operating system (Linux, Windows, ...) and version?**

all

**What runtime / compiler are you using (e.g., python version or gcc version)**

**What did you do?**

use `protobuf-java-util` 3.22.1 with sbt

```scala
libraryDependencies += "com.google.protobuf" % "protobuf-java-util" % "3.22.1"
```

**What did you expect to see**

**What did you see instead?**

```
[error]   not found: https://repo1.maven.org/maven2/$com/google/protobuf/protobuf-java//protobuf-java-.pom
```

https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1.pom

<img width="537" alt="broken-pom-xml" src="https://user-images.githubusercontent.com/389787/223585176-64979062-ca25-4263-896c-2279fb02c2b4.png">

**Anything else we should know about your project / environment**

**Comment by XN137** [comment]
seeing same problem on 3.22.1, compare these poms:
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.0/protobuf-java-util-3.22.0.pom
https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.1/protobuf-java-util-3.22.1.pom

@deannagarcia i guess the problem was introduced [here](https://github.com/protocolbuffers/protobuf/commit/9b5a2c6f6fc76da3c93f6793550fa488ae62abaf) by using `${groupId}` instead of `{groupId}`

**Comment by deannagarcia** [comment]
Thanks for the report and diagnosing the issue, I see the error and am working on a fix now and we will get another release out with the fix.

**Comment by xenomachina** [comment]
FWIW, we're also running into this issue when building with gradle.

Both releases since the pom templates were added have broken our build: missing dependencies in 3.22.0, and now this in 3.22.1. Perhaps it would be worthwhile to diff the poms currently being generated against the corresponding poms from 3.21.12 (the last version before the poms started having issues) and confirm that every difference makes sense.

**Comment by xuwei-k** [comment]
👍 

- https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.22.2/protobuf-java-util-3.22.2.pom
- https://github.com/protocolbuffers/protobuf/pull/12194
- https://github.com/protocolbuffers/protobuf/pull/12177
