### ISSUE TITLE
Add automatic releases to bcr

### ISSUE THREAD

**Issue by malt3** [protocolbuffers/protobuf#12184]
**What language does this apply to?**

n/a

**Describe the problem you are trying to solve.**

The bazel central registry (bcr) version of protobuf is still at v21.7: https://registry.bazel.build/modules/protobuf.
Other bazel projects automate this step using a github app: [example](https://github.com/bazelbuild/bazel-central-registry/pull/332), [app](https://github.com/apps/publish-to-bcr).

**Describe the solution you'd like**

Adopt the automatic release

**Describe alternatives you've considered**

Perform a manual release for v22.1 (and maybe v22.0).

**Comment by deannagarcia** [comment]
Our team does not manage the protobuf bazel central repository. We are unfortunately unable to transition to using bzlod due to 1) not all our dependencies being on bzlmod and 2) the need to support bazel 4 and 5. As soon as these blockers are resolved, we will look into utilizing bzlmod and consequently regularly releasing to bazel central repository.

In the meantime, bazel has been owning the protobuf bazel central repository so you should open an issue with them to see if you can get it updated: https://github.com/bazelbuild/bazel-central-registry.

**Comment by alexeagle** [comment]
Note, the protobuf team has funded the work to fix this, I've re-opened this as #14564
