### ISSUE TITLE
.NET cannot handle generated code collision with message name Descriptor 

### ISSUE THREAD

**Issue by daniel-eichinger-bl** [protocolbuffers/protobuf#12291]
**What version of protobuf and what language are you using?**
Version: Grpc.Tools 2.52.0 
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10 

**What runtime / compiler are you using (e.g., python version or gcc version)**
.NET 7.0.102

**What did you do?**
1. Clone https://github.com/daniel-eichinger-bl/protobuf-example (includes simple protobuf file with a message named `Descriptor`)

2. Run `dotnet build`

3. See error: `C:\dev\protobuf-example\obj\Debug\net7.0\proto\Example.cs(50,40): error CS0542: 'Descriptor': member names cannot be the same as their enclosing type [C:\dev\protobuf-example\protobuf-example.csproj]`

**What did you expect to see**
Build should succeed and the protoc compiler should handle this collision.

**What did you see instead?**
.NET error `CS0542` informing about name clash.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jskeet** [comment]
Ah, no, that's for *fields* named `descriptor`. In this case we'd need to rename the class itself to `Descriptor_` or similar.
Shouldn't be *too* hard to do - although we'll probably need to be careful to avoid collisions between the class name provider and the property name provider...

**Comment by jskeet** [comment]
Okay, proposed changes:

**Message types**

All of the names below must be "escaped" - by using a suffix of `__`. Note that just a single `_` would be insufficient, as that's added if there's a *field* with that name. (Imagine a `Descriptor` message with a `descriptor` field - we should generate `class Descriptor__` with a property called `Descriptor_`.)

- Types
- Descriptor
- Equals
- ToString
- GetHashCode
- WriteTo
- Clone
- CalculateSize
- MergeFrom
- OnConstruction
- Parser

Note that `Types` must be "escaped" even for a top-level message, in order to permit it to have nested messages/enums (which would be generated under `Types__.Types`)

**Enums**

Enum names can currently cause *warnings* when nested, but we won't try to fix those. The only change should be when an enum called `Types` is nested in a message, in which case it should be renamed to `Types__`.

The change needs to be applied to both the message/enum declaration *and* references to it (e.g. property types and in the reflection descriptor).

**Comment by clutterloh** [comment]
Looks like this has stalled, but I'm running into the same error on the latest version. Is it possible to push this through?

**Comment by jskeet** [comment]
@clutterloh: As you say, it's stalled at the moment. When I tried it in March, it turned out to be more complex than I'd expected. I'm afraid I don't have time to look into this at the moment - but if you have time, I'd be happy to review a PR.

**Comment by stefanvanburen** [comment]
I'll note that this is an issue with [Envoy's protos](https://github.com/envoyproxy/envoy/tree/187cd09e898bcf3b17682dc8a835dffabfc3533c/api), specifically [this `Descriptor` message](https://github.com/envoyproxy/envoy/blob/187cd09e898bcf3b17682dc8a835dffabfc3533c/api/envoy/extensions/rate_limit_descriptors/expr/v3/expr.proto#L27), as well as a conflict between the generated methods for `body` field and the `clear_body` field in this [BodyMutation message](https://github.com/envoyproxy/envoy/blob/187cd09e898bcf3b17682dc8a835dffabfc3533c/api/envoy/service/ext_proc/v3/external_processor.proto#L372):

```
/build/Envoy/Extensions/RateLimitDescriptors/Expr/V3/Expr.cs(75,42): error CS0542: 'Descriptor': member names cannot be the same as their enclosing type [/build/build.csproj]
/build/Envoy/Service/ExtProc/V3/ExternalProcessor.cs(4339,17): error CS0102: The type 'BodyMutation' already contains a definition for 'ClearBody' [/build/build.csproj]
```

I think the generated `ClearXXX` methods should also be generated to avoid conflicts with fields?
