### ISSUE TITLE
Generate mutable_foo() for numeric and enum fields

### ISSUE THREAD

**Issue by alexolog** [protocolbuffers/protobuf#12336]
### What language does this apply to?
C++ generated code for proto3

### Describe the problem you are trying to solve
Currently, filling or modifying a protobuf message requires writing quite a bit of boilerplate code that is difficult to abstract away because the generated API is inconsistent between field types.
For example, string fields provide `mutable_foo()` access that allows one to operate directly on the field, pass it to other functions to modify, etc. while the numeric/enum fields do not.

### Describe the solution you'd like
Generate a `T* mutable_foo()` function for numeric and enum fields similarly to string fields.

### Examples
**A trivial example: incrementing**
`message.set_my_int(message.my_int() + 1)`
becomes `++message.mutable_my_int()`

**Another trivial example: encoding the result of a C function that returns values by pointer**
```
int temp;
message.set_frac(frexp(arg, &temp));
message_set_exp(temp);
```
becomes `*message.mutable_frac() = frexp(arg, message.mutable_exp());`

**A real-world example:**
Many modern C++ libraries contain functions that either return or operate on tuples.
A use-case we have recently encountered is issuing a DB query that returns many columns, and sending it as a protobuf message to another component for further processing.
An ideal implementation would be to use `std::tie` to create a heterogenous tuple of references to the mutable fields in the message, and directly save the results into it.  This has the added advantage of failing to compile if the tuple size differs from the number of returned columns.
Whereas today we need to store the results in a temporary and copy them field-by-field into the message, which is inefficient, error prone (e.g., forgetting to copy a new field after the query changed, or getting the query and the message out of sync), tedious, and ugly; especially if you have dozens (or hundreds) of different queries to maintain. 

### Describe alternatives you've considered
Writing lots of ugly and error-prone boilerplate code.

### Additional context
The proposed change is non-breaking since all existing functionality will be preserved.

**Comment by arthur-tacca** [comment]
> A use-case we have recently encountered is issuing a DB query that returns many columns, and sending it as a protobuf message to another component for further processing. ... especially if you have dozens (or hundreds) of different queries to maintain.

If you have hundreds of database queries putting their results in protobuf messages, then manually mapping the columns to protobuf fields is more boilerplate than I would be comfortable with. That's still true even if your request were accepted and you were using `std::tie`. Not that I have anything against your request as such; it just doesn't seem to be addressing your core problem.

Instead, I suggest that the column names in the query match the field names in the protobuf (you can rename the columns with `AS` in the SQL, if necessary). Then use protobuf reflection to put the right columns into the right fields. The code would be a bit fiddly, but you only need to write it once for all your queries. I suggest caching the mapping from column name/index to `FieldDescriptor` between rows (or even between runs of the query) because I've found doing the string matching repeatedly for every row is too slow.

In fact I did this in a rather more complex situaton where I was joining multiple tables together putting the rows into complex nested messages. (I put message types and field names into the SQL column names, like `MessageType0field_name`.) That was definitely simpler than writing that code out separately for each message type.

In my case, it would have been much better if I could have just put the messages directly in the database (e.g. in [JSON format columns](https://www.postgresql.org/docs/current/datatype-json.html)) but unfortunately I didn't control the database schema. Maybe that could also be an option for you, even if your tables are mapping directly to flat messages.

**Comment by alexolog** [comment]
> Instead, I suggest that the column names in the query match the field names in the protobuf (you can rename the columns with AS in the SQL, if necessary). 
Not always possible when multiple teams are working on a big project.
As well as reflection being a drag on performance.

**Comment by fowles** [comment]
This is not an API that we wish to add.  In fact we would prefer to wean ourselves off of  `mutable_` methods altogether.  Mutable methods force the exposure of types in a way that makes internal optimizations more difficult.

**Comment by filippobrizzi** [comment]
@fowles are you suggesting that setting values using `mutable_` methods is not the most efficient way? Can you provide an example of how it should be done? Even the main documentation uses `mutable_` to set string values.

**Comment by fowles** [comment]
`mutable_` methods prevent changing the underlying representation to more compact forms (for example storing fields in some kind of packed representation that is only materialized on demand).
