### ISSUE TITLE
[Bug-Java] Protobuf Reflection Breaks with proto3 optional field that starts with `_` name.

### ISSUE THREAD

**Issue by lukemin89** [protocolbuffers/protobuf#12880]
**What version of protobuf and what language are you using?**
Version: main/3.23.1

Language: Java

**What operating system (Linux, Windows, ...) and version?**
MAC

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 11

**What did you do?**

1. define proto3 protobuf
```
syntax = "proto3";

message Proto3Break {
  optional string _underbar = 2;
}
```

2. see descriptor broken in generated code.
```
    internal_static_Proto3Break_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proto3Break_descriptor,
        new java.lang.String[] { "Underbar", "XUnderbar", });
```

in above, `XUnderbar` shoudl be `Underbar`.

3. try invoke refleciton, which cause `FieldAccessorTable.init()`
```
    Proto3Break.getDefaultInstance().getField(Proto3Break.getDescriptor().getFields().get(0));
```

**What did you expect to see**
no exception

**What did you see instead?**
exception.
```
Test > testReflectionBreak FAILED
    java.lang.IllegalStateException: Generated message class "Proto3Break$Builder" missing method "clearXUnderbar".
        at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1998)
        at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$OneofAccessor.<init>(GeneratedMessageV3.java:2251)
        at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2158)
        at Proto3Break.internalGetFieldAccessorTable(Proto3Break.java:39)
        at com.google.protobuf.GeneratedMessageV3.getField(GeneratedMessageV3.java:280)
        at testReflectionBreak(InfoTest.java:63)
        Caused by:
        java.lang.NoSuchMethodException: Proto3Break$Builder.clearXUnderbar()
            at java.base/java.lang.Class.getMethod(Class.java:2108)
            at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1995)
            ... 6 more
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
FYI our style guide recommends using lower_underscore case for field names (https://protobuf.dev/programming-guides/style/#message-field-names), so `_underscore` is not recommended and could hit other escaping problems.

The error is the result of escaping conflicting in proto3 synthetic oneofs by prepending with X in the parser for conflicts:
https://github.com/protocolbuffers/protobuf/blob/1856979d0e0ef825a338dfc6f4030dc0f8d95396/src/google/protobuf/compiler/parser.cc#L818

proto3 uses synthetic oneofs to represent proto3 optionals which results in conflicts for the FieldDescriptor's name (_underscore) and the OneofDescriptor's name (X_underscore since __underscore is reserved for cpp)

Oddly, double underscore seems to be allowed for **actual** oneofs. Maybe we may need to add escaping there too or can loosen this for synthetic oneofs if that comment is no longer current. The following proto results in FieldDescriptor with _oneof and OneofDescriptor __oneof, which is similar to the `optional string _underscore` case.
```
message Proto3Break {
  oneof __oneof {
    string _oneof = 1;
  }
}
```

In any case, I believe we can probably handle the X_ escaping here by adding special handling for synthetic oneofs with FieldDescriptors for clear (like with has/get/etc) in https://github.com/protocolbuffers/protobuf/blob/1856979d0e0ef825a338dfc6f4030dc0f8d95396/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java#L2251
