### ISSUE TITLE
Where is libprotobuf.a under the bazel build?

### ISSUE THREAD

**Issue by hq6** [protocolbuffers/protobuf#12920]
Under autoconf, one could invoke the following, and `libprotobuf.a` was in a well-known location.

I ran `bazel build :protoc :protobuf` and I cannot find `libprotobuf.a`.

Where does it live in the new world?

**Comment by weagle08** [comment]
Did you ever figure this out? We use cmake builds that have dependencies on this and would like to update to the latest protobuf version.

**Comment by hq6** [comment]
@weagle08 

It appears that the Bazel build no longer builds libprotobuf.a. 
Instead it builds two other static archives, one of which contains protobuf without well-known types, and one of which contains just the well-known types.

I did not look too closely at the cmake build, but it's possible that the cmake build still builds libprotobuf.a.

**Comment by MichaelGu718** [comment]
You can build with cmake, with -DBUILD_SHARED_LIBS=ON.

**Comment by CarltonYu** [comment]
Read cmake/README.md

**Comment by adokhugi** [comment]
I downloaded protobuf v25.3 (the project I need it for requires an older, not the latest version) and need to build libprotobuf.a. I tried "cmake . -DBUILD_SHARED_LIBS=ON" and "cmake --build ." but it did not build libprotobuf.a. Maybe it is because I used Visual Studio as the code generator? Could anybody please help me?
