### ISSUE TITLE
No way to disable protoc builds for java, csharp etc when using CMake

### ISSUE THREAD

**Issue by 20PercentRendered** [protocolbuffers/protobuf#12974]
**What language does this apply to?**
C++/CMake subproject

**Describe the problem you are trying to solve.**
I build protobuf as a submodule. I only use C/C++ in my project, so I don't need all the java and csharp protoc bits compiling.
It is apparently possible to disable these with bazel, but I use protobuf via CMake and I won't be switching build systems anytime soon. 

**Describe the solution you'd like**
Add flags to disable compilation of certain languages. 

**Describe alternatives you've considered**
Suffer the compile time penalty. 

**Additional context**
This has been tried before at:
- #1448 
- #1446

**Comment by kalikin** [comment]
You can try these definitions:
```
protobuf_BUILD_LIBPROTOC=OFF
protobuf_BUILD_SHARED_LIBS=OFF
protobuf_BUILD_PROTOC_BINARIES=OFF
```

**Comment by 20PercentRendered** [comment]
Is that fine to do if the dev happens to have a different protobuf version than the one we build?

**Comment by deannagarcia** [comment]
In both bazel and CMake it is impossible to only compile the protoc compiler for a single language, because all the compilers are registered [in the same file](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/main.cc).

In the future we could look to add flags to disable that, but unfortunately that won't be highly prioritized by the team because:
1. Our protoc compile times aren't too long (If your compile times are really long, let me know)
2. We provide a compiled binary in our [releases](https://github.com/protocolbuffers/protobuf/releases/tag/v23.2) so compilation isn't strictly necessary.
