### ISSUE TITLE
Missing binaries in maven central

### ISSUE THREAD

**Issue by janisz** [protocolbuffers/protobuf#13228]
**What version of protobuf and what language are you using?**
Version: v23.3
Language: Java

**What operating system (Linux, Windows, ...) and version?**
Linux
**What runtime / compiler are you using (e.g., python version or gcc version)**
gradle
**What did you do?**
Use protoc gradle plugin to generate files.

**What did you expect to see**
Generated files

**What did you see instead?**
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :extractIncludeProto
> Task :extractProto
> Task :generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_protoc'.
   > Could not find protoc-3.23.3-linux-x86_64.exe (com.google.protobuf:protoc:3.23.3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.23.3/protoc-3.23.3-linux-x86_64.exe
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

Looks like some binaries are missing in maven central. Compare 23.2 with 23.3
 - https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.23.3/  
 - https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.23.2/

- https://github.com/stackrox/stackrox/pull/6788

**Comment by zhangskz** [comment]
Thanks for the report! This was a release issue in 23.3 due to https://github.com/travis-ci/travis-ci/issues/9555 that unfortunately we cannot correct after-the-fact due to Maven limitations. We are instead currently working on releasing 23.4, which should contain the full set of artifacts.

See https://github.com/protocolbuffers/protobuf/issues/13070 for more details, which is where we are tracking this. Closing this as a dupe.
