### ISSUE TITLE
Build failure when building with Bazel on Windows/mingw64

### ISSUE THREAD

**Issue by oakad** [protocolbuffers/protobuf#13761]
Appears to be the root cause of grpc/grpc#28187

Most protobuf dependent rules work ok on Windows/mingw64. Unfortunately, `upb_proto_library` and `upb_proto_reflection_library` are broken somehow.

> bazel build --cpu=x64_windows --compiler=mingw-gcc -s --verbose_failures @upb//:descriptor_upb_proto

> INFO: Build option --cxxopt has changed, discarding analysis cache.
INFO: Analyzed target @upb//:descriptor_upb_proto (0 packages loaded, 1168 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # @com_google_protobuf//:descriptor_proto [action 'Generating upb protos for :descriptor_proto', configuration: b2b712173e23cb6c867282b6c749b978c36f1df42a5675b02ca89482c8e1a89e, execution platform: @local_config_platform//:host]
cd C:/users/oakad/_bazel_oakad/my7jd3mt/execroot/awesome-services
bazel-out/host/bin/external/com_google_protobuf/protoc.exe --upb_out=bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf --plugin=protoc-gen-upb=bazel-out/host/bin/external/upb/upbc/protoc-gen-upb.exe --descriptor_set_in=bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/descriptor_proto-descriptor-set.proto.bin google/protobuf/descriptor.proto
ERROR: C:/users/oakad/_bazel_oakad/my7jd3mt/external/com_google_protobuf/BUILD:326:15: Generating upb protos for :descriptor_proto failed: (Exit -1073741515): protoc.exe failed: error executing command
  cd C:/users/oakad/_bazel_oakad/my7jd3mt/execroot/awesome-services
bazel-out/host/bin/external/com_google_protobuf/protoc.exe --upb_out=bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf --plugin=protoc-gen-upb=bazel-out/host/bin/external/upb/upbc/protoc-gen-upb.exe --descriptor_set_in=bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/descriptor_proto-descriptor-set.proto.bin google/protobuf/descriptor.proto
Execution platform: @local_config_platform//:host
Target @upb//:descriptor_upb_proto failed to build
INFO: Elapsed time: 1.339s, Critical Path: 0.32s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by Flamefire** [comment]
I have a similar issue when building Bazel with Bazel using a compiler installed to a custom location as without ` use_default_shell_env = True,` the `$LD_LIBRARY_PATH` isn't kept/set correctly causing `protoc` to fail with errors like

`bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)`

The fix proposed by @oakad works for me. It needs to be applied to protocolbuffers/upb so not sure why the issue was moved by @acozzette ?

**Comment by scfwilson** [comment]
In which file do you need to add `use_default_shell_env = True`,
I'm experiencing the issue when trying to use bazel to build grpc.

**Comment by Flamefire** [comment]
> In which file do you need to add `use_default_shell_env = True`, I'm experiencing the issue when trying to use bazel to build grpc.

That is a different project and a different issue (although similar cause) and it might be better to keep this issue clean. Anyway: Search for the failing action in the build files (likely in a `*.bzl` file) and there for a call like `ctx.actions.run` or `ctx.actions.run_shell`. For example the fix here as proposed by @oakad would go to [this place](https://github.com/protocolbuffers/upb/blob/e7430e66d6e51def2a88f0b66fdab62b0d9492c1/bazel/upb_proto_library.bzl#L257)   
Maybe your issue is already fixed by my PR to grpc: https://github.com/grpc/grpc/pull/23664
