### ISSUE TITLE
Support non-ascii identifiers

### ISSUE THREAD

**Issue by rnarkk** [protocolbuffers/protobuf#13804]
**What language does this apply to?**

All languages. Both for proto2 and proto3.

**Describe the problem you are trying to solve.**

protoc fails to compile .proto when it contain non-ascii characters as identifiers:

- `package`
- `message`
- `enum`
- variants of `enum`
- `service`
- etc.

**Describe the solution you'd like**

Allow non-ascii characters to be identifiers.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangskz** [comment]
I'm pretty sure non-ascii identifiers is something that we wouldn't want to / likely couldn't support since -- this probably wouldn't work for a good number of code generators. 

https://softwareengineering.stackexchange.com/questions/436340/are-there-historical-problems-with-non-ascii-identifier-characters-in-code
