### ISSUE TITLE
Compiling CUDA files that rely on a Protobuf message with a map field results in "return type is not identical to nor covariant with return type"

### ISSUE THREAD

**Issue by kkraus14** [protocolbuffers/protobuf#14408]
**What version of protobuf and what language are you using?**
Version: v4.23.4 (but reported to reproduce back to v3.7)
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 20.04 / 22.04 using Conda

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 10.4 and NVCC 11.8

**What did you do?**
Minimal reproducible example from here: https://stackoverflow.com/questions/76728242/compiling-cuda-files-that-rely-on-a-protobuf-message-with-a-map-field-results-in

`foo.proto`
```
syntax = "proto3";
package Foo;

message Bar {
    map<string,string> baz = 1;
}

message Result {}

service FooService {
    rpc FooFunc (Bar) returns (Result) {}
}
```

`main.cu`
```
#include "foo.pb.h"

int main() {
    return 0;
}
```

Steps to repro:
```
protoc --cpp_out=. foo.proto
nvcc -x cu main.cu -I/usr/local/include -L/usr/local/lib -lprotoc -lprotobuf -std=c++17
```

**What did you expect to see**
Successful compilation

**What did you see instead?**
```
/usr/local/include/google/protobuf/map_field.h(708): error: return type is not identical to nor covariant with return type "google::protobuf::internal::UntypedMapBase *" of overridden virtual function "google::protobuf::internal::MapFieldBaseForParse::MutableMap"

/usr/local/include/google/protobuf/map_field.h(626): error: return type is not identical to nor covariant with return type "google::protobuf::internal::UntypedMapBase *" of overridden virtual function "google::protobuf::internal::MapFieldBaseForParse::MutableMap"
          detected during instantiation of class "google::protobuf::internal::MapField<Derived, Key, T, kKeyFieldType_, kValueFieldType_> [with Derived=Foo::Bar_BazEntry_DoNotUse, Key=std::string, T=std::string, kKeyFieldType_=google::protobuf::internal::WireFormatLite::TYPE_STRING, kValueFieldType_=google::protobuf::internal::WireFormatLite::TYPE_STRING]" 
cpp/foo.pb.h(272): here

2 errors detected in the compilation of "main.cu".
```

**Anything else we should know about your project / environment**

**Comment by kkraus14** [comment]
This is still an issue, could someone reopen this when they get a chance? Thanks!

**Comment by tom-robo** [comment]
Hi @kkraus14 

I found your stack overflow question. You have the same problem as I do. Very interesting you found things work with older versions of gRPC. 

I hadn't got that far to try different versions (I am using 1.57.0-pre1 and can confirm I get the "return type is not identical to nor covariant with return type" errors). One potential solution that I was looking at was using Clang instead of g++ and NVCC to compile all my C++/ CUDA code altogether in one go. I've had various issues with NVCC trying to apply compiler optimisations, etc so thought that might be a good bet to avoid NVCC altogether. 

Hopefully they fix our problem in the meantime! 

Thanks, Tom.
