### ISSUE TITLE
Valid UTF-8 character of £ makes gRPC request fail

### ISSUE THREAD

**Issue by IIFE** [protocolbuffers/protobuf#14423]
**What version of protobuf and what language are you using?**
Version: v24.3
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2022

**What did you do?**
I'm seeing an issue when sending a valid UTF-8 character from a gRPC client to server, using protobuf as the wire format. The issue can be easily re-produced by updating [this line](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/greeter_client.cc#L89) from `std::string user("world");` to `std::string user("£");`. For some reason when using the `£` character, the request fails with this error:
```
wire_format_lite.cc:626] String field 'helloworld.HelloRequest.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

However, unless I'm missing something, this doesn't seem right as `£` is a valid UTF-8 character. Changing the proto definition to `bytes` does fix it, but I'm trying understand why simply using `string` is causing an issue.

**What did you expect to see**
Request to work as expected.

**What did you see instead?**
Request fails with mentioned error above.

**Comment by esrauchg** [comment]
This should work; I suspect this issue still potentially relates to the string being represented as something other than utf-8 in your configuration. An std::string is agnostic to encoding and can contain to any byte sequence, but gRPC requires it be represented in utf8 representation.

To confirm if this is the root cause of your issue, if you look at the string it will need to be equal to the utf8 representation, which for £ is "\xC2\xA3" (the std::string should have length=2 and contain those two bytes). If your string already is those 2 bytes and you are still getting the error let us know. Thanks!

**Comment by IIFE** [comment]
Thanks @esrauchg .

I'll double check that. I have just realised one thing, the character set on the project (within Visual Studio) is `Use Multi-Byte Character Set`. Could that be the source of the issue?

**Comment by IIFE** [comment]
@esrauchg here's a screenshot showing the values of the string being sent in the gRPC request.
![protobufutf](https://github.com/protocolbuffers/protobuf/assets/24831976/3386b5f8-f0d6-4007-9af6-ca16f4b8aace)

Is it possible to look into this please? It's easily reproducible with the hello world example from gRPC. We'd like to address it soon as it's going to become a blocker for our upcoming release.

We can change all string types to bytes, but I don't know what the consequence of that is.

Thanks.

**Comment by esrauchg** [comment]
I think all evidence still suggests you are simply passing something that
is not utf8 encoded in: the debug UI shows it is the std::string it shows
length=1, but the £ character as an std::string in utf8 should take 2 bytes
( .length() on the std string only counts bytes not characters/codepoints).
If its a 1 bytes £ that seems like it's only possible in Latin-1 string
encoding which is not supported by gRPC strings.

I believe your issue is still with your C++ project configuration and not
any issue with protobuf/gRPC itself.

You can choose to use "bytes" for the type on your message and pass strings
any encoding you want, but it will simply defer your problem to the
receiving side of the rpc to turn that back into a usable string. In that
sense you can use a bytes field with Latin-1 encoded strings and then it's
up to you to coordinate that on all of your other endpoints (and most
Unicode characters won't be representable at all in Latin-1). If you use
string type then you do need to use utf8 encoding, but then gRPC will do
the right thing to expose it as the language's string type in other
languages (only in C++ does the bytes and string protobuf type use the same
type in the language bindings).

**Comment by IIFE** [comment]
@esrauchg I have tried character encoding configurations in the client C++ project, including MBCS, Unicode, and Not set, they all have the same behaviour.

Is there some build settings for either grpc or protobuf that we need to set? All I did was pull the grpc repo, and configure it using the steps from https://github.com/grpc/grpc/blob/master/BUILDING.md#windows-using-visual-studio-2019-or-later - you can try these steps and you'll see the exact issue.

Do I need to somehow tell the build system to use a specific encoding for this to work?

**Comment by IIFE** [comment]
What I'm trying to say is that it's not just my own project that is exhibiting the issue, it's also the example project from gRPC repo itself.

**Comment by esrauchg** [comment]
Unfortunately I don't think we are scoped to assist you in debugging issues with the broader C++ development environment: the spec behavior of protobuf/gRPC is that if you use string type you must provide it with utf8 encoded string.

Your screenshot reflects that you have constructed an std::string which is not in utf8 encoding and so it being rejected by the library is working as intended behavior. C++ doesn't proscribe an encoding of unicode characters and also doesn't even carry the signal of what the encoding is, so it wouldn't be possible for gRPC to 'know' that it is actually a Latin-1 string and handle it correspondingly. Really all it can do is mandate utf8 encoding and leave it up to the user to get the strings into the right encoding; it may be that the _file_ itself in windows needs to be set to another encoding (not the _project_) or some other configuration which is specific to your machine.

If your C++ service received a utf8 encoded string at runtime (from another service, or read from a file) and you passed that string in it would work, so the issue is narrowly in the construction of a string literal in your C++ file. If you can't figure out how to get a C++ string literal to be utf8 encoded under your C++ development environment, you can always fall back to spelling out the characters through explicitly writing out the escaped byte sequence, which would be "\xC2\xA3" in the case of the £ symbol in utf8 encoding. Or, if you are confident that you do reliably have a Latin-1 encoded string literal, you could use a function that will explicitly convert from Latin-1 to utf8 like boost::locale::conv::to_utf (but in this specific case this may be brittle, if the behavior is related to your machine configuration then explicitly converting it would break on another machine).

Apologies that we aren't scoped to assist you further in debugging the general C++ dev environment, but I think given your screenshot reflects that the behavior of gRPC+Protobuf is matching the intended spec I'm going to close out this issue. If you do find evidence that there is actually a bug in Protobuf please reopen the issue. Thanks!

**Comment by IIFE** [comment]
> Unfortunately I don't think we are scoped to assist you in debugging issues with the broader C++ development environment

I completely disagree with this. Protobuf/gRPC support C++ environments, and if gRPC's own source code (the helloworld example) exhibits an issue when built using a supported environment, as per the documentation from BUILDING.md, then to me that's a bug.

Not sure what more evidence I can provide as I've already provided the exact steps to reproduce the problem **_using gRPC's own source code, and build steps_**.

Also there is still not much clarity on what consequences using `bytes` would have? Both the client and server are done in C++ using the same environment, but nothing seems to explain what exactly is the difference between `string` and `bytes` in C++ protobuf. I keep reading there is no difference, but clearly there is when UTF-8 characters are involved.

**Comment by esrauchg** [comment]
> if gRPC's own source code (the helloworld example) exhibits an issue when built using a supported environment

I understand that its frustrating but I believe the relevant behavior has nothing to do with the gRPC code, or the project or specific compiler but your own individual Windows / file configuration. You may have luck reaching out to Visual Studio support forums for how to configure your specific computer so that string literals will be UTF-8 encoded strings. I did some preliminary searches for you for some related questions on this topic:

https://developercommunity.visualstudio.com/t/hangul-character-encoding-in-cp949-when-using-a-fi/120458
https://stackoverflow.com/questions/688760/how-to-create-a-utf-8-string-literal-in-visual-c-2008

I think in general there is no C++ standard way to write "£" as a constant literal in a source file. If you want the "definitely correct on all machines" way to do it the answer would be to write std::string POUND_SIGN = "\xC2\xA3"; if gRPC had to provide single guidance about unicode literals that works in Visual Studio on all machines that would be the answer.

>  I keep reading there is no difference, but clearly there is when UTF-8 characters are involved.

The difference is:
- string in every language uses the native languages string type, encoded on the wire as utf8 and exposed on all platforms by its native string type. When used on C++ the application developer needs to make sure their std::string is using utf8 encoding, and it is validated to be utf-8

- bytes accept any arbitrary sequence of bytes,  usually used for binary content. It is exposed in all platforms through the idiomatic "sequence of arbitrary bytes" language native type. When used on C++ it is std::string but any bytes are allowed verbatim.

So if you use gRPC solely with C++ then really the only difference between bytes and string is that string mandates utf8. If you use any other languages the difference will be bigger.

In your case if you write message.set_bytes_field("£") it'll be 1 byte on your machine but verbatim the same C++ code / project / compiler on another configuration that may compile to be a 2 byte string. When you use gRPC with a bytes field it'll verbatim pass through whatever you gave it, so the receiver of the message would see either the 1 or 2 byte encoding exactly as it was set on the caller side in this case and need to handle it appropriately.

Hope that clarifies things!

**Comment by IIFE** [comment]
So just to be extra clear, if bytes type is used, and both the client and server are built using the same environment/c++ configuration, will the server receive the same bytes that the client sends? I'm confused by this statement:

> When you use gRPC with a bytes field it'll verbatim pass through whatever you gave it, so the receiver of the message would see either the 1 or 2 byte encoding exactly as it was set on the caller side in this case and need to handle it appropriately.

Why would the receiver see either 1 or 2 bytes if the bytes type is used? What does "handle it appropriately" mean exactly, how would the receiver handle it?

Our set up is that the client and server are both built in C++, using the same VS configuration, targeting the same platform (Windows), so I'm still a bit unclear on if the bytes type will introduce problems or not.

Thanks.

**Comment by esrauchg** [comment]
The situation of Unicode in C++ is complicated and not great.

If you write a single C++ project and compile it, and it reads from a file,
from the terminal, from a GUI input, from another RPC, each of those
std::strings could have any different byte representation of the same
conceptual text. If you typed the £ character in each of those places, run
a single binary locally, they may all show up as != strings.

When you have a string variable and go to use it for any case that can
display text (write to file, write to terminal, show in GUI, send to an
rpc), each of those will have the encoding that they require and if you
give it a string which happens to have text with a different encoding than
that the result is usually Mojibake:
https://en.m.wikipedia.org/wiki/Mojibake

The behavior you are reproducing is that this specific file on this
specific machine is set up such that the string literal that you typed it
is using Latin-1 representation. That unfortunately doesn't actually mean
your overall C++ project has coherently decided strings will be Latin-1:
even on your exact machine in this same file at this exact moment any other
strings which aren't this string literal can be some different text
encoding. Any libraries which handle text to show to the user, it will be
broken if you pass it a string with an encoding other than what that
library requires.

If you use the bytes type then any std::string value will be passed through
by gRPC, but that will probably just defer your problem of not having a
firm grasp of the encoding that the unicode string is. On the receiving end
of the RPC your C++ code will want to do something with that string, if you
allow the sender to write utf8 or Latin-1 it probably won't be able to
handle both cases carefully.

It is an option to use bytes type and just "know" that you will only write
Latin-1 encoded text in, and then you may need to convert that to utf8 or
wchar strings or similar before it can be used with whatever other library
you're using it with. Note that this is already the case with your current
string literal: at this moment you currently know that variable is Latin-1
and if you wanted to display that string to the user it would probably need
to be converted depending on the expectations of whatever you're using to
display it.

**Comment by IIFE** [comment]
So essentially if I use bytes, then the same exact string content from the client will be received by the server? In other words, if I pass "£#@-+&\0", those exact same bytes will be received by the server, including the null terminator? The main thing is that the bytes stream is represented as a string in c++ rather than bytes array like C# for example? Also in this case, is the string size going to include the null terminator?

**Comment by esrauchg** [comment]
> those exact same bytes will be received by the server, including the null terminator

This is really getting at C++'s string semantics.

If you write const char* c = "x\0\0"; thats a char[4]: 'x' followed by 2 \0 bytes that were typed, followed by another \0 byte as the implicit null terminator. If you do strlen(c) it will give back 1 because the way C's strlen works is that it just counts characters until it sees a \0 char.

The way std::string works is that it has a .length, it holds that number of chars as data, and it also stores that with a \0 byte immediately after (for some amount of backwards compatibility with C functions). When you write std::string s = "somestring";  the right hand side is a C string and it it gets converted into a C++ string approximately like {.chars=s, .length=strlen(s)}

If you write std::string s = "x\0";  per above that literal is a char[3] with 'x' and 2 '\0'. Assigning that to an std::string will take strlen() and construct a C++ string with length=1. If you use that string with gRPC the 1 bytes would be sent on the wire regardless of your protobuf type is string or bytes. When you read the 1 bytes string on the other side it will be placed back into an std::string which stores that 1 byte of data and always separately puts a '\0' char one-past-the-end.

But std::string can have null bytes, you just can't construct one from simple implicit conversion from a C string. If you  instead write std::string s("x\0", 2) it will construct a std::string of length 2, where the contents of the string will be an 'x' followed by one '\0'. This string's held data will be 2 bytes, 2 bytes would be sent over the wire, when a server receives it and puts it into an std::string it will store the 2 bytes in an std::string which will hold it with another '\0' one-past-the-end.

> if I pass "£#@-+&\0",

If you write:
  std::string s = "\A3" "x\0";    You'll have a constructed a length=2 std::string which, if those bytes were interpreted as Latin-1 would conceptually be "£x". gRPC will reject this on a string-type field because it is not valid utf-8.

  std::string s("\A3" "x\0", 3); You'll have constructed a length=3 std::string which has a \0 byte in it. Again Latin-1, meanig it would only be usable with 'bytes'.

  std::string s("\xC2\A3" "x\0") ; You'll have constructed a length=3 std::string, if those bytes are interpreted as utf-8 would be "£x". gRPC would accept this for either bytes or string field.

  std::string s("£x");  This is basically ambiguous source code and so "what happens when I type this into my .cpp file" won't have any single answer. In reality you as the developer have constructed a string and 'choose' either case 1 or 3 above, but when you're looking at your source in the editor you literally can't "see" what choice that is because it depends on hidden state like the encoding of the .cc's file itself. When handling Unicode in C++ it is the reality that the developer must simply "know" the encoding of any of their strings, and also know the encoding required by any libraries they send the string to and handle conversions if they don't match. Since the literal in a .cpp file is obscure in what encoding it is, if you type the literal that way it will likely be difficult for you to long term handle correctness of your code.
