### ISSUE TITLE
[ruby] More flexible ENCODE_MAX_NESTING

### ISSUE THREAD

**Issue by marcinwyszynski** [protocolbuffers/protobuf#1493]
At [codebeat](https://codebeat.co) we have a legitimate use case for deeply nested protocol buffers - we use these to represent ASTs. We know for sure there are no cycles in our data structures so we wouldn't like to be limited by an arbitrary number we can't change. And we can't since it's set in a header file so without forking a repo and manually changing it there is not much we can do. We would like to kindly request that this constant is turned into a Ruby constant that can be modified by the caller.

**Comment by lfittl** [comment]
For anyone finding this (like I have) - this is still an issue after the recent ubp refactoring in the Ruby library.

The `_ubp_decode` method now allows passing in options (see https://github.com/protocolbuffers/protobuf/blob/0ebbd7d7c31c0e0c5bee617cf191c5c53bbd93dd/ruby/ext/google/protobuf_c/ruby-upb.c#L890), which theoretically would let one increase the limit from the default of 64 levels deep, but this is not yet available in the Ruby level API, since the relevant function calls ubp_decode (not _ubp_decode with the leading underscore, that allows the depth to be passed in as an option):

https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/message.c#L928
