### ISSUE TITLE
iOS need Privacy Manifests

### ISSUE THREAD

**Issue by LionWY** [protocolbuffers/protobuf#15029]
Apple need privacy Manifests

https://developer.apple.com/cn/support/third-party-SDK-requirements/

![image](https://github.com/protocolbuffers/protobuf/assets/5524753/19ab5e1e-fd9d-46c5-9b6b-2f12a28e0f77)

**Comment by GH-Ong** [comment]
hi @zhangskz any updates on this requirement as well as code signing?

**Comment by zhangskz** [comment]
This was cherry-picked to the 26.x branch and should be included in the v26.0-rc2 (and later v26.0) release.

**Comment by WWSellers** [comment]
Apple updated the schedule for manifest requirements
https://developer.apple.com/news/?id=3d8a9yyh
March 13: warnings
May 1: possible rejections

**Comment by zhangskz** [comment]
We believe this should be addressed per the apple privacy manifests added as of v26.0-rc2. Please reopen if this is unsufficient!

**Comment by naahmedea** [comment]
Let's say we are using an old version of protobuf(3.19.4) that uses `mach_absolute_time()` then should we declare the below reason in the privacy manifest file? please confirm:

- `35F9.1` Declare this reason to access the system boot time in order to measure the amount of time that has elapsed between events that occurred within the app or to perform calculations to enable timers.

**Comment by zhangskz** [comment]
Discussed in https://github.com/protocolbuffers/protobuf/issues/16358
