### ISSUE TITLE
Why does proto3 not support constants?

### ISSUE THREAD

**Issue by AaronKonishi** [protocolbuffers/protobuf#15221]
Hi everyone, even we can define a message in proto:

message test {
  string str = 1;
}

But both sides of the message sending and receiving have some special meanings for the value of the 'str'，such as "system", "handshake", etc.

How can we define these constant data int 'proto3', so both sides can use '*.proto' file instead of oral agreement.

In my opinion, **constants are also a part of message definition.**

**Comment by DavidZbarsky-at** [comment]
Can you use enums instead?

**Comment by AaronKonishi** [comment]
@DavidZbarsky-at 
For integer constants, That's OK. But other types also have constants, such as bool, float, double, string, etc.

**Comment by acozzette** [comment]
I don't think adding support for constants in .proto files is a direction we want to pursue. But you can already do something like this fairly easily using [custom options](https://protobuf.dev/programming-guides/proto2/#customoptions) anyway. This would let you specify the special string values like this:
```
message test {
  string str = 1 [(myproject.string_values) = ["system", "handshake"]];
}
```

**Comment by AaronKonishi** [comment]
@acozzette 
That's not what I want. 
What I want is not a message, but a special value for a field in the message, which may have data types such as float, double, string, etc.
In some cases, special values of message fields may not be defined together with the message. It is possible to define it int another *.proto file with 'Any' or 'Bytes' data types.

**Comment by matheuscscp** [comment]
I'd like to see support for constants too. I think the description of this issue captures very well the idea. I want clients using my gRPC service to have a library of the accepted values they can pass on my string field rather than hardcoding those constant values. I really don't see how this should be out of the scope of a technology for defining APIs.

**Comment by MatthewChudleigh** [comment]
I had to choose Apache Thrift over proto due to const string support. All I need is the ability to generate const strings with the same reliable value for use across multiple language targets. Doesn't even need to be in the messaging, it's used at the initialisation stage (Temporal namespace and workflow ids, specifically).  Such a shame protobuf doesn't support this
