### ISSUE TITLE
C#: Add a static virtual interface for messages

### ISSUE THREAD

**Issue by aelij** [protocolbuffers/protobuf#15327]
**What language does this apply to?** C#

**Describe the problem you are trying to solve.**
I would like to be able to write generic code that accepts a message type and parses it.
For example:
```cs
T Deserialize<T>(BinaryData data);
```

**Describe the solution you'd like**

Add an interface that exposes [static virtual members](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/static-abstracts-in-interfaces) and emit it in codegen.

For example:

```cs
public interface IParsableMessage<T> where T : IMessage<T>
{
    public abstract static MessageParser<T> Parser { get; }
    public abstract static MessageDescriptor Descriptor { get; }
}
```

Which would allow writing code like this:

```cs
T Deserialize<T>(BinaryData data)  where T : IParsableMessage<T> => T.Parser.ParseFrom(data.ToMemory().Span);
```

**Describe alternatives you've considered**

I could add this interface myself, but then I'd have to manually implement it for every generated contract.

**Comment by jskeet** [comment]
I like the idea of this - and indeed when writing the initial C# implementation of protobuf back in 2008, I [wrote about wanting static members in interfaces](https://codeblog.jonskeet.uk/2008/08/29/lessons-learned-from-protocol-buffers-part-4-static-interfaces/). (That was about builders rather than parsing, as that version of protobuf used immutable message types and builders, but it's the same idea.)

We'd definitely want a separate interface for this, to avoid it being a breaking change. I'm somewhat nervous about the fact that we'd need to only implement it in some versions. As it happens, we already do that for `IBufferMessage`, so there is at least *some* precedent, although that's done in a slightly different way.

Basically, I'm supportive of the idea - but at the moment I've got so much on that I won't have time to think about the corner cases etc. I'll leave the issue open and *hope* to get to it at some point - but I should warn you that my backlog (particularly of protobuf work as opposed to my main work) is quite long.

In the mean time, if you do create your own interface it should be pretty straightforward to make messages *that you own* implement it due to partial classes - you should be able to just have:

```csharp
public partial class Message1 : IParseableMessage {}
public partial class Message2 : IParseableMessage {}
public partial class Message3 : IParseableMessage {}
public partial class Message4 : IParseableMessage {}
```

... and let it just use the declarations from the "main" generated code. You could then have a unit test to make sure all the messages are covered. That won't help for any protos you're not generating yourself, of course.

Sorry that this probably isn't quite as "yeah, let's go!" as you'd have liked - I wish I could clone myself to get to everything I want to do :(

**Comment by alrz** [comment]
Keep getting back to this and I finally found the issue.

>We'd definitely want a separate interface 

You can probably add a default impl with `virtual abstract` I guess that would at least address the breaking change concern.

**Comment by Mitchman215** [comment]
Would love to see this feature implemented as I have a similar use case for a generic `Deserialize<T>` method. I'm wondering if this is something that could be re-opened and reconsidered now?

**Comment by Stepami** [comment]
well for now one can use workaround like this:
```cs
new MessageParser<T>(() => new())
```
but still it would be very pleasant to have the `static abstract` feature integrated with Google.Protobuf contracts
