### ISSUE TITLE
C#: Add DateOnly and TimeOnly conversion methods for Timestamp

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#15393]
**What language does this apply to?**
C#

**Describe the problem you are trying to solve.**
.NET has added DateOnly and TimeOnly types. There should be a way to easily convert these to Protobuf's Timestamp

**Describe the solution you'd like**
There are conversion methods for DateTime and DateTimeOffset already:
* https://github.com/protocolbuffers/protobuf/blob/27275da1c0033331e55277613f32457b2500e811/csharp/src/Google.Protobuf/WellKnownTypes/TimeExtensions.cs
* https://github.com/protocolbuffers/protobuf/blob/27275da1c0033331e55277613f32457b2500e811/csharp/src/Google.Protobuf/WellKnownTypes/TimestampPartial.cs

Replicate these methods for the new types.

**Describe alternatives you've considered**

**Additional context**

**Comment by JamesNK** [comment]
TimeOnly doesn't make sense as a Timestamp, but it could be convertible to a Duration.

**Comment by jskeet** [comment]
Personally I don't think either of these types is suitable as a conversion target.

`TimeOnly` is a time of day, not a duration of time. (`DateTime.TimeOfDay` uses a `TimeSpan`, but that's problematic too IMO. That's why `TimeOnly` was created...)

`Timestamp` is an instant in time - it's "machine time" rather than "civil time" whereas `DateOnly` is about civil time, and that usually involves a time zone - any conversion from `Timestamp` to `DateOnly` would have to *assume* UTC, and that feels like it's misleading to me.

The conversion to `DateTimeOffset` (or `DateTime`) allows you to get to a `DateOnly` reasonably easily (and both conversion methods give a value that really does represent the original `Timestamp`, as it includes the UTC offset or UTC kind), so I don't think that providing additional methods that could easily cause confusion would be a benefit.

**Comment by JamesNK** [comment]
Ok. I don't feel strongly about either.

**Comment by davidkarlsson** [comment]
Was this closed without adding any support for them? What's the recommended way to use `TimeOnly` with protobuf then if that's the case?

Since `TimeOnly` can be converted to and from `TimeSpan` and `TimeSpan` is convertible to `Duration` why can't `TimeOnly` also be directly convertible to `Duration` for consistency? I understand the argument that `TimeOnly` is a time of day and not a duration of time but can't it also be seen as the time elapsed since midnight like the documentation for `TimeOnly.FromTimeSpan` says?

**Comment by jskeet** [comment]
@davidkarlsson: `TimeOnly` just doesn't have a logical representation in protobuf. Sure, you *can* convert a `TimeOnly` to a `TimeSpan`, but they're logically not the same thing. A "time of day" and "elapsed number of milliseconds" are *not* the same, and in my experience trying to accept them as if they're interchangeable is a recipe for confusion.

A time of day is *not* a "time elapsed since midnight", in general - even if it is most of the time.

If you want to add your own extension methods and factory methods in your own code, you can do so - but I would strongly resist putting it into Google.Protobuf.

**Comment by ivebeenlinuxed** [comment]
Hi Guys,

I'm new to gRPC, but I struggled to find a sample of a suitable extension. Would this be appropriate?


In the program main:
```csharp
RuntimeTypeModel.Default.Add(typeof(DateOnly), false).SetSurrogate(typeof(DateOnlySurrogate));
```

DateOnlySurrogate.cs:
```csharp
using ProtoBuf;

[ProtoContract]
public class DateOnlySurrogate
{
    [ProtoMember(1)]
    public DateTime QualifiedDateTime { get; set; }
    // protobuf-net wants an implicit or explicit operator between the types
    public static implicit operator DateOnly(DateOnlySurrogate value)
    {
        return DateOnly.FromDateTime(value.QualifiedDateTime);
    }
    public static implicit operator DateOnlySurrogate(DateOnly value)
    {
        return new DateOnlySurrogate {
            QualifiedDateTime  = value.ToDateTime(TimeOnly.MinValue) };
    }
}
```
