### ISSUE TITLE
Superfluous quotes when calling the `ToString()` method on `Timestamp` objects

### ISSUE THREAD

**Issue by Simonbtlr** [protocolbuffers/protobuf#15396]
**What version of protobuf and what language are you using?**
Version: 3.23.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
MacOS Sonoma 14.2.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
`dotnet --list-runtimes`: Microsoft.AspNetCore.App 8.0.0, Microsoft.NETCore.App 8.0.0;
`dotnet --list-sdks`: 8.0.100

**What did you do?**
1. Create a `Timestamp` object
3. Call the `ToString()` method
4. Look at the contents of the variable
5. You'll see the extra quotation marks

**What did you expect to see**
I'd like to see just the date and time, without the extra quotation marks.

**What did you see instead?**
I see that the variable contains the value `\"2024-01-10T00:00:00:00Z\"`. `\"` Clearly should not be in the output

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I have attached a screenshot showing what is output when this method is called
![image](https://github.com/protocolbuffers/protobuf/assets/54881795/b3a599d9-4935-4345-86e8-af83d3a54507)

**Comment by jskeet** [comment]
This is by design - it's providing the JSON representation, which is a string value. In general, calling `ToString` on any message provides the JSON representation. (This also includes the other well known types such as `Struct`, `Duration` etc.) In other words, I disagree with your claim of:

> Clearly should not be in the output

This is working as intended, and changing it would be a very breaking change.
