### ISSUE TITLE
[Rust] Generated code uses non-existing crate

### ISSUE THREAD

**Issue by smoell** [protocolbuffers/protobuf#15562]
**What version of protobuf and what language are you using?**
Version: v3.25.2

**What operating system (Linux, Windows, ...) and version?**
macOS Sonoma 14.2.1

**What runtime / compiler are you using (e.g., python version or gcc version)**
Apple clang version 15.0.0 (clang-1500.1.0.2.5)

**What did you do?**
1. Write a generic proto-file
2. Generate code using `protoc --rust_out=experimental-codegen=enabled,kernel=upb:. foobar.proto`
3. Start a build with cargo
4. Error message
```
1 | extern crate protobuf_upb as __pb;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**What did you expect to see**
No errors

**What did you see instead?**
```
1 | extern crate protobuf_upb as __pb;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by buchgr** [comment]
Hji @smoell! Super cool that you are trying out our experimental Rust implementation! However, note that it's super experimental and not meant to be used for anything but trying it out.

You are seeing the error because we currently only support building with Bazel and the generated code assumes that. We'll support building with cargo once we have a stable version.

So I am closing this issue because it "fails as expected" :-). Feel free to reopen if you think this was a mistake.
