### ISSUE TITLE
Python python_edition_defaults is not being built when setup.py is executed

### ISSUE THREAD

**Issue by ottmar-zittlau** [protocolbuffers/protobuf#15625]
**What version of protobuf and what language are you using?**
Version: v26.0-rc1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
python

**What did you do?**
I try to use protobuf together with nanopb (https://github.com/nanopb/nanopb)

1. Go to python subfolder and run `python setup.py build`
2. Copy resulting python package into the nanopb folder (so that nanopb finds it)
2. When I then run nanopb, I get the error
```
[build]   File ".../nanopb/generator/google/protobuf/descriptor_pool.py", line 44, in <module>
[build]     from google.protobuf.internal import python_edition_defaults
[build] ImportError: cannot import name 'python_edition_defaults' from 'google.protobuf.internal' (..../nanopb/generator/google/protobuf/internal/__init__.py)
```
At least with v24.4 it did work well. I found a template for the missing file: https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/python_edition_defaults.py.template
However, as far as I can see this is only used in a bazel-file in the python-subfolder:
https://github.com/protocolbuffers/protobuf/blob/5b77d8cc3d917b96e2e1104c79314a6a6e84f442/python/build_targets.bzl#L158

Do I need to build the python-package with bazel or is there a way to make the python-approach work?

**What did you expect to see**
Calling setup.py generates all files.

**What did you see instead?**
An error.

**Anything else we should know about your project / environment**
I'm building a Conan-protobuf package in a Gitlab pipeline.

**Comment by zhangskz** [comment]
Thanks for the report! `setup.py` is actually meant to be used from the *Python source package* published on PyPI and is not expected to work when built from the Github repo / release tarball. As you've noticed, python_edition_defaults is bazel generated and not checked into in our Github repo, but should be present in our published Python source package.

python/setup.py is also obsolete/deprecated since it is for the old C++ backend (deprecated in 21.x) and will be removed in 26.x. python/dist/setup.py (distributed in our source package) should be used instead. See https://github.com/protocolbuffers/protobuf/pull/15671 for more details.

**Comment by ottmar-zittlau** [comment]
@zhangskz - many thanks for your quick reply! i was not aware that there are separate source packages for the python package - i think that this will simplify my problem considerably.

best regards
oz
