### ISSUE TITLE
What are equivalent of CreateBuilder() in proto 3 classes

### ISSUE THREAD

**Issue by ikrammohammad** [protocolbuffers/protobuf#15833]
We are migrating proto 2 C# classes to proto 3 using protoc.exe. In proto 2 version there used to be CreateBuilder() available see example below 

// proto 2
Person john = new Person.Builder()
    .SetFirstName(“John”)
    .SetLastName(“Doe”)
    .Build();

Now in proto 3 we dont have these. So please suggest what is equivalent in proto 3?

Could below is the only way to migrate?

![image](https://github.com/protocolbuffers/protobuf/assets/38226861/ad556835-dd65-41d0-9d58-01595fee6efa)

Thanks!

**Comment by jskeet** [comment]
There's no equivalent - the only reason for the builder classes was because the non-builder classes were immutable.
The current generated classes are mutable, so there are no builder classes. Your screenshot is basically right - that just creates an instance of the class for the `Clipboard` message. There's nothing else to do (except rename your method, given that it's not creating a builder).
