### ISSUE TITLE
How to define param with Object type in Java？

### ISSUE THREAD

**Issue by lorantlorant** [protocolbuffers/protobuf#16153]
lanaguge：java
hi buddy，righ now，i just have TestReq  struct like this 
==========================
public class TestReq implements Serializable {

    private static final long serialVersionUID = 5756566851716700046L;
    
    private Long timestamp;

    private Object body; //how to define this parm in proto file
    
}
======================================

how to define body in proto file? can any one help me？

**Comment by sgammon** [comment]
Hello @lorantlorant 

I am just a mere protobuf user, but you may want to take a look at [`google.protobuf.Any`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/any.proto#L58-L69), which can help you safely serialize any protocol buffer type. There are also types like [`google.protobuf.Value`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L56-L78).

Conceptually, these types are safe containers for either a protocol buffer message (`Any` message, which is _roughly_ similar to `Object extends GeneratedMessage`), or for any primitive type, with nesting. `google.protobuf.Struct` is basically like a JSON map of `google.protobuf.Value` entries.

I have used protocol buffers for years now and I don't think there is another way to generate a method which gets close to a plain Java `Object`. My guess is this is because Protocol Buffers would not necessarily be able to guarantee perfect serialization capabilities.

**Comment by lorantlorant** [comment]
Okay, thank you very much, I'll try it first
