### ISSUE TITLE
Detected mismatched Protobuf Gencode/Runtime version suffixes when loading com.wonders.kafka.ketier.protobuf.InternalDataSetInfoTwoProto$InternalDataSetInfo: gencode 4.26.0, runtime 4.26.0-rc3. Version suffixes must be the same.

### ISSUE THREAD

**Issue by sqlAIJava** [protocolbuffers/protobuf#16152]
com.google.protobuf.RuntimeVersion$ProtobufRuntimeVersionException: Detected mismatched Protobuf Gencode/Runtime version suffixes when loading com.wonders.kafka.ketier.protobuf.InternalDataSetInfoTwoProto$InternalDataSetInfo: gencode 4.26.0, runtime 4.26.0-rc3. Version suffixes must be the same.

**Comment by zhangskz** [comment]
Per the error message, this should be due to mixing gencode from the 4.26.0 final release with runtime from the 4.26.0-rc3 prerelease. Please check if your runtime needs to be updated to also use 4.26.0 at the same version.

Please reopen if this does not appear to be the case, and you believe there is a mistake in the version check itself.
