### ISSUE TITLE
com.google.protobuf:protobuf-java missing Automatic-Module-Name in its manifest or a module-info.class in v3.22.0+

### ISSUE THREAD

**Issue by antonulasevich** [protocolbuffers/protobuf#16190]
**What version of protobuf and what language are you using?**
Version: 3.22.0 and later
Language: Java

**What operating system (Linux, Windows, ...) and version?**
This issue is not specific to an operating system

**What runtime / compiler are you using (e.g., python version or gcc version)**
Gradle 8.6, Java 17

**What did you do?**
There is an issue using `com.google.protobuf:protobuf-java` in a modular application built using Gradle starting with `protobuf-java` version `3.22.0`. Version `3.21.12` is the latest version that contains `Application-Module-Name` attribute in its manifest file. Starting with version `3.22.0` neither that attribute, nor `module-info.class` is present and therefore the jar is not considered a Java module. Gradle then puts it on the class path instead of module path and compilation fails with the following error:

../src/main/java/module-info.java:7: error: module not found: com.google.protobuf
    requires com.google.protobuf;

**What did you expect to see**
Expected result is that compilation of a modular application succeeds in `3.22.0` like in previous versions.

**What did you see instead?**
`protobuf-java:3.22.0` can not be used in a modular application built using Gradle.

**Anything else we should know about your project / environment**

**Comment by zhangskz** [comment]
I believe this was reported in https://github.com/protocolbuffers/protobuf/issues/12639, and should have been fixed in 26.x release by https://github.com/protocolbuffers/protobuf/commit/d580fde63aa8ea5c6f4619396e68aaf017fc9d61#diff-580cdf6ec10b074d78ecc4a185c2f5ca053ae488c7ec41cd957f6dab0d9cf9e8

Closing as duplicate -- please update in the other github issue if you are still having trouble with this in 26.x+.
