### ISSUE TITLE
"Don’t Go from Repeated to Scalar" packed note doesn't sound correct

### ISSUE THREAD

**Issue by Kampfkarren** [protocolbuffers/protobuf#16298]
The documentation on [Don’t Go from Repeated to Scalar
](https://protobuf.dev/programming-guides/dos-donts/#repeated-to-scalar) specifies this:

> Going from scalar to repeated is OK in proto2 and in proto3 with [packed=false] because for binary serialization the scalar value becomes a one-element list .

I'm not sure about proto2, but for proto3 this doesn't seem like it should be correct, in the sense that [packed=false] should be unnecessary, from [Packed Repeated Fields](https://protobuf.dev/programming-guides/encoding/#packed):

> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa. This permits adding [packed=true] to existing fields in a forward- and backward-compatible way.

Other docs suggest that this wasn't always the case, from [Language Guide (proto 3)](https://protobuf.dev/programming-guides/proto3/):

> In 2.3.0 and later, [changing packed] is safe, as parsers for packable fields will always accept both formats, but be careful if you have to deal with old programs using old protobuf versions.

But am I correct in thinking that I can change a scalar type to repeated without having to specify packed in proto3 and it should just work, since Protobuf implementations should be able to work with both packed and unpacked?

**Comment by acozzette** [comment]
The situation with fields that might be packed is tricky. Let's say you have a singular int32 field and you would like to change it to repeated. Presumably you can't deploy that change everywhere instantaneously, so for some period of time there will be a mixture of some newer deployed binaries that think the field is repeated while older ones still think it is singular. If the newer binaries (the ones that know the field has changed to repeated) serialize the field in the packed format and then the older binaries (which still think it is singular) try to parse it, these old binaries will not know how to parse the field correctly. They won't choke on the data but will quietly put it in the unknown field set, which is probably not what you want.

So this is why is it is potentially risky to switch between a singular field and a packed repeated field. Two ways to solve the problem would be:
 - Set `packed = false` so that the wire format does not change.
 - Alternatively, if you can manage the rollout in such a way that no old binaries ever try to parse the new format, that could also work.

**Comment by Kampfkarren** [comment]
Ahhh that makes sense--I was thinking about it in terms of potentially old clients sending Protobufs to a definitely new server. Thanks!
