### ISSUE TITLE
Adding `Bytes` suffix to a field breaks java compilation

### ISSUE THREAD

**Issue by alexthe2** [protocolbuffers/protobuf#17367]
**What version of protobuf and what language are you using?**
Version: main/v3.25.1
Language: Java

**What operating system (Linux, Windows, ...) and version?** macos sonoma

**What runtime / compiler are you using (e.g., python version or gcc version)**
Java 21

**What did you do?**
Create a message like:
```protobuf
package foo.bar.models;

message User {
    optional string profileImage = 1;
    optional bytes profileImageBytes = 2;
}
```

The problem here is simple, the java code generator generates a `xxxBytes` return function for `profileImage`, which then overlaps with `profileImageBytes`. This **also happens when using underscores** as defined by the style guide 

This leads to:
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] .../target/generated-sources/protobuf/java/.../proto/models/User.java:[404,41] method getProfileImageBytes() is already defined in class foo.bar.proto.models.User
[ERROR] .../target/generated-sources/protobuf/java/.../proto/models/User.java:[3039,43] method getProfileImageBytes() is already defined in class foo.bar.proto.models.User.Builder
[ERROR] .../target/generated-sources/protobuf/java/.../proto/models/User.java:[3052,20] method setProfileImageBytes(com.google.protobuf.ByteString) is already defined in class foo.bar.proto.models.User.Builder
[ERROR] .../target/generated-sources/protobuf/java/.../proto/models/UserOrBuilder.java:[198,34] method getProfileImageBytes() is already defined in interface foo.bar.proto.models.UserOrBuilder
```

**Comment by esorot** [comment]
The generated code for proto messages with `bytes` fields generates both `getFoo()` and `getFooBytes()` methods. This is because the `ByteString` type is more efficient for storing and manipulating binary data than the `String` type.

If you are using the proto message in a way that expects a `String` type, you can use the `toStringUtf8()` method to convert the `ByteString` type to a `String` type. This method will convert the `ByteString` to a UTF-8 string, which is the same encoding that is used for `String`s in Java.

For example, the following code converts the `ByteString` field `data` to a `String` field `text`:

```java
String text = data.toStringUtf8();
```

**Comment by alexthe2** [comment]
I'm aware of what the generator does, however it is not mentioned in the docs that you cannot have a Bytes suffix field (unless I'm mistaken in which case I'm sorry). Thus this is a unwanted side-effect of generating set more efficient Java code. In our use case, the upstream client (written in dart) will either send bytes or a string, the downstream server (written in python) then takes the right field. The new Java service is just failing to generate code because of this
