### ISSUE TITLE
Ruby Version Mismatch for google-protobuf in x86_64-linux variant

### ISSUE THREAD

**Issue by gregoryfm** [protocolbuffers/protobuf#18042]
I’m using a gem that has google-protobuf version `3.23.4` as a dependency. I’ve installed the gem and its dependencies on my machine (MacBook M3) without any issues. However, the CI is broken on GitHub Actions because the `x86_64-linux` variant has a different Ruby version requirement (>= 2.6, < 3.3.dev) compared to the main version 3.23.4, which requires Ruby >= 2.3.

Is there a specific reason for this difference, and would it be possible to update the `x86_64-linux` variant to match the standard version’s requirement of Ruby >= 2.3?

https://rubygems.org/gems/google-protobuf/versions/3.23.4
https://rubygems.org/gems/google-protobuf/versions/3.23.4-x86_64-linux

Thank you.

**Comment by JasonLunn** [comment]
@gregoryfm - Can you clarify what gem you're using that has an explicit dependency on 3.23.4? That version is no longer supported (see https://protobuf.dev/support/version-support/#ruby-support for documentation on what versions are currently maintained).

If you need a protobuf version that targets a higher Ruby interpreter version, you'll need to use a later release, preferably the latest.

My educated guess is that because https://rubygems.org/gems/google-protobuf/versions/3.23.4 is a source gem, it may be possible for end users to use it to build against arbitrary Ruby interpreter versions, whereas https://rubygems.org/gems/google-protobuf/versions/3.23.4-x86_64-linux is a precompiled version build against a Ruby interpreter prior to the release of Ruby 3.3 and therefore may not have binary compatibility.
