### ISSUE TITLE
JsonStringToMessage will parse fail if a json string too large

### ISSUE THREAD

**Issue by xiedeacc** [protocolbuffers/protobuf#18530]
my json contain a string field with size over 64MB, then JsonStringToMessage  will fail, it's expected behavior?

**Comment by JasonLunn** [comment]
Probably, but can you specify what language / version / platform are you using so I can confirm?

**Comment by xiedeacc** [comment]
c++
v27.1
ubuntu24.04
gcc13.2
compiled by bazel

**Comment by xiedeacc** [comment]
that string field value is a binary string

**Comment by acozzette** [comment]
I'm not aware of a length limit, but if it's binary data stored in a `string` field then that might explain the problem. `string` fields are required to be valid UTF-8, so non-UTF8 will cause a parse failure. You might want to switch to a `bytes` field if you need to store binary data, but keep in mind that this will change the JSON format since the data will need to be base64-encoded.

**Comment by xiedeacc** [comment]
yes, I'm use bytes

**Comment by acozzette** [comment]
Do you have a test case you could show us so that we can try to reproduce the error?

**Comment by xiedeacc** [comment]
sorry, maybe json base64 code problem, for I used rapidjson manually transfered to avoid this problem, and for busy work, I cannot provide such UT, I think it's most likely my own problem, so I close this issue first
