### ISSUE TITLE
How to deal with null or unset values of repeated type

### ISSUE THREAD

**Issue by hicker-kin** [protocolbuffers/protobuf#19064]
One：

I create a message, example:

`
message Entry {
  string key = 1;
  repeated string values = 2;
}
`

then use it as repeated:

`
message DataReq {
......
  repeated **Entry** tags = 39;
}
`

Second：
my server receive  **DataReq**  ,  I am not sure whether 'tags' being nil means that the client hasn't set it or has set it to an empty value 'tags: []'.

Then, How should I resolve this issue? Are there any good solutions on the official website? Thanks to the experts.

**Comment by esrauchg** [comment]
Can you clarify if this is about the Go API?

In general Protobuf does not support 'presence' on repeated fields; if you touch a repeated field but it becomes empty before being serialized, thats the same as if it was never touched at all and nothing will be included on the wire for that field.

Most of our supported languages use opaque API designs where you can only see the fields through getters, and in that case a repeated field will never be nil, an default empty instance will always be there for any repeated field.

For 'open struct' API designs (namely Go) where you use public fields with no accessors, it can be possible for a repeated field to be null/nil, in which case the application code really should treat it the same as a non-nil empty list, since there's no semantic meaning that differentiates those two things.
