### ISSUE TITLE
protoc errors with no line numbers are hard to resolve

### ISSUE THREAD

**Issue by jskeet** [protocolbuffers/protobuf#2315]
I've just been trying to put together a proto3 version of unittest_custom_options.proto, and obviously there's a lot of proto2 stuff to remove.

However, protoc makes this harder than it should be only reporting line numbers for some errors.
Here are the errors without line numbers that I've been seeing:

- Extensions in proto3 are only allowed for defining options.
- Extension ranges are not allowed in proto3.
- The first enum value must be zero in proto3.
- MessageSet is not supported in proto3.

**Comment by plemanach** [comment]
Hi,

I tried this custom option after removing the unsupported ones but I get this issue on the generated code 
'DescriptorReflection' is inaccessible due to its protection level

`namespace UnitTest.Issues.TestProtos {

  /// <summary>Holder for reflection information generated from unittest_custom_options_proto3.proto</summary>
  public static partial class UnittestCustomOptionsProto3Reflection {

    #region Descriptor
    /// <summary>File descriptor for unittest_custom_options_proto3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnittestCustomOptionsProto3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiR1bml0dGVzdF9jdXN0b21fb3B0aW9uc19wcm90bzMucHJvdG8SEXByb3Rv",
            "YnVmX3VuaXR0ZXN0GhBkZXNjcmlwdG9yLnByb3RvInMKHFRlc3RNZXNzYWdl",
            "V2l0aEN1c3RvbU9wdGlvbnMiUwoGQW5FbnVtEhYKEkFORU5VTV9VTlNQRUNJ",
            "RklFRBAAEg8KC0FORU5VTV9WQUwxEAESFgoLQU5FTlVNX1ZBTDIQAhoFsIb6",
            "BXsaCMX2yR3r/P//OjIKCWVudW1fb3B0MRIcLmdvb2dsZS5wcm90b2J1Zi5F",
            "bnVtT3B0aW9ucxjontkDIAEoDzo8Cg9lbnVtX3ZhbHVlX29wdDESIS5nb29n",
            "bGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjmoF8gASgFQh2qAhpVbml0",
            "VGVzdC5Jc3N1ZXMuVGVzdFByb3Rvc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UnitTest.Issues.TestProtos.TestMessageWithCustomOptions), global::UnitTest.Issues.TestProtos.TestMessageWithCustomOptions.Parser, null, null, new[]{ typeof(global::UnitTest.Issues.TestProtos.TestMessageWithCustomOptions.Types.AnEnum) }, null)
          }));
    }
`

**Comment by jskeet** [comment]
@plemanach: It's not clear to me which custom option you're talking about, or how it's related to this issue...

**Comment by plemanach** [comment]
I tried to build this proto  👍 
`syntax = "proto3";


import "descriptor.proto";

// We don't put this in a package within proto2 because we need to make sure
// that the generated code doesn't depend on being in the proto2 namespace.
package protobuf_unittest;
option csharp_namespace = "UnitTest.Issues.TestProtos";

extend google.protobuf.EnumOptions {
  sfixed32 enum_opt1 = 7753576;
}

extend google.protobuf.EnumValueOptions {
  int32 enum_value_opt1 = 1560678;
}


// A test message with custom options at all possible locations (and also some
// regular options, to make sure they interact nicely).
message TestMessageWithCustomOptions {
  
  enum AnEnum {
    option (enum_opt1) = -789;
    ANENUM_UNSPECIFIED = 0;
    ANENUM_VAL1 = 1;
    ANENUM_VAL2 = 2 [(enum_value_opt1) = 123];
  }
}


`

**Comment by jskeet** [comment]
Again, if you're facing errors building the resulting C# code, that's unrelated to what this issue is about.

**Comment by xfxyjwf** [comment]
Note that these errors without line number come from a different staging of proto compilation where the DescriptorPool is validating a already parsed FileDescriptorProto. The line numbers are much harder to recover at that stage and likely doesn't worth the effort to support.

**Comment by haon4** [comment]
Most of the errors now have line numbers associated with it. Closing as obsolete.
