### ISSUE TITLE
Disable -Wno-sign-compare

### ISSUE THREAD

**Issue by StefanoD** [protocolbuffers/protobuf#2957]
When compiling Tensorflow, I get tons of sign compare warnings from protobuf.
In your makefile, you say, at Google, you ignore them. But they can be real errors!
In languages like Rust, this is not even compilable!
So it would be cool, if you enable sign compare again.

**Comment by mcy** [comment]
Unfortunately early Google style suggested using `int` for lengths. This is inconsistent with modern C++ practice, so you wind up getting nasty mixed comparison errors.

While I certainly agree with the sentiment, it is not something we have the bandwidth to fix, since it would be a major effort to clean up within Protobuf. I'm going to close this as "not planned", since I'd rather we be clear that we simply do not have the bandwidth to fix this. :(
