### ISSUE TITLE
Inconsistent parsing behaviour between python and c++ implementations

### ISSUE THREAD

**Issue by jake-low** [protocolbuffers/protobuf#322]
I discovered this recently; I'm not sure whether it's intended behaviour or a bug.

In C++, the `ParseFromString()` method fails (i.e. returns `false`) when the input string is empty. However, in the Python implementation, `ParseFromString()` (which is void) does not raise a `DecodeError` if the input string is `""`.

This seems counterintuitive to me, given that in C++ other parse errors are also reported by returning `false` from `ParseFromString()`, and in Python the `ParseFromString()` raises `DecodeError` for most parse failures (e.g. truncated message, unexpected end-group tag, etc). You'd think that if parsing from an empty string in C++ is an error, it would be the same in Python.

See [this gist](https://gist.github.com/jake-low/13c603b962713d3b45cf) for a complete overview and a pair of example programs that reproduce the issue. Note that all tests were using protobuf v2.5.0.

**Comment by xfxyjwf** [comment]
Given that you have "required" fields in your message, the behavior of C++ implementation is correct. Parsing should fail because of unset required fields. I suspect the Python method might have been behave that way since always. That is, Python's ParseFromString method does not throw DecodeError because of absent required fields.

**Comment by elharo** [comment]
upcoming work on Python will resolve this
