### ISSUE TITLE
"Official" Wireshark dissector

### ISSUE THREAD

**Issue by FlorianWolters** [protocolbuffers/protobuf#3303]
**Note:** I know this is not the best place to post this kind of request, but I do not know where to post this elsewhere. Hopefully other people are also interested in this.

----

I do wonder what tools the folks at Google use internally to debug and analyze the Protobuf messages transferred over the wire (if using network communication).

The defacto standard to do network analyzes is the network tool [Wireshark](https://wireshark.org). The functionality of Wireshark can be extended with a *Protocol Dissector* (i.e. a plug-in) to support a (custom) protocol.

I've researched a bit and found the following dissectors for Protobuf:
- [Wireshark Protobuf Dissector](https://github.com/128technology/protobuf_dissector)
  Dissector written in Lua. Does support `proto2` and UDP (without any prefixing) only. Pretty clumsy usage and buggy visualization.
- [Length Prefixed Protocol Buffer Dissector](https://github.com/othrayte/lppb)
  Seems to add length prefix support to the Lua dissector in order to support TCP. Haven't tested it.
- [sst-dissector](https://github.com/pathorn/sst-dissector)
  Undocumented C dissector. Haven't tested it.
- [protobuf-wireshark](https://code.google.com/archive/p/protobuf-wireshark)
  The first C dissector around. Project seems dead. Haven't tested it.
- [protobuf-wireshark (fork)](https://github.com/chrisdew/protobuf-wireshark)
  See above.

There are plenty of requests for a working and user-friendly dissector on the WWW, e.g.:
- [How to make Wireshark tool support Protocol Buffers?](https://ask.wireshark.org/questions/27378/how-to-make-wireshark-tool-support-protocol-buffers)
- [Protocol Buffer Wireshark Plugin](https://ask.wireshark.org/questions/29203/protocol-buffer-wireshark-plugin)
- [Wireshark dissector for a Google Protocol Buffer defined protocol](https://ask.wireshark.org/questions/23808/wireshark-dissector-for-a-google-protocol-buffer-defined-protocol)
- [How to parse protobuf packets in Wireshark](https://stackoverflow.com/questions/42394911/how-to-parse-protobuf-packets-in-wireshark)

I would be very interested in some kind of official Wireshark protocol dissector with the following features:
1. Supports both `proto3` and `proto2`.
2. Supports both UDP and TCP (see point 3). The port ranges for both protocols should be configurable with the GUI of Wireshark (i.e. when to activate the dissector).
3. Supports the configuration of a custom prefix with *length-prefix framing*. The custom prefix is configured by:
    1. The total length (in bytes) of the custom prefix.
    2. The position of the length-prefix.
    3. The length (in bytes) of the length-prefix.
  That would allow to support TCP as well as custom protocols that define additional fields.
4. Supports both generic decoding as well as specific decoding (with the help of provided `.proto` files).
    1. *generic*: Displays a aessage as `[numeric field id:value]` pairs. This does not require the `.proto` file(s).
    2. *specific*: Displays a message as `[field name:value]` pairs.  This requires the `.proto` file(s) for the specific protocol. The addition of `.proto` file(s) should be possible via the GUI of Wireshark and the directory path to the official Protobuf `.proto` files should be configurable as well (e.g. `$PROTOBUF_ROOT/include/google/protobuf`).

At the end of the day it would be very nice to have some kind of official protocol dissector [contributed](https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcContribute.html) to Wireshark.

Are there any efforts towards an official Protobuf dissector for Wireshark? What does the community think? Is this considered useful? Or did I overlook an already existing solution that satisfies the requirements stated above?

**Comment by xfxyjwf** [comment]
In Google, to send protobuf over the wire, you will be using the rpc library (the internal version of http://grpc.io/) instead of writing your own socket code, and a set of tools/libraries are provided to inspect and diagnose the rpc traffic. For example, with a command line tool you can easily write up a proto message in text format and send it to an arbitrary rpc server and get the response in text format. Hardly anyone needs to inspect the network traffic to understand the proto data being sent and it's also very hard to do because the rpc library will compress and encrypt the proto data. People who work on the rpc library probably need to use wireshark or tcpdump to inspect the network traffic, but again they don't need to inspect the proto data (I know they send payload of 1 byte in their tests). So pretty much nobody in Google will need this protobuf dessector for Wireshark and I doubt it will ever be officially supported...

**Comment by ruudsieb** [comment]
Actually after reading the OP I tried using the Length [Prefixed Protocol Buffer Dissector](https://github.com/othrayte/lppb) together with the [protobuf_dissector (forked)](https://github.com/dex/protobuf_dissector). And it was pretty easy to setup and get it to work in my context which is; Wireshark on Windows, TCP connection, length prefix (little endian, for this I made a small change on the lppb).

**Comment by FlorianWolters** [comment]
@ruudsieb Did you get it to work with the proto3 language?

**Comment by ruudsieb** [comment]
Sorry, forgot to mention that, no, I'm using **proto2** message format.

**Comment by AjayNan** [comment]
@FlorianWolters I am also trying to write a wireshark plugin in c to parse google protocol buffers over TCP, but not finding proper source to know how. Have you found any solution for it?

**Comment by FlorianWolters** [comment]
@jfjffilk No, as mentioned in the OP there is currently no out-of-the-box solution working for the proto3 language. For general information how-to implement a Wireshark dissector refer to [Chapter 9. Packet dissection](https://www.wireshark.org/docs/wsdg_html_chunked/ChapterDissection.html) of the official Wireshark documentation. But I **strongly** recommend to contact the author(s) of the [Wireshark Protobuf Dissector](https://github.com/128technology/protobuf_dissector) and to analyse/fork/extend that project before beginning from scratch and implementing your own dissector. Please read the OP again for problems related to the existing Protobuf dissectors.

**Comment by ndandanov** [comment]
I would also be interested in an official Wireshark dissector for protobuf and perhaps gRPC.

I agree that it may not be of much use in Google's environment, however I think that many developers and testers would benefit from it.

**Comment by ndandanov** [comment]
Sorry for double-posting, but I tried a few things after posting above.

I found out, that in the official Wireshark repo on GitHub, there is a gRPC dissector - namely the *wireshark/epan/dissectors/packet-grpc.c* located here: https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-grpc.c

It seems that it was officially added in the end of September this year:
https://github.com/wireshark/wireshark/commits/master/epan/dissectors/packet-grpc.c

*Note that the original Wireshark repo is located on their website. Please check https://www.wireshark.org/develop.html.*


I opted to see how this dissector is working and cloned the Wireshark repo:
```
git clone https://code.wireshark.org/review/wireshark
```

My system is a 64-bit Arch Linux, so I built Wireshark with the following commands:

```
./autogen.sh 
./configure 
make
```
(using this as a reference: https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcBuildFirstTime.html)

It took around 20-30 minutes to build. The Wireshark version is:
![screenshot_2017-11-30_17-09-00](https://user-images.githubusercontent.com/17270267/33437663-5337f27c-d5f1-11e7-9197-6869b0e6e1b3.png)

I then ran it as `root` (in order to be able to capture any traffic) and started capturing the loopback interface.

I cloned, built and started the official gRPC `hello world` server and client from the grpc-java repo:
https://github.com/grpc/grpc-java/tree/master/examples

The console outputs are, as expected:
![screenshot_2017-11-30_16-38-16](https://user-images.githubusercontent.com/17270267/33437171-c5d39982-d5ef-11e7-8edc-d77c72b72e8f.png)

The captured packets in Wireshark are:
![screenshot_2017-11-30_16-39-16](https://user-images.githubusercontent.com/17270267/33437212-e490d52e-d5ef-11e7-9df5-ef71e814774d.png)

Here you can see that they are decoded as TCP packets.

I clicked with the right mouse button on a packet and selected `Decode As...`:
![screenshot_2017-11-30_16-39-39-1](https://user-images.githubusercontent.com/17270267/33437237-fc74da3c-d5ef-11e7-800a-c73dcdf9dc1b.png)

And configured the packets as HTTP2:
![screenshot_2017-11-30_16-40-24](https://user-images.githubusercontent.com/17270267/33437305-2dcb4ada-d5f0-11e7-9493-74ab70197933.png)

And the packets are now correctly recognized as either HTTP2 or gRPC:
![screenshot_2017-11-30_16-40-37](https://user-images.githubusercontent.com/17270267/33437328-40904cb0-d5f0-11e7-8534-e712ef73ac73.png)

Let's take a look at the packet which carries the actual gRPC `hello world` request: 
![screenshot_2017-11-30_16-45-49](https://user-images.githubusercontent.com/17270267/33437346-50059826-d5f0-11e7-981f-9b7b62757d8c.png)

I had also opened the `.proto` file (located here https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto) for reference.

The actual value of field 1 from the `message HelloRequest`, which is `string name`, is "world" (or 77 6f 72 6c 64 in hex):

![screenshot_2017-11-30_16-49-54](https://user-images.githubusercontent.com/17270267/33437430-8ff506d8-d5f0-11e7-8c1c-e5853acafa0d.png)

And we can verify this:
![screenshot_2017-11-30_16-49-39](https://user-images.githubusercontent.com/17270267/33437477-c1a6f48e-d5f0-11e7-9582-6953704f26ab.png)

The gRPC `hello world` response was of course "Hello world":
![screenshot_2017-11-30_16-50-18](https://user-images.githubusercontent.com/17270267/33437502-d0d1bbf6-d5f0-11e7-94f4-f6bdf06fb4cf.png)


The Wireshark interpretation of fields and their values could definitely be extended. I did not come across any option to specify and input `.proto` file to extract the field names and correct value types. This leads to some `double`s represented as just `uint64` in Wireshark.

Nevertheless, I think this is a significant improvement in the right direction.

Please share your opinion on this dissector. Has anyone else tried it and published some results/improvements?
Is there any public information regarding the release of this dissector?
Kind regards!

**Comment by xfxyjwf** [comment]
@ndandanov Great findings! Could you also post this to grpc github repo? I think lots of grpc users will find this useful.

**Comment by ndandanov** [comment]
Hi @xfxyjwf, thank you for the kind words!
I added the above to the following issue: https://github.com/grpc/grpc/issues/13586

I also recorded two videos which show the process in depth. They are somewhat lengthy and unfortunately I could not replicate the same successful packet dissection - probably due to the slightly newer development version of Wireshark.

Nevertheless, they could be of help to somebody:
**gRPC Wireshark dissector - Part 1: https://youtu.be/LoGArC58Row**
**gRPC Wireshark dissector - Part 2: https://youtu.be/Wj9VoJQf-qc**

**Comment by abhinava** [comment]
@ndandanov This is really great! Do you happen to have any packet captures (PCAP files)?

**Comment by abhinava** [comment]
@ndandanov Found it in your previous post :) https://github.com/ndandanov/wireshark-grpc/blob/master/grpc-hello-world.pcapng

**Comment by haon4** [comment]
Thank you for all the posts here. Posting them at an issue doesn't seem like the best place though. I'd recommend creating a page somewhere, and add a link to that page at https://github.com/protocolbuffers/protobuf/blob/master/docs/third_party.md. You would probably want to reach out to gRPC and figure out where to best post it there too. Thanks!

**Comment by huangqiangxiong** [comment]
Hope following information might be useful: 

New features about Protobuf and gRPC dissectors have been added into Wireshark since version 3.2.0:
1. Protobuf files (*.proto) can now be configured to enable more precise parsing of serialized Protobuf data (such as gRPC).
2. The message of stream gRPC method can now be parsed with supporting of HTTP2 streaming mode reassembly feature.
3. User can specify protobuf search paths (where has *.proto files), and the UDP ports to protobuf message type maps at the Protobuf protocol preferences.
4. If your own dissectors need invoke protobuf dissector, you can pass the message type to Protobuf dissector by data parameter (in C) or pinfo->private_table["pb_msg_type"] (pinfo.private["pb_msg_type"] in lua).

Another two new features will be released in 3.3.0 or 3.4.0:
1. Protobuf fields can be dissected as wireshark (header) fields that allows user input the full names of Protobuf fields or messages in Filter toolbar for searching.
2. Dissector based on Protobuf can register itself to a new 'protobuf_field' dissector table, which is keyed with the full names of fields, for further parsing fields of BYETS or STRING type. 

Preferences userguide:
https://www.wireshark.org/docs/wsug_html_chunked/ChProtobufSearchPaths.html
https://www.wireshark.org/docs/wsug_html_chunked/ChProtobufUDPMessageTypes.html

**Comment by jtattermusch** [comment]
@huangqiangxiong  would you be interested in writing a guest blogpost for https://grpc.io/blog/ about how to use wireshark with grpc and what are some of the new features?

**Comment by huangqiangxiong** [comment]
OK.&nbsp; But I may spend a little time to study how to get the privilege to post article on that website.&nbsp;



---Original---

**Comment by jtattermusch** [comment]
Btw a blogpost is created by opening a PR (e.g. https://github.com/grpc/grpc.io/pull/121).

**Comment by Alex-David-Hu** [comment]
I know






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jan Tattermusch"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 下午2:57
收件人:&nbsp;"protocolbuffers/protobuf"<protobuf@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [protocolbuffers/protobuf] "Official" Wireshark dissector (#3303)





 
Btw a blogpost is created by opening a PR (e.g. grpc/grpc.io#121).
