### ISSUE TITLE
[Ruby] Reload protobuf definition

### ISSUE THREAD

**Issue by Elyahou** [protocolbuffers/protobuf#3814]
I wan't to reload the protobuf definition in my ruby code when schema change.

But when I try to reload it I got this error:

`RuntimeError: Unable to add defs to DescriptorPool: Symtab already has a def named 'proto.example'`

To reproduce it just run twice this code:
```
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "proto.example" do
    optional :test, :string, 1
  end
end
```

Is there a way to clean the `generated_pool` before reloading it ?

**Comment by haberman** [comment]
Would you be reloading all _pb files, or just the ones that change?

I think it would be difficult to clear some types but not others.

**Comment by oggy** [comment]
I'd ❤️ to be able to just clear everything. Super helpful for Rails-style workflows where you want to unload stuff between dev iterations. We can let the app figure what if anything it needs to reload right away.

**Comment by JasonLunn** [comment]
Based on https://github.com/protocolbuffers/protobuf/pull/4995#issuecomment-412655882 - a community contributed PR that added the capability to set `generated_pool` could be a viable way to move forward.

Since this feature request has not been prioritized in the years since it was opened and there have not been any recent follow ups, I'm closing and leaving it labeled `help wanted`.
