### ISSUE TITLE
Add props file to Google.Protobuf.Tool

### ISSUE THREAD

**Issue by iskiselev** [protocolbuffers/protobuf#3820]
It is hard to integrate protoc from Google.Protobuf.Tool to MsBuild scripts, as it hard to resolve actual path to protoc. It could be greatly simplify, if package will contain file build/Google.Protobuf.Tool.props with text like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <protoc64>$(MSBuildThisFileDirectory)..\tools\windows_x64\protoc.exe</protoc64>
    <protoc86>$(MSBuildThisFileDirectory)..\tools\windows_x64\protoc.exe</protoc86>
  </PropertyGroup>
</Project>
```
With it call to protoc from MsBuild file will be possible with `$(protoc64)` ms-build expression.

**Comment by kkm000** [comment]
This would be an amazing feature!

Since the package is crosspatform, however, it would probably be a better idea just to define one property for a root tool directory, like
```xml
<GoogleProtoCompilerRoorDir>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/'))</GoogleProtoCompilerRoorDir>
```

The GetFullPath function will take care of proper path separators in the property name; you can give it any mix of `\` and `/`, and it'll straighten them out for the system it runs on.

Also, if submitting a patch, please omit the `ToolsVersion` attribute from the project. It does nothing except producing a warning when used in .props/.targets files; the parent project ToolsVersion takes precedence.

**Comment by ObsidianMinor** [comment]
Targets added through https://github.com/google/protobuf/pull/4648

**Comment by kkm000** [comment]
Thank you @ObsidianMinor!

**Comment by kkm000** [comment]
@anandolee, this is resolved, please close!

**Comment by kkm000** [comment]
/cc @jtattermusch

@ObsidianMinor, @anandolee: #4648 is a very breaking change. Please please do not ship it as is, requires fixing. It blindly relies on MSBuild version 15.3+, and .NET Framework 4.7.1+ or .NET Core. Otherwise, a project adding the package will not even load.

So this works with .NET SDK, but breaks on Windows unless very latest build tools *and* .NET Framework are installed. And on Mono, no support at all.

I would just remove the `<protoc Condition=...` lines. It is well known that there is no universally consistent way to figure out the OS and platform from inside all of living MSBuild species, outside of .NET Core (or its backported functionality in .NET 4.7.1+). Even finding the MSBuild version itself is a tricky task, so even degrading gracefully not to define `protoc` property in a less capable MSBuild  is quite a scripting task! I am resolving tools directory this in Grpc.Tools with a custom build task, and weeks of work went into making tool resolution backwards-compatible with VS2013+ and Mono.

So instead of defining the `protoc` property, I'd just stop at defining the root directory, [as was initially suggested](https://github.com/google/protobuf/issues/3820#issuecomment-342011424) and leave the rest to the user. 

Also, please add namespace to the first line as `<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`, otherwise it won't be compatible even with MSBuild v14.x!

**Comment by kkm000** [comment]
This more or less degrades ok under Windows (I saved it as pb.props for testing below):

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <protoc_linux64>$(MSBuildThisFileDirectory)..\tools\linux_x64\protoc</protoc_linux64>
        <protoc_linux86>$(MSBuildThisFileDirectory)..\tools\linux_x86\protoc</protoc_linux86>
        <protoc_macosx64>$(MSBuildThisFileDirectory)..\tools\macosx_x64\protoc</protoc_macosx64>
        <protoc_macosx86>$(MSBuildThisFileDirectory)..\tools\macosx_x86\protoc</protoc_macosx86>
        <protoc_windows64>$(MSBuildThisFileDirectory)..\tools\windows_x64\protoc.exe</protoc_windows64>
        <protoc_windows86>$(MSBuildThisFileDirectory)..\tools\windows_x86\protoc.exe</protoc_windows86>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(MSBuildRuntimeType)' == 'Core' or
                                ('$(MSBuildVersion)' != '' and 
                                  $([System.Version]::Parse($(MSBuildVersion))) &gt;= $([System.Version]::Parse(15.3))) ">
        <protoc Condition="'$([MSBuild]::IsOsPlatform(Linux))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X64'">$(protoc_linux64)</protoc>
        <protoc Condition="'$([MSBuild]::IsOsPlatform(Linux))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X86'">$(protoc_linux86)</protoc>
        <protoc Condition="'$([MSBuild]::IsOsPlatform(OSX))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X64'">$(protoc_macosx64)</protoc>
        <protoc Condition="'$([MSBuild]::IsOsPlatform(OSX))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X86'">$(protoc_macosx86)</protoc>
        <protoc Condition="'$([MSBuild]::IsOsPlatform(Windows))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X64'">$(protoc_windows64)</protoc>
        <protoc Condition="'$([MSBuild]::IsOsPlatform(Windows))' And '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)'=='X86'">$(protoc_windows86)</protoc>
    </PropertyGroup>
    <Target Name="Build">
      <Message Importance="high" Text="'$(protoc_linux64)'" />
      <Message Importance="high" Text="'$(protoc)'" />
    </Target>
</Project>
```

New MSBuild:
```
c:\temp> msbuild pb.props
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18-06-22 11:27:32.
Project "c:\temp\pb.props" on node 1 (default targets).
Build:
  'c:\temp\..\tools\linux_x64\protoc'
  'c:\temp\..\tools\windows_x64\protoc.exe'
Done Building Project "c:\temp\pb.props" (default targets).
```

Older MSBuild (protoc is undefined, but at the least there is no error):
```
C:\temp> C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild pb.props
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18-06-22 11:27:56.
Project "C:\temp\pb.props" on node 1 (default targets).
Build:
  'C:\temp\..\tools\linux_x64\protoc'
  ''
Done Building Project "C:\temp\pb.props" (default targets).
```

**Comment by kkm000** [comment]
But I am not sure what to expect with MSBuild >= 15.3 on Windows 7, where `System.Runtime.InteropServices.RuntimeInformation` might not be present. So better do not.

**Comment by ObsidianMinor** [comment]
Well, that sucks. I'll make a new PR to remove those elements, I never realized their addition was so recent.

**Comment by kkm000** [comment]
> I never realized their addition was so recent.

if you are interested in this saga (just one of the whole multiplatform MSBuild epics), the discussion is here: https://github.com/Microsoft/msbuild/issues/539.

It's really tough to expand a 20-year old build system used by millions in the wild, and also cloned by an outside project (Mono) without breaking its API and behaviors, and, having read MSBuild code and contributed a couple of small fixes, I can really the great lengths the MSBuild SWE have to go to support backward compatibility. This also implies, naturally, that scripting build snippets that are compatible with all the many dozens of MSBuild version, platform and even vendor variants, which are in the wild today, is a tricky business. While simple conditions like `'$(MSBuildRuntimeType)' == 'Core'` are easily backwards-compatible and correct (the property is not set in non-Core builds), even an innocuously looking API invocation, like `$([System.Version]::Parse($(MSBuildVersion)))` is dangerous, as the function throws if given an empty string as an argument, and even `MSBuildVersion`, which is easy to take for granted, does not exist is older MSBuild versions. And any exception in property evaluation prevents the build from proceeding (and, should it happen in a static property evaluation, causes the project load in Visual Studio to fail, as VS also uses the MSBuild engine to load the project, and even invokes a few manifest targets from it to discover the list of project files and other certain things).

So in the end, *almost all* additions to MSBuild are "recent," given it's long history. It has been expanded greatly due to the multiplatform work. And it's still WIP. The first stage was to make *an* MSBuild for the new .NET Core platform for Linux etc. Now it seems to be in the phase of convergence, when all the API added to .NET Core are being added to .NET Framework. But this is happening only now, with the Framework version 4.7.1+, and too many field installation still do not have it. Good thing is Windows 10 comes with it, and upgraded automatically with every semiannual release. Bad thing is that even Windows Server editions of the same OS are often not (enterprise admins are conservative), that Windows 7 came with 3.5, the first .NET on the CLR4, and is still supported and used widely, and that people also run all different versions of Mono. The APIs are converging now, but sadly it will take years to pass before anyone can take the new features for granted and just say "oh, just update your build tools, you rig is too ancient to support!"

On the practical side, one can guess the platform OS from different clues, including probing for the existence of well-known runtime .dylib files to tell Linux apart from OSX), but host bitness (64 or 32) can be guessed only by probing for well known files (e. g. /lib64). Tricky and unreliable business (what if the user unwittingly installed a badly scripted deb package that creates /lib64 on a 32-bit system?) without adding a custom MSBuild task or requiring MSBuild 15.3+, which is yet too new.

Sorry about the long-winded comment. I just wanted to share some of the stuff I learned, mostly unwillingly, while solving similar problems when I was writing compatible build scripts for another project.

**Comment by kkm000** [comment]
And thank you @ObsidianMinor again for your contribution and collaboration. This change, even if it does not fully abstract the tool location, makes life a lot easier for the package users!

**Comment by deannagarcia** [comment]
Closing as this looks resolved to me. If there is still an action item for the protobuf team, feel free to reopen!
