### ISSUE TITLE
Please add MessageParser<Value>.TryParse api to C#

### ISSUE THREAD

**Issue by Thaina** [protocolbuffers/protobuf#4100]
I would like to suggest that MessageParser base class should have TryParse function for additional to `ParseDelimitedFrom` `ParseFrom` and `ParseJson` that return boolean and out value

So we could check for message that it parsable and handle alternate logic if it not parsable instead of expensive try/catch

**Comment by mihalios** [comment]
Hi, 

Is this something we can hope to see added soon?

**Comment by Thaina** [comment]
It seem not likely for 7 years. Is it too hard or impossible?

**Comment by bill-poole** [comment]
A `TryParseFrom` method (and `TryParseDelimitedFrom` method) would be useful for parsing a length-delimited stream of protobuf-encoded messages using a `System.IO.Pipelines.PipeReader` in .NET. Parsing from a pipe reader works on the basis of trying to parse a minimum parsable unit from a buffer `ReadOnlySequence<byte>` - if the parse is successful, the buffer is advanced; however if unsuccessful, then the buffer position remains the same, but more data is read into the buffer and the parse operation is retried.

This try/retry mechanism relies on the parser having a "try parse" operation. However currently, we must try to parse using `ParseFrom` and retry if `InvalidProtocolBufferException` is thrown, which hurts performance because exceptions are slow.
