### ISSUE TITLE
Offer new "ToBytes" and "FromBytes" behaviors as successors of "SerializeToString" and "FromString"

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [protocolbuffers/protobuf#4115]
Now that [Python 3 has finally won](https://twitter.com/pycharm/status/865659029460209664), the names of the behaviors `SerializeToString` and `FromString` are especially problematic as the former doesn't return instances of `str` and the latter doesn't accept instances of `str` (right?).

It would be better if the API offered successor methods more helpfully named `ToBytes` (or maybe `SerializeToBytes` if strictly necessary, but `ToBytes` is definitely the more attractive name) and `FromBytes`.

**Comment by anandolee** [comment]
Yes, they return/use bytes instead of str. But it might not good to remove or change the behavior of  SerializeToString/FromString which breaks users. Add new ToBytes/FromBytes and do the same thing with current APIs may also confusing...

@xfxyjwf  @haberman do you have any thoughts on it?

**Comment by xfxyjwf** [comment]
+1 to add SerializeToBytes/ParseFromBytes and deprecate SerializeToString/ParseFromString.

Besides the problematic behavior of not accepting/producing str in Python 3, the name SerializeToString/ParseFromString are often mistaken to be related to text format and I see quite a few times people trying to use ParseFromString to parse text format data...

IMHO, adding SerializeToBytes/ParseFromBytes won't make it more confusing. If an user wants to serialize a proto into binary, SerializeToBytes is apparently up for the job, whereas SerializeToString may or may not produce a binary output. I wouldn't try to use SerializeToString when SerializeToBytes is available. There is even less confusion if SerializeToString is marked deprecated. If there is only SerializeToString, I would have to double check it actually produces binary data because the name suggests something else.

**Comment by anandolee** [comment]
Agree with "the name SerializeToString/ParseFromString are often mistaken to be related to text format". But it is then not only a python issue, C++ is also using SerializeToString() for wire format, and maybe some other languages. Do you think we should make changes for other languages too?

**Comment by nathanielmanistaatgoogle** [comment]
@xfxyjwf: correct - Python just has `bytes` (which are bytes), `unicode` (which is unicode), and `str` (which is pronounced "string" or "native string" and is `bytes` in Python 2 and `unicode` in Python 3). Python doesn't have "string", "StringPiece", "Cord", or anything else (I don't think?).

**Comment by daravi** [comment]
What really confuses me is why this has not been mentioned in the documentation:
> SerializeToString(): serializes the message and returns it as a string. Note that the bytes are binary, not text; *we only use the str type as a convenient container*  

With no mention of the different type (`bytes`) being used in Python 3.

**Comment by wimax-grapl** [comment]
The documentation bit (or even, dare I say, pep484 types on these) would be an easy win. 
Basically, the line:
> we only use the str type as a convenient container.
is wrong and misleading for py3. It just returns a `bytes` object.

**Comment by anandolee** [comment]
We are adding support for Nextgen (Pythonic) APIs. The binary parse/serialize APIs are:
```
def serialize(message: _MESSAGE, deterministic: bool = None) -> bytes:
def parse(message_class: Type[_MESSAGE], payload: bytes) -> _MESSAGE:
```

in https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/proto.py
