### ISSUE TITLE
Zero-value Enum types are not be seted correctly  in objectivec language

### ISSUE THREAD

**Issue by zhangyangsk8** [protocolbuffers/protobuf#4152]
define enum type in some.pbobjc.h:
typedef GPB_ENUM(someStatus) {
  Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  StatusNotStart = 0,
  StatusStart = 1,
  StatusPaused = 3,
  StatusStop = 4,
};
define a Property in otherClass like this:
@property (nonatomic, assign) someStatus type;

otherClass.type = StatusNotStart;//can not be seted the zero-value
otherClass.type = StatusStart;//if the value is not zero-value it can be seted correctly

**Comment by thomasvl** [comment]
I'm guessing this is a .proto file with the `syntax` of `proto3`?  https://developers.google.com/protocol-buffers/docs/proto3 explains the syntax, in that, all single fields get _cleared_ also by setting them to the zero value (they also don't need to serialize because the default is the zero value).  So this is working to spec.
