### ISSUE TITLE
When exporting symbols, an include directive may be necessary

### ISSUE THREAD

**Issue by mathstuf** [protocolbuffers/protobuf#4198]
It'd be nice to have an option to add `#include "mylib_export.h"` to generated `.pb.h` files so that export symbols are defined before their use.

**Comment by TeBoring** [comment]
If your code depends on symbols in mylib_export.h, it's a better practice to directly include that in your code instead of indirectly included from our generated code.

**Comment by mathstuf** [comment]
Umm, but protobuf is also generating code using an export macro (`dllexport_decl=` on the command line or `EXPORT_MACRO` in CMake), so it should include the file which provides that macro.

**Comment by mathstuf** [comment]
@TeBoring Thoughts on the above comment?

**Comment by traversaro** [comment]
>  Since symbols in mylib_export.h is not used by .pb.cc, I don't think .pb.h needs to import that.

I faced a similar problem (see https://github.com/ros-industrial/abb_libegm/pull/63), and  I am bit confused by this comment. The macro passed to `dllexport_decl`, if they are defined in  `mylib_export.h`, need to include by the preprocessor when generating the code for the compilation unit corresponding to `.pb.cc` file, otherwise the compiler will complain because the macro is not defined. 

I noticed that some projects deal with this problem by defining a custom generator (see https://bitbucket.org/osrf/gazebo/src/804410860234af97c5e309896dc007e8cde04ba8/gazebo/msgs/generator/GazeboGenerator.cc#lines-72 and https://bitbucket.org/ignitionrobotics/ign-msgs/src/18640ef6c31777e25953ae44b6ad10ed68c4993e/src/Generator.cc#lines-106), but it would be nice to be able to insert a user-specified included header without implementing a custom generator. If there is an interest in merging such an option, I would be happy to provide a PR.

**Comment by mathstuf** [comment]
I think a PR with a test case would help a lot with this. I forget how I worked around it in the project that I found this with. But, getting the attention of a Googler back on this is probably a prerequisite given how I've seen other things happen on this project :( . Hopefully a PR would do that, but who knows.

**Comment by traversaro** [comment]
Interestingly, Chromium has a protoc wrapper that adds the necessary includes in the generated `.pb.h`  via a  `--include` option: https://github.com/chromium/chromium/blob/80.0.3974.1/tools/protoc_wrapper/protoc_wrapper.py#L90 . 

The motivation for this wrapper is indeed to correctly handle export macros, see: https://github.com/chromium/chromium/blob/80.0.3974.1/third_party/protobuf/proto_library.gni#L34 .

**Comment by mathstuf** [comment]
The author of the latter doesn't have an (obvious) github username, but @gkraynov refactored the former last. Maybe they could get some attention on this to avoid having such a workaround in chromium's vendoring of protobuf in the future :) .

**Comment by traversaro** [comment]
In my specific case, the workaround that I found is to force the inclusion of the visibility header via the MSVC option [`/FI`](https://docs.microsoft.com/en-us/cpp/build/reference/fi-name-forced-include-file?view=vs-2019) for all the compilation unit that are part of the library or if they link the library that contains the protobuf-generated code, see https://github.com/ros-industrial/abb_libegm/pull/63#issuecomment-557553377 . This solution is a bit brittle, but it seems to be working.

**Comment by imrichardcole** [comment]
This still appears to be an issue in 2025?  Is `/FI` still the best option for this?

**Comment by mathstuf** [comment]
For the compilation of the `.pb.cc` file, it is probably sufficient. If the header itself is included from elsewhere, all consumers may need it (or to `#include` the header before the `.pb.h` file manually).
