### ISSUE TITLE
c++: gRPC service descriptors are missing if the source proto has no messages defined

### ISSUE THREAD

**Issue by kyessenov** [protocolbuffers/protobuf#4221]
It seems that if my protobuf file consists of a single service, and I link against the resulting `.pb.h` then the service descriptor is missing from the generated descriptor pool. For context, this is happening in Envoy (https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cds_api_impl.cc#L40) using Bazel to generate protobuf files.   

The workaround is to (1) add a dummy message to the service proto; (2) instantiate the dummy message from the resulting `.pb.h` file.  

cc @htuch

**Comment by xfxyjwf** [comment]
What you observed is most likely due to the linker dropping unused symbols (i.e., the descriptor registering code is not reachable from your application code so they got removed by linker). Besides adding a dummy message and referencing it in C++ code, there are a few other options:
1. Add "option cc_generic_services = true;" to the proto file and reference the generated service code.
2. Use bazel's always_link attribute to prevent linker dropping the proto library.

**Comment by htuch** [comment]
`always_link` makes the most sense in our situation, since we do not want to use the generated service code. @kyessenov can you confirm this works? Thanks @xfxyjwf.
