### ISSUE TITLE
Extranous code in python protobuf generation

### ISSUE THREAD

**Issue by nmiculinic** [protocolbuffers/protobuf#4295]
For this example proto file:
```
syntax = "proto2";
package etcdserverpb;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;

message Request {
	optional uint64 ID         =  1 [(gogoproto.nullable) = false];
	optional string Method     =  2 [(gogoproto.nullable) = false];
	optional string Path       =  3 [(gogoproto.nullable) = false];
	optional string Val        =  4 [(gogoproto.nullable) = false];
	optional bool   Dir        =  5 [(gogoproto.nullable) = false];
	optional string PrevValue  =  6 [(gogoproto.nullable) = false];
	optional uint64 PrevIndex  =  7 [(gogoproto.nullable) = false];
	optional bool   PrevExist  =  8 [(gogoproto.nullable) = true];
	optional int64  Expiration =  9 [(gogoproto.nullable) = false];
	optional bool   Wait       = 10 [(gogoproto.nullable) = false];
	optional uint64 Since      = 11 [(gogoproto.nullable) = false];
	optional bool   Recursive  = 12 [(gogoproto.nullable) = false];
	optional bool   Sorted     = 13 [(gogoproto.nullable) = false];
	optional bool   Quorum     = 14 [(gogoproto.nullable) = false];
	optional int64  Time       = 15 [(gogoproto.nullable) = false];
	optional bool   Stream     = 16 [(gogoproto.nullable) = false];
	optional bool   Refresh    = 17 [(gogoproto.nullable) = true];
}

message Metadata {
	optional uint64 NodeID    = 1 [(gogoproto.nullable) = false];
	optional uint64 ClusterID = 2 [(gogoproto.nullable) = false];
}
```

few extra lines are generated:

```
from github.com.gogo.protobuf.gogoproto import gogo_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2

```

Also the resulting .py file depends on github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2.DESCRIPTION which is also a mistake. 

https://github.com/gogo/protobuf/issues/376
@awalterschulze

**Comment by arthur-tacca** [comment]
(Note: I am not a protobuf maintainer, I am just passing by. No warrenties on the contents of this comment.)

There are a few problem with the way you're calling protoc:

 * You're not passing `gogo.proto` to protoc. If you did, it would generate the corresponding `pb2`, so you wouldn't get an import error.
 * You're not using the correct relative path for `gogo.proto`. Perhaps everything will actually work with this incorrect path once you fix the previous point, but you'll find the generated `gogo_pb2.py` is in a surprisingly deep nested directory, and actually it will probably still break because `github.com` is not a valid Python package name.

## Passing `gogo.proto` to protoc

This is pretty easy. Just add it to your command line, including the full path:

    protoc -I=. -I=$GOPATH/src -I=$GOPATH/src/github.com/gogo/protobuf/protobuf --python_out=. etcd.proto $GOPATH/src/github.com/gogo/protobuf/protobuf/gogoproto/gogo.proto


## Fix relative path of `gogo.proto`

Compare the file path against the first `-I` it matches to get the relative path:

    file: $GOPATH/src/github.com/gogo/protobuf/protobuf/gogoproto/gogo.proto
    -I:   $GOPATH/src
    rel:  github.com/gogo/protobuf/protobuf/gogoproto/gogo.proto

But the relative path ought to just be `gogoproto/gogo.proto`. To fix the problem, remove that `-I=$GOPATH/src` option; you don't seem to be using it for anything. Then the path will match against the other import switch:

    file: $GOPATH/src/github.com/gogo/protobuf/protobuf/gogoproto/gogo.proto
    -I:   $GOPATH/src/github.com/gogo/protobuf/protobuf
    rel:  gogoproto/gogo.proto

This is the correct relative import. So your protoc invocation now looks like this:

    protoc -I=. -I=$GOPATH/src/github.com/gogo/protobuf/protobuf --python_out=. etcd.proto $GOPATH/src/github.com/gogo/protobuf/protobuf/gogoproto/gogo.proto

You'll need to change the `import` statement in the `etcd.proto` to reflect this, back to what it originally was. The fact you had to change this before was the hint that something wasn't right in the way you were calling `protoc`. 


## Bonus changes: Package for `etcd_pb2.py`

I would suggest putting etcd.proto in a directory e.g. `etcdserverpb`, but leave the `-I.` (i.e. pointing to its parent directory). This way the generated file is considered to be in a Python package i.e. you would import it with `import etcdserverpb.etcd_pb2`.
