### ISSUE TITLE
Cannot install specific version 3.5.1.2-universal-darwin

### ISSUE THREAD

**Issue by cdelrosario** [protocolbuffers/protobuf#4499]
I am trying to install a specific version on Mac OSX High Sierra 10.13.4 and am getting an error below:

```
gem install google-protobuf -v 3.5.1.2-universal-darwin
ERROR:  Could not find a valid gem 'google-protobuf' (= 3.5.1.2.pre.universal.pre.darwin) in any repository
ERROR:  Possible alternatives: google-protobuf
```

The reason I am try a specific one is we have to deal with local development on a Mac as opposed to a production deploy which is Unix.

When we deploy in Unix we get a different error because the gems are vendored:
In the unix deployement we get:
`
Could not find google-protobuf-3.5.1.2 in any of the sources
`

**Comment by mhoad** [comment]
Possibly worth mentioning that I am also seeing this exact error when trying to deploy a Rails app to App Engine Flex.

**Comment by BonMatts** [comment]
Running into the same issue when deploying a project to travis. Has anyone discovered any work arounds?

**Comment by BonMatts** [comment]
A work around I found for this issue was to 

1. spin up an instance of your CI environment in docker. in my case, [travis](https://docs.travis-ci.com/user/common-build-problems/#troubleshooting-locally-in-a-docker-image)
2. run bundle install in that instance
3. commit and push the relevant gems in vendor/cache (in my case ` google-protobuf-3.6.1-x86_64-linux.gem ` and `grpc-1.14.1-x86_64-linux.gem`) from the docker container using a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/)
4. destroy the personal access token

**Comment by TeBoring** [comment]
I think we have uploaded it: https://rubygems.org/gems/google-protobuf/versions/3.5.1.2-universal-darwin
Is it an issue of gem?
