### ISSUE TITLE
[cpp] Generate enum classes instead of enums

### ISSUE THREAD

**Issue by gioragutt** [protocolbuffers/protobuf#4513]
We have our internal schemas, from which we generate our ORM classes. We had to generate `.proto` files for all the classes and enums.

Along the way, we realized we had to prefix enums values with the enum name due to the generated enums, as they are not enum classes.

Is there any place that describes why are enum classes not used?

I would like to add a PR for it, but I want to know if there's a point to do that.

**Comment by acozzette** [comment]
@gioragutt I think the original reason was that until recently we supported C++98, and enum classes were introduced only in C++11. That's no longer a problem by itself now that we require C++11, but still I suspect it would be difficult to make this change since it would have to be done in a way that doesn't break compatibility with existing code.

**Comment by gioragutt** [comment]
@acozzette reading #3625, there seems there's an issue with protobuf's internal representation of enums, as enum names are global in the scope of protobuf's internal scope (not cpp symbol scope).

Obviously code would be broken, since the generated enums are `enum`s and not `enum class`es, meaning that they must have been used as such.

Usually the solution for this is to put this behind a flag, and give a grace period before making this the default behavior.

**Comment by acozzette** [comment]
The thing is that we try hard to avoid adding new flags, because the work of maintaining them adds up in the long term. If the flag is temporary then that cuts down on the maintenance burden but it's still not ideal to break backward compatibility. Unfortunately I think it's not really worth it to try to make this change at this point.
