### ISSUE TITLE
OneofOptions extend in proto3 lite gives error.

### ISSUE THREAD

**Issue by sridharsundaram** [protocolbuffers/protobuf#4744]
This piece of unittest_custom_options.proto gives an error in proto3 lite
"Extensions in proto3 are only allowed for defining options"

extend google.protobuf.OneofOptions {
  int32 oneof_opt1 = 7740111;
}
--------------------------------------------
Error can be traced to   descriptor.cc in method 
``void InitAllowedProto3Extendee()``

In lite, this has   

`const char* kOptionNames[] = {
      "FileOptions",      "MessageOptions", "FieldOptions", "EnumOptions",
      "EnumValueOptions", "ServiceOptions", "MethodOptions"};`

while in proto3 same method has 

`  const char* kOptionNames[] = {
      "FileOptions",      "MessageOptions", "FieldOptions", "EnumOptions",
      "EnumValueOptions", "ServiceOptions", "MethodOptions", "OneofOptions"};`

I would expect OneofOptions to be supported in the same way in proto3 lite as in proto3.

**Comment by acozzette** [comment]
I think the problem here is that for compatibility reasons we have not released a new Java lite version in a while, so if you're using Java lite then you're most likely using an old `protoc` version that hasn't had `OneofOptions` added to that list yet. But hopefully the situation here will improve soon, since we're planning on updating Java lite and moving it to its own repo.

**Comment by elharo** [comment]
should be fixed now
