### ISSUE TITLE
[Java] Proto generated classes do not shade easily due to shade plugin corrupting internal string constants in generated code

### ISSUE THREAD

**Issue by lukecwik** [protocolbuffers/protobuf#4749]
It is a common pattern for the proto package path and the java package to be the same string when generating protobufs. This typically causes issues when shading generated proto classes because shading tools search and replace string constants within classes that match package path strings with the relocated variant.

For example `org.apache.beam.model.pipeline.v1.AccumulationMode.Enum` was changed to `org.apache.beam.repackaged.beam_runners_direct_java.model.pipeline.v1.AccumulationMode.Enum`. This made loading the class fail because the varint field describing the string length was no longer correct causing the descriptor parsing to fail.

See https://issues.apache.org/jira/browse/BEAM-4484 for more details.

Please obfuscate string constants within the generated code (such as base64 encoding) to make it easier for users to shade proto generated classes.

**Comment by ejona86** [comment]
CC @garrettjonesgoogle

**Comment by ejona86** [comment]
This seems it would always be a problem when shading protobuf, because either the java package name matches the proto package (which should not be changed during shading) or the `option java_package` value (which may be fine to change, with the exception of length changing problems).

I do wonder whether the shading tool's over-zealousness is widespread. This issue was experienced with Gradle's shadow plugin. It'd be interesting to do a test and see the behavior of jarjar and Maven shade, if for no other reason to better understand the various behaviors.

**Comment by lukecwik** [comment]
It turns out its not always a problem because I decompiled the class and looked at what changed and only one of the many package strings were replaced. Since the field is being interpreted as ISO 8859-1 to get access to the raw bytes, I assume the string matching doesn't always get a hit on the descriptor field. You just have to get unlucky like I did.

**Comment by ejona86** [comment]
Hmm... that sounds incomplete. Since package names are ASCII and strings in protobuf are byte aligned, I'm not sure what source of randomness there may be. Maybe the varint was 0x20 which was interpreted as a space which then matched for replacement?

**Comment by elharo** [comment]
shading is a hack at best. TBH this feels like a bug in the shader.
