### ISSUE TITLE
Unclear documentation for SerializeWithCachedSizes

### ISSUE THREAD

**Issue by rnburn** [protocolbuffers/protobuf#5026]
The notes on this documentation for the  [SerializeWithCachedSizes](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message_lite#MessageLite.SerializeWithCachedSizes.details) function aren't clear to me.

> The message must not have changed since the last call to ByteSize(), and the value returned by ByteSize must be non-negative. Otherwise the results are undefined.

Are you required to call ByteSize (you can't use [ByteSizeLong](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message_lite#MessageLite.ByteSizeLong.details))? And when would ByteSize return a negative number? what does ByteSizeLong return in that case given that it uses an unsigned integer?

**Comment by acozzette** [comment]
I think that documentation is just out of date because it predates the existing of `ByteSizeLong`. The problem we used to have is that some people were trying to serialize huge protos, more than 2 GiB in size. That's the scenario where `ByteSize()` could end up returning a negative number, because the true value wouldn't fit in a signed 32-bit int. `ByteSizeLong()` will always return the correct value because it's pretty near impossible to create a message whose size won't fit in a `size_t`.

Just to be safe it's probably best to use `ByteSizeLong`, but in practice I don't think you'll run into any issues unless you're working with huge protos.
