### ISSUE TITLE
how to build protoc for linux-x86_64

### ISSUE THREAD

**Issue by CooperLuan** [protocolbuffers/protobuf#5096]
how to build protoc for `linux-x86_64` like `protoc-3.6.1-linux-x86_64.zip` ?

**Comment by acozzette** [comment]
We generate those zip files using the build-zip.sh [script](https://github.com/protocolbuffers/protobuf/blob/master/protoc-artifacts/build-zip.sh) and the instructions [here](https://github.com/protocolbuffers/protobuf/tree/master/protoc-artifacts#upload-zip-packages-to-github-release-page). Note that what the script does is download protoc binaries from the Maven Central Repository and package them. I'm guessing that is probably not exactly what you want to do, but you could modify the script so that it gets a `protoc` binary from a different location you choose.

**Comment by CooperLuan** [comment]
it works, thanks
