### ISSUE TITLE
Where to find the protoc executable for Windows 10? 

### ISSUE THREAD

**Issue by emailtovamos** [protocolbuffers/protobuf#5205]
I downloaded the zip file from [here](https://github.com/protocolbuffers/protobuf/releases) and unzipped to see a folder like this: 

![protodoubt](https://user-images.githubusercontent.com/18745859/46256821-0d361c80-c4a8-11e8-95e5-4f59fac0d5a4.JPG)

But what to do next before I can use ```proto``` to use. 

I was expecting to see a ```proto.exe``` or similar executable file which I could put in my ```PATH``` variable. There is no detailed instructions for windows but just a link to the download section.

**Comment by acozzette** [comment]
@emailtovamos It looks like you must have downloaded a source zip file, but if you are looking for a compiled protoc.exe executable then the right thing to download is [protoc-3.6.1-win32.zip](https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-win32.zip).

**Comment by emailtovamos** [comment]
Thanks @acozzette . I have couple of questions: 
 - Is this fine for 64 bit Windows 10? 
 - If the compiled ```proto.exe``` is in another zip then why the source zip is there to be downloaded? I mean what can I do to compile this source folder so that I get ```proto.exe```? I eventual aim is to use ```protoc``` to generate the ```.pb``` files from ```proto``` files. 
Sorry for such basic questions since I am beginner in this.

**Comment by acozzette** [comment]
@emailtovamos I haven't used Windows in a while but I believe it should work fine on 64-bit Windows 10--let me know if you have any problems. The source packages are there in case you want to build from source instead of using the precompiled binaries. Also note that `protoc` will generate code for your `.proto` file but in practice you will also need the runtime library for whichever language you want to use. For that you will probably also want to download the language-specific zip file, or get it from the package manager for your language.

**Comment by ianferreira** [comment]
https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0

**Comment by DennisL68** [comment]
`choco install protoc`
