### ISSUE TITLE
Python float are always double precision. Round-trip results in precision loss.

### ISSUE THREAD

**Issue by SebastienGaspar** [protocolbuffers/protobuf#5274]
**What version of protobuf and what language are you using?**
Version: master/v3.6.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
Python 3.6.5

**What did you do?**
1. Generate
`message Msg {
    float value = 1;
}`
2. Run the float_precision_issue.py python from the attached .zip
[float_precision_issue.zip](https://github.com/protocolbuffers/protobuf/files/2496490/float_precision_issue.zip)

**What did you expect to see**
1237.95 != 1237.95
**What did you see instead?**
1237.949951171875 != 1237.95

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by anandolee** [comment]
Are you using cpp extension? Pure python and cpp extension has a behavior difference of the precision: Python does not have C-style float , it only has a C-style double. Thus pure python is using double precision for both float and double field, cpp extension is using float precision for float field.

**Comment by SebastienGaspar** [comment]
No, we use pure python, as in the provided sample. We add to change our .proto files to use `double` rather than `float` to work around this precision issue.

**Comment by anandolee** [comment]
That is wired, can you double check the api by adding those lines in float_precesion_issue/py:
`
from google.protobuf.internal import api_implementation
print(api_implementation.Type())
`

Note:
Doing equality comparisons on floating point values is fragile. We are changing all google internal tests to use assertAlmostEqual() instead of assertEqual if they use float field but want to do equality comparisons. 
I don't mean pure python should have this behavior, just let you know what we are doing on the float precision problem

**Comment by SebastienGaspar** [comment]
It returned `cpp`

**Comment by anandolee** [comment]
Will close this issue as the behavior is expected in cpp implementation
