### ISSUE TITLE
support embedding message

### ISSUE THREAD

**Issue by unlikezy** [protocolbuffers/protobuf#5372]
My request might be similar to https://github.com/golang/protobuf/issues/192
Given the proto definition:
```
synatx = "proto3";
package test;
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
message Req2 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req2_fff1 = 10;
     string req2_fff2 = 11;
}
// more reqs definition....
```
As you can see, every Req definition needs some common fileds(1~3).
I have to repeate them(might be a lot) in every message.
You might suggest to seperate these fields into a new message, like this:
```
message CommonFields {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
}
message Req1 {
     CommonFields common_fields = 1;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
message Req2 {
     CommonFields common_fields = 1;
     string req2_fff1 = 10;
     string req2_fff2 = 11;
}
````

But we are using grpcgateway, and the json proto is required by our company MUST be the former way:
(there might be a lot other reasons for people need proto be in this way)
```
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```

The problem will be well solved if protobuf provide a syntax suger like this:
```
message Req1 {
      CommonFields;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```

what protoc should do is to treat this definition as below:
```
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```
This solution seems quite straightforward.

**Comment by acozzette** [comment]
Unfortunately I don't think we can make this kind of change. This would require new functionality in every language we support and would be quite complicated to implement, and I think the benefit from it just doesn't justify the amount of work that would be involved.

If every message is required to have these three fields at the top, another solution would be to just write a test verifying that each message complies with that requirement. That test would be easy to write, because it's straightforward to either use reflection or just directly examine the descriptors generated by `protoc` and validate the message structure. Another solution would be to just do a small amount of pre-processing to the `.proto` file before passing it to `protoc`. For example, you could have a simple `sed` script that inserts those fields where they're needed.

**Comment by unlikezy** [comment]
@acozzette , thanks for your kindly reply.
But I didn't see why "This would require new functionality in every language we support". Because my suggest is to provide a way to expand message fileds into another message. That would be on "proto definition" level, not implement level. After expanded, protoc could treat this as a normal proto file.

**Comment by yu31** [comment]
@acozzette  Excuse me;  Is any updates for this ?

**Comment by timo-klarshift** [comment]
Why has this been closed without any comment?
