### ISSUE TITLE
Can not define two same enum name in the same proto file

### ISSUE THREAD

**Issue by go4awalk** [protocolbuffers/protobuf#5425]
Version: grpc-protobuf 1.14.0
Language: Java
OS: Windows 7

Define the following two enum in the same proto file, both TestEnum1 and TestEnum2 have a enum constant named UNKNOWN.
```
enum TestEnum1 {
    IDLE = 0;
    RUNNING = 1;
    UNKNOWN = -1;
}

enum TestEnum2 {
    MAN = 0;
    ANIMAL = 1;
    UNKNOWN = -1;
}
```

**What did you expect to see**
The proto will be compiled successfully.

**What did you see instead?**
I got the following compile error:
"UNKNOWN" is already defined in "xxx".

And it's interesting that we can't define two same enum constant in the same proto file, but protobuf will add a UNRECOGNIZED enum constant to every enum in the Java class generated after compiling.

**Comment by acozzette** [comment]
This behavior is actually expected. The enum values go into the scope enclosing the whole enum definition, so in cases like your example, values in different enums can still conflict with each other. Probably the best way around it is just to put a prefix in front of `UNKNOWN`, like `TEST_ENUM1_UNKNOWN` for example.

**Comment by go4awalk** [comment]
@acozzette 
Although this behavior is expected, it's really not friendly to developer. Values in different enums don't  conflict with each other in many programming languages, such as Java and C.

**Comment by TeBoring** [comment]
The general protoc syntax has to taken all supported languages into account.

**Comment by go4awalk** [comment]
@TeBoring 
So you mean we can't define two same enum names in the same file in some other languages, could you please give an example?

**Comment by ncioj10** [comment]
Isn't it possible to use scoped enums for c++ and implement an option to specify which enums to be used. We mainly use Java and it's seriously utterly stupid that this requires these kinds of hacks.

**Comment by j-vizcaino** [comment]
Same applies in Go where the enum value gets prefixed with the enum name automatically by the code generator.
Manually adding the enum name again as a prefix in the enum value results in stuttering and is very unpleasant to read and use 😢

**Comment by prakhar-ap** [comment]
Hi folks,
I was finding the best way to write enum but didn't found any solution what i am looking for.

I need to check that if this enum valid?
```
enum Scope {
  ...
 _ADMIN = 31;
}
```

**Comment by emeraldhieu** [comment]
The design looks odd. Prefixing with the enum name brings me back to the old age of programming.

**Comment by sanan-fataliyev** [comment]
It is common use case to define UNSPECIFIED/UNKNOWN=0 in enums to avoid undesired defaults, and require explicit values.
Providing syntax to define multiple enum types without isolated scope for their values looks like an incomplete design.

**Comment by anthonyalayo** [comment]
Is there any plans to fix this? Is there any clean workaround for this in 2024? It really doesn't make any sense.

**Comment by hayyaun** [comment]
+1

**Comment by jotalanusse** [comment]
JavaScript projects that use `@grpc/proto-loader` rely on being able to convert enum values into strings and use them as such. The fact that the current solution requires prefixing every enum value with the name of the enum is ridiculous.

Please fix the current design!

**Comment by domeniconappo** [comment]
For the series: things you won't find in the README.md.

**Comment by ZheruiL** [comment]
at least remove the prefix if the prefix has the same name as the enum name please, for example: 

```proto
enum PhoneType {
  PHONE_TYPE_UNSPECIFIED = 0;
  PHONE_TYPE_MOBILE = 1;
  PHONE_TYPE_HOME = 2;
  PHONE_TYPE_WORK = 3;
}
```

```go
type PhoneType int32

const (
	PhoneType_PHONE_TYPE_UNSPECIFIED PhoneType = 0
	PhoneType_PHONE_TYPE_MOBILE      PhoneType = 1
	PhoneType_PHONE_TYPE_HOME        PhoneType = 2
	PhoneType_PHONE_TYPE_WORK        PhoneType = 3
)
```
it repeats PhoneType twice.

can't it be just `PhoneType_MOBILE` as a result ?

**Comment by fastfend** [comment]
It looks like after this issue was closed it went directly into "do not elaborate further" trash bin

**Comment by esrauchg** [comment]
For anyone still reading closed bugs long after they were closed, the context is that the enums values semantics are a concept that necessarily has semantics outside of any one language (in reflection, global references, etc), and the decision was made in the beforetimes for values to be unscoped (matching beforetimes C++), lots of ancillary tooling was built with that assumption, so it is too problematic to allow collisions between enum values defined in sibling enums even when ~all languages could do something sane with it.

In the short term, newer language development has had the behavior of automatically stripping the prefixes in the generated code names; for example Rust, C# and Swift have that behavior.  Go has added an option in Edition 2024 where you can opt into the behavior (see https://go-review.googlesource.com/c/protobuf/+/618979), Edition 2024 will be available for use in OSS later this year. Note that the JSON representation cannot realistically be stripped of the prefix because updating all ProtoJSON parsers is not feasible (there's many dozens that aren't controlled by Google at all which are all interoperating today).

We still intend to add an option to .proto itself that makes enum values be considered semantically scoped to their containing enum (as a semantic orthogonal to any individual languages that it used in). This is sufficiently difficult to retrofit in with all existing tooling that it unfortunately we weren't able to do it in Edition 2024. We still hope that we can add this behavior _and_ make it the default in the next Edition after that one, putting this long-standing issue to rest once and for all once people uptake a new enough release.

We understand that is a slow timeline and as users of protobuf we feel the pain just as much as everyone, but its just the technical realities of a project like Protobuf that we can only move as fast as the ecosystem tooling can move; it would only be harmful for Protobuf to have a swiss army knife of features that don't actually work in practice.

**Comment by sanan-go** [comment]
@esrauchg thank you for providing an update!  Glad to know that there is ongoing work on it, and we will eventually get this option.
Currently the issue is closed as "completed". I think it should be kept open until there is at least a reasonable workaround.
