### ISSUE TITLE
C++ Bytes field representation as std::vector instead of std::string

### ISSUE THREAD

**Issue by rainerschoe** [protocolbuffers/protobuf#5431]
**What language does this apply to?**
C++ (maybe others)
Affects generated code and general APIs (reflection etc.).

**Describe the problem you are trying to solve.**
When working with raw data buffers in C/C++, operating system interfaces or other low level interfaces typically represent those buffers as `void*`, `uint8_t*` or `char*`.
In protocol buffers generated C++ code, `Bytes` fields are represented `as std::string`. This leads to type conversion difficulties:

Unfortunately, std::string does not provide mutable access to its data in `char*` representation. Only non-mutable access is allowed via `const char* data() const noexcept;` ([link](http://www.cplusplus.com/reference/string/string/data/))

This implies, that all low-level code, which creates or modifies buffer contents has to be wrapped using memory copies, for example like this:
```
char * buffer = malloc(size);
lowLevelBufferModifyingFuncationCall(buffer, size);
std::string myString(buffer, size);   // copy happens here
delete buffer;
```

**Describe the solution you'd like**
In contrast to std::string, std::vector provides read and write access to the underlying datastructure, as it guarantees, that stored data is consecutively in memory (`&v[0]+n == &v[n]`:
```
      value_type* data() noexcept;
const value_type* data() const noexcept;
```
see [link](http://www.cplusplus.com/reference/vector/vector/data/)

If protocol buffer would expose an interface to access Bytes fields as std::vectors, the above example could be implemented without the seemingly unnecessary copy operation:
```
// initialize the vector to the required size:
// zero initialization is assumed to be faster than copy (see comment below)
std::vector<char> buffer(size); // might also use buffer.resize()
lowLevelBufferModifyingFuncationCall(buffer.data(), size);
// now buffer could directly be used with protocol buffers, no copy necessary
```
Unfortunately `std::vector` does not provide a way to change its size without initializing its contents.
However zero initialization should be faster than a copy, which would still give better performance than the workaround with a temporary buffer.

**Describe alternatives you've considered**
The only alternative I currently see is the one described on the problem section. Or derivations of this.

**Additional context**
As far as I know, the main difference of `std::string` vs. `std::vector` is, that `std::vector` guarantees that the data will be allocated as a continuous block of memory. I would be interested in the reasons as to why protocol buffer designers chose `std::string` over `std::vector`.

**Comment by acozzette** [comment]
Actually I did a little more research just now and found that C++17 adds in a non-const `data()` method for `std::string`, like the one that was added for `std::vector`. So at least starting from C++17 the problem goes away entirely. Still I think the `&s[0]` trick is not really so bad, since it relies only on behavior documented by the standard starting from C++11.

**Comment by rainer-ibm** [comment]
I agree with you. It seems like C++ `std::string` + `std::vector` were primarily designed to be usable within the std:: ecosystem.
Type-safe interoperability with low-level data-structures only recently seems to get attention. We were just unlucky, that std::vector got this attention first :smile:

I am just beginning to wonder, what the difference between `std::string` and `std::vector` actually is... Maybe in the future we might get a O(1) conversion between std::string and `std::vector` :yum: 

-> closing, as problem seems to be caused by limitations in legacy C++ APIs and does not exist in more recent C++ versions.

**Comment by cculianu** [comment]
May I just chime in with this:  This looks to me like the google engineers that first designed this didn't really care about type safety or using the proper types for this.  It smacks to me of C programmers doing C++.  

```
typedef char Byte;
typedef std::vector<Byte> Bytes;
```

Would have been far less nasty.

**Comment by HamzaHajeir** [comment]
Telling people `std::string` is the way-to-go for binary data because it just "works" contradicts why we're using a programming "language" in essence!

Any C++ developer, by reading a code would expect `std::string` to hold null-terminated character sequence, being otherwise makes a lot of confusion!

We write "codes" which we read way more often than we write them, how about spreading them worldwide!

For more reasons, see answers here: https://stackoverflow.com/questions/9626914/stdstring-or-stdvectorchar-to-hold-raw-data

**Comment by rainerschoe** [comment]
Re-opening due to public interest (see comments above).

I recently stumbled on this issue again when inter-operating with other libraries, which expect `std::vector<uint8_t>` as input for work on data buffers.
Modern C++ APIs rarely use raw pointers in favor of containers with `move` or references to containers.
I could still not find a way to cleanly convert `std::string` to `std::vector<uint8_t>` without nasty copy.

**Comment by cculianu** [comment]
While I support the idea that `std::string` is the wrong type to use here, I do want to chime in that likely the reason the original designers of the codebase went with `std::string` may be due to the one small advantage it has: the [short-string optimization](https://stackoverflow.com/questions/10315041/meaning-of-acronym-sso-in-the-context-of-stdstring), which can mean no allocations for short strings (<16 or <20 bytes, depending on implementation).

That being said, using `std::string` in this way is not new to Google codebases -- leveldb also does it.  I think it's a design error because it leads to a certain lack of type safety, but it might not be worth breaking compatibility to redo this anytime soon..

**Comment by HamzaHajeir** [comment]
I think it worths to add returning values as `std::string_view` and `std::span<std::uint8_t>` beside `std::string` and `std::vector<std::uint8_t>`, as these will point to the decoded data directly without copying, and the user will know exactly how to handle them.  

Not sure what's needed to add this feature in the library, perhaps decoding without copying the data in essence, where absent data got created on heap and deleted dynamically somehow, or even allowing those return-values dynamically only if present (conditional `if(XX.has_value()`.

**Comment by fowles** [comment]
There are a great many competing tensions going on here:

- `std::string` is not a great type for binary data (as noted).
- exposing any type as a `const &` constrains the implementation a great deal (as the implementation must then have such a type)
- `std::vector` comes with some significant complexity around how it would interact with protobuf arenas (actually `std::string` already has some of that, but we do some carefully managed encapsulation breaks to work around it)
- Any change to the signature of generated APIs must be embarked on carefully.

The entire motivation behind the new [editions](https://protobuf.dev/editions/overview/) effort is to provide primitives for doing this.

One of the first targets we will use this for is to switch `string` accessors from `const std::string&` to `absl::string_view` parameters.  We can review `bytes` fields at the same time, but there is a lot of value in terms of smooth evolution of user code bases when one can go back and forth between `std::string`.  All this to say, we are thinking about these things, but don't expect any fast motion here.

**Comment by HamzaHajeir** [comment]
I think it's better to stick with `std::string_view` for C++17 upwards compilers, as abseil might remove its support.

[As Quoted](https://github.com/abseil/abseil-cpp/issues/1122#issuecomment-1060768218):
> 2. Our goal is for Abseil types like string_view to generally disappear when the relevant standard is available. string_view is a C++17 type - by the time there is good compiler support for C++23 we may well be removing Abseil support for string_view.

I understand that protobuf is a very large project, which is loaded with years of backward-compatibility requirements, which naturally slows the pace of introducing new features. Given this, can we expect the no-copy decoding feature to be introduced soon (perhaps within two years)?

**Comment by fowles** [comment]
For the specific question `std::string_view` vs `absl::string_view`, protobuf is committed to using `absl::string_view` right now.  At the end of 2024, both abseil and protobuf will update their [minimum C++ to 2017](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md).  Until then we are definitely on `absl::string_view`.  When that happens, the type will dissolve into an alias for `std::string_view`.  After that, we will likely clean our internal spellings to `std::string_view`.  Abseil will probably remove the alias eventually as well, but that is for them to decide.

For the specific case of no-copy decoding, we added support for this via `absl::Cord` in [23.x](https://protobuf.dev/news/2023-04-11/#cord).

**Comment by coyorkdow** [comment]
I suppose we all agree that `std::string` is a bad abstraction to the bytes buffer data. But what is the most appropriate abstraction so that we can avoid data copy whenever possible?

1. All the bytes buffer can be represented as a pair of `void* data` and `size_t len`.
2. The underlying data can be discontinuous. I believe we should consider such scenario, otherwise the Linux's `iovec ` and `readv`, `writev` would be unnecessary.
3. protobuf message should take the ownership of the buffer.

If we ignore 3, then it's no doubt that a sequence of `std::string_view` or `std::span`. e.g., `std:span<std::span<char>>`. But just forget it. There is no way that we can abandon the ownership.

Let's assume we now have a pair of `void* data` and `size_t len`. We've know how it be allocated and how to release it. Does STL give us a facility to take the ownership of these data without copying memory? I believe the answer is NO.

But we still have a room for refine. We can let each of the protobuf's bytes type hold an instance of `std::pmr::memory_resource`, and replace `std::string` with `std::pmr::string`. Therefore, at least we can construct our buffer on the stack or somewhere where we can customize the behaviour allocation and deallocation.

---
FYI. I use brpc (https://github.com/apache/brpc) in my corporate project. brpc has a type called `IOBuf` to represent the bytes buffer. If we use brpc to receive the http request, then the http body will be wrapped into an `IOBuf` object. This type enables user to append the user data into the buffer, but without data copy. That is, the buffer can be discontinuous. And we will also pass a deleter object when appending the data, so that when the `IOBuf` destructing, it can release all the data we've appended into it.

Here are some reference of `IOBuf`, hope these stuff can help the evolving of protobuf.

https://brpc.incubator.apache.org/docs/c++-base/iobuf/

https://github.com/apache/brpc/pull/2431 (A PR submitted by myself, change the deleter type from `void(*)(void*)` to `std::function<void(void*)>`.)

https://github.com/apache/brpc/blob/master/src/butil/iobuf.cpp#L1220 (The source codes of `IOBuf`.)
