### ISSUE TITLE
proto4: Add support for nullability / optionality in Java

### ISSUE THREAD

**Issue by kevinhwang** [protocolbuffers/protobuf#5450]
I think we can all appreciate the importance of having first-class support for nullability / optionality in our programming languages. I think we all recognize there's frequent, legitimate need when programming to distinguish between the default, zero or "zero-like" value of a type, and the complete absence of a value. This is so much the case that many functional programming languages prominently feature some sort of [option type](https://en.wikipedia.org/wiki/Option_type).

Following that, it should be important that the protocol buffers language and accompanying programming language bindings give first-class support for this.

Due to the design of proto3, this isn't currently feasible: e.g., the serialization format cannot distinguish between a default value and an absence of value, Java codegen cannot use Java `Optional`s without requiring everyone to use Java 8, etc. (see #2553).

So right now, we muck around with [wrapper types](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto) for primitive types, and boxing/unboxing them in our code; checking `com.google.protobuf.MessageOrBuilder#hasFoobar` before calling `com.google.protobuf.MessageOrBuilder#getFoobar`for message types, and checking if a value is `null` (if using a `@Nullable` type) or if `Optional#isPresent` (if using an `Optional` type) before setting anything in a builder; etc. It's a giant mess, and it's no fun.

I would propose that in proto4, we add first-class support for nullable / optional types, both in the serialization format, and the codegen. We can do this in a type safe way that avoids [the pitfalls of `null`](https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained), using modern language support for optional types.

Here's an example of how this could be done in proto4:

- Add back the `optional` keyword to the Protocol Buffers Version 4 Language Specification. This keyword would denote a nullable type. This would require the serialization format to distinguish between a default value and absence of value once again. The default value then of an `optional` field would be none / the empty optional / whatever you want to call it.
- If a field is marked `optional`, then codegen outputs classes whose getters return `java.util.Optional` types, and whose builders' setters accept `java.util.Optional` types. This requires that proto4 require Java 8 and above.

At no point in Java is `null` ever used. Unset `optional` fields do not return `null` when you call its getters, and setters will still throw NPE if you try to pass them `null`. This approach is null safe, while retaining the usability of optionality which so many modern languages already support.

**Comment by efenglu** [comment]
I would even be happy not throwing an NPE on set and returning NULL on get if its not set.

**Comment by daveyostcom** [comment]
Rather than the `optional` keyword, I look forward to optionality being indicated with the standard `?` after the type.

**Comment by danieleades** [comment]
So if you dont use the `optional` keyword you get the default value transparently?

That leaves you with a small problem. If you *require* a field to be set, you mark it optional, so you can determine whether it was set, and then return an error if it wasn't.

Then you have to live with the irony of having marked a field as 'optional' because it's not.

Suspect you would need a `required` keyword as a *dual* to the optional keyword, otherwise you run into the same kind of semantic nonsense you're trying to avoid

**Comment by puellanivis** [comment]
There is no reason for us to increment any version information and limit this only to a whole new jump in version. The keyword `optional` was already not a valid type, and thus adding it in is unambiguous, which is why a proposal was advanced to add it back into proto3, but keep the default behavior the same: https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/implementing_proto3_presence.md 

There is absolutely no reason to add in `required` again, because it was already fundamentally problematic on many levels. If people want to enforce ensuring a value is set by marking it `optional` and then testing for its presence, then :woman_shrugging: that seems like a whole lot of effort to go through rather than just validating that the value makes sense in the first place.

For instance, a required string field can just as easily be tested for the zero value (which will almost certainly already be an invalid value), as it can for presence. I’ve stumped a whole lot of developers covering validation magic, by pointing out tha `int port [required]` does not guarantee that the value is valid at all. “But a zero value would fail to open up the port.” But, actually, it doesn’t.

There are many good reasons why protobuf should steer clear of any validation of data inputs, even including making a field mandatory or required. Validation of values is a business logic decision, and one that cannot by solved by a data storage/interchange format.

**Comment by danieleades** [comment]
I guess the part that i find weird is that the `optional` keyword has been added in, even though *every* field is optional.

so `optional` doesn't actually mean "you don't have to set this" (which is what you might expect if you weren't familiar with proto3), instead it actually means "I'll be able to tell the difference between you setting it to the default value, and not setting it at all". I've not seen the word `optional` used to describe exactly these semantics in *any other context*.

Can we agree that's just a *little* odd?

As far as I can tell, there are two applications for this:

1. **distinguishing between a default value and an unset value**. There are loads of interfaces for which there's an important semantic difference between a default value and an unset value, or where the default value for a primitive type is valid, but almost certainly undesirable (and we want to be *defensive* about being given this value by accident). It's clear that `0` is *qualitatively* different to `None` (for example. substitute your favourite language) and `optional` allows us to capture that in the general case when we can't or won't use the well-known wrapper types. Fine.
2. **the `optional` keyword can be abused as a way to enforce that a field is set**, as I described above.

It seems clear to me that the first application is the intended one, even if the way 'optional' is being used here is very gently 'off'.

The second application is Bad, and is a great way to generate interfaces which are not backwards compatible (at the application layer). But since it exists, people will use it. Now not only is it a misuse of the functionality, you'll have people using the word `optional` on a  field *specifically because* it is **not** optional.

Now this just the worst kind of issue comment, because i'm not going to offer a solution. I just don't see how you could alter this in a backwards compatible way.

Cap'n'proto has a nice solution- it serialises the same way on the wire, but you can specify your own default values for fields. That means you can choose values that make sense for your application, or set the default value to something absurd so that you can more easily infer that it wasn't set. If you could do *that* then `oneof` wrappers would be sufficiently rare you probably wouldn't mind using them explicitly

**Comment by puellanivis** [comment]
:thinking: OK, yeah. I get the point about the name of the keyword.

I think the interest in using the term was because it would restore the `optional` semantics that existed in proto2.

**Comment by daveyostcom** [comment]
Several existing strongly-typed modern languages
1. provide for an optional field that must be checked at runtime before use (typical syntax: a ? after the type)
2. provide for a required field that must be provided at compile time or provably at object creation time (no ? after the type)
3. require that a field be either optional or required (perhaps with a default value, e.g., 0 or "")
Seems to me that a future proto-n language should satisfy all 3 points. A clean syntax such as ? would be nice. We have to be looking forward, not back, so I would be in favor of an incompatible syntax change.

**Comment by puellanivis** [comment]
Just because several “modern languages” support these features, does not mean that protobuf should cater exclusively to them.

There are plenty of languages which are significant users of protobuf, where such features do not exist, and/or make supporting said feature unbearably inefficient.

Very specifically, any sort of builtin requirement that a value _must_ be set or exist before marshalling or after marshalling is going to run head-first into one of the very reasons why there is a `proto3` in the first place: the `requirement` keyword was made with good intentions, but created far more issues than it ever solved.

The proto3 optional keyword satisfies your point 1, and proto3 semantics already satisfy your point 3.

**Comment by clehene** [comment]
Since [Field Presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md) support was added to proto3, would this issue be the right place to track Java support for this feature or is there another issue?

**Comment by JustinEdwardKennedy** [comment]
Related: https://github.com/protocolbuffers/protobuf/issues/8012

**Comment by elharo** [comment]
proto4 is not under development, and it's unlikely this feature will be considered

**Comment by mcpiroman** [comment]
Isssue #8676 is about essentially the same thing and although it is for kotlin, as I commented there, it could be implemented for java too.
