### ISSUE TITLE
[PHP] got error is not found in descriptor pool.

### ISSUE THREAD

**Issue by mobintmu** [protocolbuffers/protobuf#5506]
i am new in protobuf.
i 'm using php and laravel framework and want connect to server via protobuf.
i 'm making .proto file and compile it with Protoc version 3.6.1 whit command below
protoc --proto_path=src --php_out=build/gen src/AnalysisBatchRequest.proto

and add 
composer require "google/protobuf"
to my project.

but when i 'm running code i got this errror:
AnalysisBatchRequest is not found in descriptor pool.
on line 96 of ./vendor/google/protobuf/php/src/Google/Protobuf/Internal/Message.php

how could i fix this problem?
thanks all

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/php/composer.json#L20-L23
You should autoload your generated dir, which is build/gen.
```
"autoload-dev": {
    "psr-4": {
      "": "build/gen"
    }
  },
```

**Comment by Xenology** [comment]
For anyone that is stumbling across this issue from google searches. You will want to make sure that the autogenerated Protobuf classes are in the root of your application and not under another namespace or folder. Autoloading your classes in the root namespace is required because of the way the classes are generated and loaded into the Protobuf internal classes. 

If your composer file or autoloader specifies a namespace default for a `src` folder, you will need to place the generated files in a folder outside the src directory and load them into the root namespace like such. 


```
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "": "protobuf/"
        }
    },
```

This should resolve the error of classes not being found in the descriptor pool, as classes are loaded into the descriptor pools based on their entire namespace and not their class name. Having additional folders or namespace prefixes in the class signature will result in the Protobuf internal methods looking for the class name in the internal descriptors, but being unable to find it because its indexes as the fully qualified namespace. This results in the `not found in descriptor pool` error.
