### ISSUE TITLE
Strange serialization with LITE_RUNTIME

### ISSUE THREAD

**Issue by oxoocoffee** [protocolbuffers/protobuf#5665]
Version: libprotoc 3.6.1
Language: C++
Linux Mint Cinnamon 19.1 (Linux mint-box 4.15.0-45-generic #48-Ubuntu SMP )
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

I have strange serialization issue on same data. Here is sample of my proto file

syntax = "proto3";
option optimize_for = LITE_RUNTIME;

message testMessage
{
    int32  val1    = 1;
    float  val2     = 2;
    uint32 val3   = 3;
}

Now after generation *.pb.h|c from proto file on both sides server and client project from same proto file,
in client project I have method 

bool Socket::sendData(int v1, float v2, unisigned int v3) {

     testMessage message;  

     message.set_val1(v1);
     message.set_val2(v2);
     message.set_val3(v3);

     long byteSize  = message.ByteSizeLong();

     char buffer = new char[byteSize];

     if( message.SerializeToArray(_buffer, byteSize) == false )
             return false;

     // Send message on TCP socket. I am skipping message 
     // header that is also added above, but not in this sample

    delete [] buffer;
    return true;
}

Now the problem is that if I call sendData() two time with same parameters

sendData(0, 0.0, 0);
sendData(0, 0.0, 0);

In first case message.ByteSizeLong() returns 2 which is ok
On second call message.ByteSizeLong() return 0 which is wrong.

Since testMessage is created on stack and same data is passes in to sendData() sizes should be the same. But they are not for me.

Is this a bug? Am I missing something? sendData() is called from same thread (I did checked)

Any one can chime in? Let me know if I need to provide any additional informations or clarifications.

**Comment by acozzette** [comment]
That is strange. I would actually expect 0 to be the correct value of `ByteSizeLong()` because with proto3 there is no distinction between a field being empty and being set to its default value (which is 0 for numeric types). I can't think of any reason why it would sometimes return 2 then. If you can come up with a full reproducible test case then I could try to debug it.

**Comment by acozzette** [comment]
If I'm not mistaken the size with proto2 should actually be 9. That is because each field needs a one-byte tag (which is a field number and wire type), and then the values themselves need one byte for each integer type and four bytes for the float. `int32` and `uint32` are variable-length but `float` is always four bytes.

Serializing from a buffer of 0 bytes should work so I am surprised that it's failing. The only way that should fail is if there are missing required fields, which isn't the case here.

**Comment by oxoocoffee** [comment]
Ok I found the problem on my end :) The reason I had size 2 was threading/mutual exclusion in other part of the code. Not that is fixed it looks good. So no bug. Closing it.
