### ISSUE TITLE
protoc generates json_name "" if json_name field option is set to ""

### ISSUE THREAD

**Issue by cybrcodr** [protocolbuffers/protobuf#5682]
Using protoc v3.6.1.

Compile following with -o
```
syntax = "proto3";
message M {
  string f1 = 1 [json_name = ""];
}
```
produces ...

```
file: <
  name: "bug.proto"
  message_type: <
    name: "M"
    field: <
      name: "f1"
      number: 1
      label: LABEL_OPTIONAL
      type: TYPE_STRING
      json_name: ""
    >
  >
  syntax: "proto3"
>
```

Generators using json_name to output JSON will produce "" as key name.  I think that protoc should produce the lowerCamelCase version instead similar to not having json_name field option set.

**Comment by TeBoring** [comment]
Could you just mention the name you want instead?

**Comment by cybrcodr** [comment]
I should have noted as well that C++ MessageToJsonString will produce example JSON string `{"": "value"}` on that message, and I think it's because `json_name` is empty string.  I don't think it's correct to produce an empty string key for that field as the parser will not be able to parse it back in.

So, is it a bug on the C++ API or protoc?

**Comment by esrauchg** [comment]
Slightly necromancy but this was tagged in the other issue, so in case this is referenced again going forward, I would say `[json_name=""]` is perfectly legal and can be used intentionally and sensibly when you want to use a Protobuf library to parse JSON of the shape `{"": 1}`

Its an usual name, but IMO no more weird than `" "` or `"☃️"` or a number of other things. Empty string is just a perfectly valid key in JSON, fully-co-equal with any other string you might have which has length>0, it would actually be weirder to silently ignore it than it is to honor it.

The ability to distinguish empty-string from unset is almost always sensible which is why proto3 implicit presence is regretted in current view, conveniently descriptors never moved to proto3 which made it so `[json_name=""]` and not setting a json_name at all are 2 distinct states that have different handling: anything which observes json_name definitely should always check has_json_name() first.
