### ISSUE TITLE
Static variables in the autogenerated C++ headers prevent delay loading of dll

### ISSUE THREAD

**Issue by stolstov** [protocolbuffers/protobuf#5684]
**What language does this apply to?**
C++
Auto-generated code for C++

**Describe the problem you are trying to solve.**
We build protobuf auto generated code into a dll. We would like to use delay-loading with this dll (DELAYLOAD linker option in Visual Studio).
The auto generated header files contain exported static variables that produce the following link error:
fatal error LNK1194: cannot delay-load 'mydll.dll' due to import of data symbol '"__declspec(dllimport) class xxxx::XXXXXDefaultTypeInternal xxxx::_XXXX_default_instance_"

**Describe the solution you'd like**
Allow delay loading of the dll that exports protobuf autogenerated structures. A solution would be to avoid declaring exported static variables in the auto generated header files.

**Describe alternatives you've considered**
We don't use delay load option right now.

**Comment by deulgaonkaranup** [comment]
@stolstov i think we solved it with a workaround.

reference email:

From: Sergey Tolstov 
Sent: Monday, November 19, 2018 9:39 AM
To: Anup Deulgaonkar <ADeulgaonkar@esri.com>
Cc: Roop Goyal <rgoyal@esri.com>; Abhishek Kabra <AKabra@esri.com>
Subject: delay loading of pbf dlls

Anup,

I have confirmed that it is impossible to delay load the pbf dll. This is due to the fact that delay loading is impossible when one has to use a global variable exported by the dll.
For example, you are calling inline method queryresult(), if you look inside if the method you’ll see it returns a pointer to one of exported variables in the if statement. There are other methods there that use other exported variables.

The delay loading works when one references only functions exported by a delay loaded dll. So a workaround for this – disable inline function expansion for the PBFFeatureCollectionDeserializer.cpp.

A branch with the changes to consider:
https://devtopia.esri.com/ArcGISPro/ArcGISPro/compare/serg4066/delay_load_pbf

I recommend this change as delay loading maybe more beneficial than small gain in performance in PBFFeatureCollectionDeserializer due to inlining.

Thanks,
Sergey

**Comment by acozzette** [comment]
@stolstov I'm not sure if it's feasible for us to get rid of those static variables but do you have any ideas on how to do it?

**Comment by stolstov** [comment]
@acozzette 
In the header file you have this:

namespace xxx
{
	__declspec(dllexport) XXXXXDefaultTypeInternal _XXXX_default_instance_
}

Is it possible to replace these export variables with export functions that return the reference?
namespace xxx
{
	__declspec(dllexport) XXXXXDefaultTypeInternal& get_XXXX_default_instance_();
}

In the cpp

XXXXXDefaultTypeInternal& get_XXXX_default_instance_()
{
  return _XXXX_default_instance_
}

Use get_XXXX_default_instance_() functions instead of global variables _XXXX_default_instance_ in the auto generated code?

**Comment by acozzette** [comment]
The one potential issue is that if those functions are not inlined then there may be a performance cost.
