### ISSUE TITLE
A wrong header files path in C++

### ISSUE THREAD

**Issue by Tancen** [protocolbuffers/protobuf#5764]
**What version of protobuf and what language are you using?**
Version: masterv3.5.0 etc.
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 7  7601

**What did you do?**
I have two proto files that './a.proto' and '../b.proto'. The file 'b.proto' import file 'a.proto'.
I executed command 'cd b'  before executed command 'protoc --proto_path=./ --proto_path=../ --cpp_out=./  b.proto'. in the Terminal.

**What did you expect to see**
'#include "../a.pb.h"' in the file 'b.pb.h' 

**What did you see instead?**
'#include "a.pb.h"' in the file 'b.pb.h'

**Comment by acozzette** [comment]
This is just the way protoc works--it will consider the `--proto_path` flags to determine where to look for `.proto` files, but that will not change the `#include`s that it generates. You can still get your code to compile by passing the right `-I` flags to the compiler so that it knows where to search for headers. But probably the best option is to restructure your files so that all your `.proto` files are within a common subdirectory, because otherwise this kind of thing gets confusing quickly.

**Comment by Tancen** [comment]
> 
But probably the best option is to restructure your files so that all your `.proto` files are within a common subdirectory, because otherwise this kind of thing gets confusing quickly.
> 
I don't think it's a good way for a service that serve for more than one of other services
