### ISSUE TITLE
"PROTOBUF_MIN_PROTOC_VERSION" is not defined.

### ISSUE THREAD

**Issue by Monk-Liu** [protocolbuffers/protobuf#5814]
I am trying to install gem5 on CentOS 7. So I download the gem5 via Mercurial (2.6.2) and use the scons (3.0.1) to compile source code. That is when the error happend. Scons reports the error that "PROTOBUF_MIN_PROTOC_VERSION" is not defined in a file generated by protobuf compiler (the file is "/ARM/proto/packet.pb.h").
Does it mean I have not installed protobuf correctlly? Or maybe there are somethings wrong with the gem5 source code?
Could anyone help me? Thannks.

**Comment by acozzette** [comment]
I'm not familiar with the gem5 build but that error sounds like it is caused by a mismatch between the `protoc` version and the version of the library (i.e. `libprotobuf`). For C++ these versions need to be the same, so the `protoc` used to generate `packet.pb.h` and `packet.pb.cc` has to have the same version as the protobuf library you use.

**Comment by Monk-Liu** [comment]
Thanks for acozzette. I'll try to reinstall protobuf in a proper way. Hope anyone have the same problem could know your answer.
