### ISSUE TITLE
[Protobuf 2.6.1] Objective-C: use NSArray instead of PBArray in generated files

### ISSUE THREAD

**Issue by richardtop** [protocolbuffers/protobuf#5818]
Is it possible to specify `protoc` compiler to use `NSArray` instead of `PBArray` in generated files?

I already have a large codebase expecting `NSArray` and having a `PBArray`(which is not compatible with `NSArray` in method signature) is a huge inconvenience.

Having compiler generate compatible model files will solve the issue for me. Is there any way to achieve it?

**Comment by thomasvl** [comment]
Nope, using `NSArray` for a integers, etc. would require boxing of them and that can use a lot more memory.

Also we try to avoid options like this because you can get into trouble if two things depend on a common proto file and they have tried to use different decisions around what to set an option to (as only one ObjC class can exist with a given name in the runtime at a time).

**Comment by richardtop** [comment]
Clear, I understand the issue with ambiguity of output originating from a single `proto` file but different compiler settings.
