### ISSUE TITLE
Crash with the v3.6.1 version macOS 10.14.3

### ISSUE THREAD

**Issue by Cyberbeni** [protocolbuffers/protobuf#5877]
**What version of protobuf and what language are you using?**
Version: v3.6.1
Language: Objective-C

**What operating system (Linux, Windows, ...) and version?**
macOS 10.14.3 (18D109)
**What runtime / compiler are you using (e.g., python version or gcc version)**
Xcode 10.1
**What did you do?**
The crash only happened 1 time in the released app.

Relevant part of the crash log:

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [8404]

Application Specific Information:
objc_msgSend() selector name: mergeFromCodedInputStream:extensionRegistry:

Thread 1 Crashed:: Dispatch queue: com.myapp.userinitiated.695
0   libobjc.A.dylib               	0x00007fff7d88da2e objc_msgSend + 46
1   MyApp  	0x00000001015aa5e4 0x10158b000 + 128484 -[GPBCodedInputStream readMessage:extensionRegistry:] (in MyApp) (GPBCodedInputStream.m:455)
2   MyApp  	0x00000001015e1d9a 0x10158b000 + 355738 -[GPBMessage mergeFromCodedInputStream:extensionRegistry:] (in MyApp) (GPBMessage.m:2158)
3   MyApp  	0x00000001015e103c 0x10158b000 + 352316 -[GPBMessage mergeFromData:extensionRegistry:] (in MyApp) (GPBMessage.m:1921)
4   MyApp  	0x00000001015de0d4 0x10158b000 + 340180 -[GPBMessage initWithData:extensionRegistry:error:] (in MyApp) (GPBMessage.m:869)

**Comment by thomasvl** [comment]
Without more info, I don't think there is anything we can do to help.

From the limited stack you have provided, it looks like a message was being created from some data, while parsing the data, it was attempt create a submessage for a field, and in creating that the objc class that was needed didn't respond to one of the methods the library provides internally.

So my guesses would be:
- Since you have only seen this happen once, maybe some threading/memory corruption that happened to correct the memory for these objects.  i.e. - other crashes could be the same sorta memory issue, but in this case, it happened to the the protobuf library that failed.
- Some other library is loaded into memory containing a ObjC class with the same name as this message class.  The ObjC runtime only allows one class with a given name to be loaded at runtime, if something attempts to load two classes, the behavior for which one "wins" is undefined.  So if your message class has a common name, there is a chance something like this can happen.  The file level option to add a prefix to the generated objc types can help with this.  Given you say this only happened once, it is possible it is a collision with some private system library that is lazy loaded based on what the user does (i.e. - the System address book support loads some libraries on demand as the public apis are called, so it could be dependent on what the user does in your app before this parse happens), or if this user could have some system wide utility installed that injects into all apps.
