### ISSUE TITLE
Static initializers prevent using libraries which also use Protobuf

### ISSUE THREAD

**Issue by klapstoelpiloot** [protocolbuffers/protobuf#5914]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 18.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
GCC 7.3.0

**What did you do?**
Follow this link to see the steps to reproduce:
https://github.com/tensorflow/tensorflow/issues/24976

**What did you expect to see**
I expect using Protobuf and Tensorflow (and any other library that uses Protobuf) to work fine together. Without using cumbersome workarounds like wrapping anything in an addition shared library.

**What did you see instead?**
Segmentation fault during static initialization.
See this link for more details:
https://github.com/tensorflow/tensorflow/issues/24976

**Comment by acozzette** [comment]
If I understand correctly it sounds like TensorFlow bundles its own copy of protobuf, resulting in ODR violations when TensorFlow users try to use both TensorFlow and protobuf. Unfortunately I don't think we can really do anything on the protobuf side to fix this, and the only solution is to avoid linking against two separate copies of protobuf. The static initializers are not the problem, because ultimately ODR violations are undefined behavior no matter what how we do our initialization.
