### ISSUE TITLE
n C++, in ReadLittleEndian32FromArray() returning the byte cursor as 'const' makes the idea of a cursor unusable

### ISSUE THREAD

**Issue by GameCy** [protocolbuffers/protobuf#6019]
The following piece of code is not possible
`typedef google::protobuf::uint8* BufferPointer;

BufferPointer FrameHeader::fromBinary(const BufferPointer cursor)
{
    cursor = google::protobuf::io::CodedInputStream::ReadLittleEndian32FromArray( cursor, &ByteSize);
    cursor = google::protobuf::io::CodedInputStream::ReadLittleEndian32FromArray( cursor, &RequestId);
    cursor = google::protobuf::io::CodedInputStream::ReadLittleEndian32FromArray( cursor, &MessageType);
    return cursor;
}
`
Is the 'const' needed in 
// inline const uint8* CodedInputStream::ReadLittleEndian32FromArray( ......)
????
Why return an advancing cursor as const?

**Comment by acozzette** [comment]
I think `const BufferPointer` in your example code doesn't make sense, because that is a const pointer to non-const uint8. What you probably want is a non-const pointer to const uint8. The underlying data should be const, because we don't need to modify it, but the pointer itself should be mutable because we're incrementing it as we go along.
