### ISSUE TITLE
Duplicate Java mergeFrom methods when message contains a from field of its own type

### ISSUE THREAD

**Issue by jackloughran** [protocolbuffers/protobuf#6021]
**What version of protobuf and what language are you using?**
Version: v3.7.1
Language: Java

**What operating system (Linux, Windows, ...) and version?**
macOS Mojave 10.14

**What runtime / compiler are you using (e.g., python version or gcc version)**
python version

**What did you do?**
create a_message.proto:
```protobuf
syntax = "proto3";

option java_package = "com.test";

message AMessage {
    AMessage from = 1;
}
```
generate java code:
```bash
protoc --java_out=../java/ a_message.proto
```

**What did you expect to see**
AMessageOuterClass.java will compile successfully.

**What did you see instead?**
AMessageOuterClass.java does not compile due to two methods having the same signature:
```java
public Builder mergeFrom(com.test.AMessageOuterClass.AMessage other) {
```

**Comment by BSBandme** [comment]
Sorry but it can't use `from` as field name since the mergeSomeField method will conflict with mergeFrom method.
@haon4 Do we have any plan for preventing these words that are not java key words appears in protoc?

**Comment by haon4** [comment]
We do have existing proto messages with 'from' as field name that can compile successfully. The problem here is that 'from' is using the same type as the Message that contains is, causing a signature conflict. We have a couple of options to resolve this:

1. Do nothing - users will just have to update their field name :-/
2. Rename the generated merge method for the field name to something like mergeFrom_. But then we will have mergeFrom(com.test.AMessageOuterClass.AMessage) and mergeFrom_(com.test.AMessageOuterClass.AMessage), which would be super confusing.
3. Return an error when we generate the Java codes with custom error message telling developers to change the field name.

**Comment by haon4** [comment]
At this point I am leaning toward doing nothing. It is unpleasant, but the work around is quite simple. It is probably better to have the user rename the field than having confusing mergeFrom() and mergeFrom_(). Returning an error earlier would be an ideal long term goal, but requires significantly more investment that we won't be prioritizing yet.
