### ISSUE TITLE
json_format unable to check the presence of required fields 

### ISSUE THREAD

**Issue by Dharmateja28** [protocolbuffers/protobuf#6027]
**json_format.ParseDict**

    Am using json_format.ParseDict to parse dictionary

    But while parsing dictionary to proto message some required fields in message are missing in dict.

    Still I dont see any error message.

**json_format.MessageToJson**
    Created a proto message which contains some required fields.

    Assigned some fields in message but not all the required fields.

    Now used json_format.MessageToJson to convert my message to JSON.

    Here some of my required fields in message are not intialized but am able use
    json_format.MessageToJson whithout any error message.

    But if I try to serialize the parsed message using SerializeString it throws an error saying
    required field "required field name" is missing.

**Comment by BSBandme** [comment]
Generally, we only have proto3 json format officially, for proto2 we're still trying to figure out a specification.

**Comment by haon4** [comment]
Sorry about this, but JSON format is a Proto3 concept, and we didn't specify any behavior for proto2. While it works in happy cases, we can't promise anything about it for proto2. For proto2, we are also discouraging the usage of required fields because it is known to cause issues. If possible, we recommend that you switch to using proto3 if you want to use JSON format. At the minimum, please avoid using required fields.
