### ISSUE TITLE
Choose not to delete messages when Clearing with C++?

### ISSUE THREAD

**Issue by amarcum** [protocolbuffers/protobuf#6036]
**What language does this apply to?**
C++ code change/function addition, no proto3 syntax change.

**Describe the problem you are trying to solve.**
When calling CopyFrom at very high rates with most messages having at least 1 sub message there becomes a lot of new and delete calls from the Clear function (or a very large memory leak if using arenas, one test caused 300 GB of ram to be used in 35 mins).

**Describe the solution you'd like**
When generating the cpp code for Clear if the sub message is not nullptr and its not the default instance then call Clear on it. This could be a different function if needed

**Describe alternatives you've considered**
- I have used reflection when clearing messages then calling mergeFrom which causes too much CPU usage to iterate through each field.
- I have tried with an Arena which causes a 300 GB memory leak since the sub message pointer is just set to nullptr.

**Additional context**
The code that could be modified or duplicated if a new function would be required is here.
[cpp_message_field.cc#L355-L358](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_message_field.cc#L355-L358)

Thanks for spending the time to read through this request!

**Comment by acozzette** [comment]
CC @haberman and @gerben-s 

This seems like an interesting case where the proto3 performance is not as good as proto2. I don't think we can just call `Clear()` on the submessage like you suggest, because we need to keep track of whether the submessage exists or not. We would probably need to reintroduce the bit array indicating whether fields are present (the "hasbits"), at least for submessage fields.

About arenas, the way they work is that everything is freed all at once when the arena is destroyed. I suspect that when you tried arenas you didn't encounter a real memory leak, it's just that it will keep using more memory until you destroy it. Usually arenas work best for servers where you can create an arena just for the duration of one request.
