### ISSUE TITLE
Request: protoc should only overwrite files if contents are not identical

### ISSUE THREAD

**Issue by kjin** [protocolbuffers/protobuf#6040]
If it's straightforward enough I'd be happy to contribute a patch on this.

**What language does this apply to?**
Any language

**Describe the problem you are trying to solve.**
I'm implementing Perfetto in Node.js, and Perfetto has quite a large number of generated sources from protobufs. Because these files get overwritten on every build, incremental re-builds are slow. Note that we are using GYP in Node.js which I believe does not assume hermetic builds, so GYP will try to re-build dependents every time the protoc-generated files change.

**Describe the solution you'd like**
Something similar to V8's Torque, where [output files are only changed if they are not the same](https://github.com/v8/v8/blob/4dd01774c63e9d8a896dcddccb23b964e0c160e0/src/torque/utils.cc#L246).

**Describe alternatives you've considered**
We could wrap protoc in a script that only invokes it if sources are newer.

**Comment by juliettepretot** [comment]
+1 to this

**Comment by juliettepretot** [comment]
For future reference, an example script to achieve this in user land:

```bash
readonly PROTO_TMP_OUT_DIR="./protoc_tmp_out"
readonly PROTO_OUT_DIR="./protoc_out"

mkdir -p "${PROTO_TMP_OUT_DIR}"
mkdir -p "${PROTO_OUT_DIR}"

# Initially write the generated code to a temporary directory.
protoc \
    --js_out="import_style=commonjs,binary:${PROTO_TMP_OUT_DIR}" \
    ...

# Copy each generated file into actual output directory, but only if an
# identical file does not yet exist there. Doing this preserves the last
# modified date.
for file in $( (cd "${PROTO_TMP_OUT_DIR}" && find -type f) | sed "s|^\./||" ); do
  if ! cmp --silent "${PROTO_TMP_OUT_DIR}/${file}" "${PROTO_OUT_DIR}/${file}"; then
    mkdir -p "$(dirname "${PROTO_OUT_DIR}/${file}")"
    cp -rf "${PROTO_TMP_OUT_DIR}/${file}" "${PROTO_OUT_DIR}/${file}"
  fi
done

# Finally delete the temporary protobuf directory.
rm -rf "${PROTO_TMP_OUT_DIR}"
```

**Comment by mkruskal-google** [comment]
This feature would add an extra step of processing the existing generated code and then comparing them.  This is inefficient, so enabling it by default is a no-go.  Making this an opt-in flag doesn't have any technical issues, but it does increase our maintenance burden just to support timestamp-based build systems (which have a number of problems like this).

If you can't migrate to a smarter build system that checks for real changes, I think creating a script similar to what @jul-sh posted would be a good solution.  Protobuf isn't the only library that can update timestamps without making any real changes, so if you set this up it'll likely help you more in the future (instead of having to continue to make this request of all your dependencies).
