### ISSUE TITLE
Could we modify the generated pb.go file?

### ISSUE THREAD

**Issue by zq24** [protocolbuffers/protobuf#6053]
I am wondering if I could make some changes to the generated pb.go file. For example, is it ok to add an interface or associate a function with a struct? 

Thanks in advance.

**Comment by zq24** [comment]
Just to clarify, I wouldn't make any change to the original generated code, just wondering if I could add an interface or functions into that file?

**Comment by timestee** [comment]
i think it will be  better to add the function or interface to a separated file but not the generated one

**Comment by BSBandme** [comment]
Sorry but golang protobuf is in [a different repo](https://github.com/golang/protobuf), maybe ask question there would get better help.
@dsnet 

Generally for builtin languages we have insertion point for user to change the generated code, but for go it is already implemented in a plugin, so insertion point maybe not work for that.

**Comment by dsnet** [comment]
We provide no compatibility guarantees for injected or modified code. While it is probably safer to inject methods in a separate Go files, there's no guarantees that this practice won't be broken in the future since we reserve the right to add new methods.

For example, injecting a `UnmarshalJSON` method in a separate file might work today, but might not work in the future if we do golang/protobuf#256.
