### ISSUE TITLE
ByteSizeLong() return 0

### ISSUE THREAD

**Issue by shihaonan369** [protocolbuffers/protobuf#6066]
1. `
2. //proto
3. message Test
4. {
5. 	uint32 a = 1;
6. 	uint32 b = 2;
7. }
8. `
9. `
10. //cpp
11. Test test;
12. test.set_a(0);
13. test.set_b(0);
14. auto size = test.ByteSizeLong();
15. //size is 0
16. `

**Comment by acozzette** [comment]
This behavior may be surprising if you're used to proto2 but it is the expected behavior for proto3. In proto3 there is no distinction between a field being unset and being set to its default value (i.e. 0 for integer fields), so a zero-valued field is not serialized. Since your message just contains zeros, there is nothing to serialize. Note that if you prefer the proto2 behavior you can stick with proto2 by putting `syntax = "proto2";` at the top of your file.
