### ISSUE TITLE
Error Domain=GPBCodedInputStreamErrorDomain Code=-103 "(null)" UserInfo={Reason=Unexpected tag read}

### ISSUE THREAD

**Issue by zw318** [protocolbuffers/protobuf#6075]
Send the same request at the same time, the first request data is successfully parsed, and the second request fails，Error Domain=GPBCodedInputStreamErrorDomain Code=-103 "(null)" UserInfo={Reason=Unexpected tag read}

**Comment by thomasvl** [comment]
I'm guessing there are some other layers involved since the objc protobuf library doesn't do networking on its own; so you'll need to provide more details about what is really happening.  If you can provide the .proto definition(s) and the binaries you are trying to parse it might be easier to spot the problem.  Failing that, more details of how you are getting the binary blobs to send/parse might help out.
