### ISSUE TITLE
[Java] DynamicMessage needs it's own equals strategy

### ISSUE THREAD

**Issue by alexvanboxel** [protocolbuffers/protobuf#6100]
**What version of protobuf and what language are you using?**
Version: master
Language: Java

A DynamicMessage equals operator inherits its functionally from the AbstractMessage. The problem of the operator is that it checks the Descriptor on Object equality.

But the purpose of a DynamicMessage is that you can create messages from non-pre compiler descriptors. You can load a descriptor set from file and generate a DynamicMessage from it, but as those Descriptors are created at runtime you can have **semantically equal messages**, but have a _different descriptor reference_.

My proposal is that the DynamicMessage get's it own equal operator, very similar to the AbstractMessage one, but if the Descriptors are non-object-equal it will just check if the **full Message name** is equal and if it is, return **true**.

**Comment by alexvanboxel** [comment]
I'm willing to create a PR for this.

**Comment by haon4** [comment]
Thanks for filing this issue. I am working on a change to fix this. I think we need to go a little further, check if the full Message name is equal and all the fields + unknown fields are equal. Basically the same as AbstractMessage#equals() but loosening the check for descriptor identity.

**Comment by alexvanboxel** [comment]
Great, that was actually the exact same way I though doing it.

**Comment by haon4** [comment]
While doing this, I realized that Descriptors may want to have their own equals() method too. Then the question becomes what does it mean to have Descriptor equality. Just the full name (with the underlying proto potentially not being equal)? Or do we expect the full DescriptorProto to be equal (which is expensive as it requires going through all the transitive closure dependency).

**Comment by alexvanboxel** [comment]
For DynamicMessage equality I wouldn't go that far. Reasoning is that equality is **important on the values of the message**, but for the schema it's mostly the intent of defining the message of type "X".

**Comment by haon4** [comment]
I don't think we can proceed with the proposal as is. Throughout DynamicMessage, we have a lot of verifyContainingType() call, which check that the FieldDescriptor type is the same. If we proceed with this proposal and assert that DynamicMessageA and DynamicMessageA2 are equal because their fullname are equal, we can get into a weird state where you can call dynamicMessageA.getField(fieldDescriptorA) but not dynamicMessageA2.getField(fieldDescriptorA) - which will throw an IllegalArgumentException.

I guess a better way to work around this would be to ensure that we have some sort of mapping that automatically map A2 to A if they have the same name. This seems too risky to put at the core Protobuf level because A and A2 may actually refer to completely two different Descriptors even if they have the same name. It may be more easily solvable at the application level though.

**Comment by haon4** [comment]
Closing as infeasible :(
