### ISSUE TITLE
IOS integration issue (Xcode 10.1)

### ISSUE THREAD

**Issue by Blurzschyter** [protocolbuffers/protobuf#6114]
Hi,

I'm currently following the steps mention in this [objective-C part](https://github.com/protocolbuffers/protobuf/tree/master/objectivec).
<img width="843" alt="Screenshot at May 08 16-34-18" src="https://user-images.githubusercontent.com/23515008/57361758-b5833080-71af-11e9-86fc-5d14abbc7bc1.png">

And the result I got is this:-
<img width="855" alt="Screenshot at May 08 16-33-46" src="https://user-images.githubusercontent.com/23515008/57361785-caf85a80-71af-11e9-9ee9-efcb28964a6a.png">
Is it correct? If is correct or not, what should I do next?

Since there is no step by step guideline on how to properly integrate this protobuf with iOS project, appreciate anybody assistance on this.
I'm currently using macOS Mojave and Xcode 10.1 . I also want to avoid from using any Cocoapods in my current project.

Thank you ^_^

**Comment by thomasvl** [comment]
The _No such file or directory` is caused because you appear to have missed step in the main directions for checking out the source.  Do a `git submodule update --init --recursive` to fetch the dependencies, then you can run `full_mac_build.sh` again to do a build (and tests) to ensure everything is installed on your machine.

The HISTTIMEFORMAT error seems to be something about your shell environment, that isn't part of the script, so you'll need to look at how you have configured it to see what that error is about.

As far as integrating with Xcode (for iOS); since you don't wan't to use CocoaPods, follow the _Building_ section in the objc `README.md`, it talks about what files need to be added to your project.
