### ISSUE TITLE
google/protobuf/arena.h(692): error C3857: 'Map': multiple template parameter lists are not allowed

### ISSUE THREAD

**Issue by limnax** [protocolbuffers/protobuf#6159]
I get this error when i try to build my project that uses tensorflow libraries.My code is in c++11 and the environment is windows 10.

I built tensorflow from source and completed,i also built protobuf v3.7.0 from source but it gives me the same error.I also installed protobuf using vcpkg but it returns the same error.

This is the error iam getting mocs_compilation.cpp **C:\libs\vcpkg\installed\x64-windows\include\google/protobuf/arena.h(692): error C3857: 'Map': multiple template parameter lists are not allowed** 
C:\libs\vcpkg\installed\x64-windows\include\google/protobuf/stubs/strutil.h(359): warning C4127: conditional expression is constant 
C:\libs\vcpkg\installed\x64-windows\include\google/protobuf/stubs/strutil.h(359): note: consider using 'if constexpr' statement instead 
C:\libs\vcpkg\installed\x64-windows\include\google/protobuf/stubs/strutil.h(366): warning C4127: conditional expression is constant 
C:\libs\vcpkg\installed\x64-windows\include\google/protobuf/stubs/strutil.h(366): note: consider using 'if constexpr' statement instead
 c:\libs\vcpkg\installed\x64-windows\include\unsupported\eigen\cxx11\src/Tensor/Tensor.h(76): warning C4554: '&': check operator precedence for possible error; use parentheses to clarify precedence
 c:\libs\vcpkg\installed\x64-windows\include\unsupported\eigen\cxx11\src/Tensor/TensorMap.h(33): note: see reference to class template instantiation 'Eigen::Tensor' being compiled

**Comment by BSBandme** [comment]
I think `if constexpr` only available after c++ 17, and it might not be fixed to that since we need to be compatible with c++ 11

**Comment by Sil3ntStorm** [comment]
While `if constexpr` is only available starting with C++17 and you may want to remain compatible with C++11, it would be good if this issue could be fixed.
Especially considering that this issue forces users of the library to either globally disable a useful warning or litter the code with 10+ lines of conditional warning disabling around **every inclusion** of problematic protobuf headers.

Preferably by conditionally marking things that can be `constexpr`, something along the lines of
```cpp
#if defined(__cpp_if_constexpr) && __cpp_if_constexpr >= 201606L
#define CEXPR constexpr
#else
#define CEXPR
#endif
```
then using `if CEXPR (sizeof(x) == sizeof(int))` rather than a simple if statement where appropriate.

Alternatively, warnings that you do not care to fix should be disabled in as tight a scope as possible (**without bleeding to the outside**), so that users of the library get to use/enable the warnings they would like to have, rather than the usable warnings being dictated by a third party library.

**Comment by sbenzaquen** [comment]
This file has been removed at head in favor of Abseil's implementation.
