### ISSUE TITLE
memory does not release by clear()

### ISSUE THREAD

**Issue by michael4338** [protocolbuffers/protobuf#6197]
we use c++ 11 and protobuf 3.3.0, and recently found a problem that the memory hold by protobuf object does not get released by calling clear() function.  

A Demo c++ class and Protobuf message can be like below:

_class Foo {
public:
    void Add(const Message& message) {
        Message* p_message = bar.add_messages();
       *p_message = message;
    }

    void Delete() {
         bar.clear_messages();
    }

private:
    proto::Bar bar;
};

message Bar {
    repeated Message messages = 1;
}_

After calling Delete the memory is not released.  However, if we use a smart pointer to wrap the protobuf object, like 

_unique_ptr<proto::Bar> bar,_ 

and when delete, we reset the pointer like 

_bar.reset(new proto::Bar())_

The hold memory is gone.  Could you help to clarify?

**Comment by acozzette** [comment]
I believe this is actually the expected behavior. Sometimes as an optimization code will keep around the same proto message and keep reusing it, since it will effectively hang onto memory and avoid needing to allocate and deallocate memory. This is less important now that we have arenas, though. If it's important in your case to free the memory eagerly then I would recommend going with your approach of storing the message in a `unique_ptr`.
