### ISSUE TITLE
is not found in descriptor pool

### ISSUE THREAD

**Issue by denept** [protocolbuffers/protobuf#6219]
hello！！

$from = new \Protoc\Person();
$from->setId(1);
$from->setStr('foo bar, this is a message');
$from->setOpt(29);

显示：
Protoc\Person is not found in descriptor pool

autoload_psr4：
return array(
    'Protoc\\' => array($baseDir . '/extend/Protoc'),
);

Person.php
namespace Protoc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protoc.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
...

path：
extend/Protoc/Person.php

同目录SnowFlake可以正常调用
extend/Tools/SnowFlake.php

请问是什么问题？

**Comment by TeBoring** [comment]
Have you set autoload properly?

**Comment by TeBoring** [comment]
We also generate some class in GPBMetaData, which is depended by Persion. You also need to set autoload for it.

**Comment by denept** [comment]
我用的是thinkphp5框架 extend/路径下的类库都是自动加载。

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/php/composer.json#L17
I don't know what is thinkphp5 but you need to tell autoload to find your generated code for protobuf.

**Comment by denept** [comment]
Thanks TeBoring.
我生成时的包名（命名空间）路径有问题。

**Comment by Xenology** [comment]
For anyone that is stumbling across this issue from google searches. You will want to make sure that the autogenerated Protobuf classes are in the root of your application and not under another namespace or folder. Autoloading your classes in the root namespace is required because of the way the classes are generated and loaded into the Protobuf internal classes. 

If your composer file or autoloader specifies a namespace default for a `src` folder, you will need to place the generated files in a folder outside the src directory and load them into the root namespace like such. 


```
    "autoload": {
        "psr-4": {
            "App\\": "src/",
            "": "protobuf/"
        }
    },
```

This should resolve the error of classes not being found in the descriptor pool, as classes are loaded into the descriptor pools based on their entire namespace and not their class name. Having additional folders or namespace prefixes in the class signature will result in the Protobuf internal methods looking for the class name in the internal descriptors, but being unable to find it because its indexes as the fully qualified namespace. This results in the `not found in descriptor pool` error.
