### ISSUE TITLE
protoc: invalid span in source location

### ISSUE THREAD

**Issue by dsnet** [protocolbuffers/protobuf#6378]
Using `protoc v3.6.1`

Given the following .proto file:
```proto
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

syntax = "proto3";

package goproto.protoc.comments;

option deprecated = true;
option go_package = "google.golang.org/protobuf/cmd/protoc-gen-go/testdata/comments";

message DeprecatedMessage {
  option deprecated = true;
  string deprecated_field = 1 [deprecated=true];
}

enum DeprecatedEnum {
  option deprecated = true;
  DEPRECATED = 0 [deprecated=true];
}
```

When compiling this, one of the `google.protobuf.SourceCodeInfo` provided by `protoc` looks like this:
```
location: {
	path: [4, 0, 2, 0, 4]
	span: [13, 2, 12, 27]
}
```
The span in this message makes no sense. It is saying that the location starts on line 13 and ends of line 12.

**Comment by jhump** [comment]
This only happens with `syntax = "proto3"` files, for optional fields. It is trying to emit a source location for the _label_, which is not present (and not allowed for non-repeated fields in proto3).

Since there is no actual label in the source, it attributes the start location to be the start of the field and the end location to be the end of the previous element. The end location calculation incorrectly assumes that the last source location generated would have been the label.
