### ISSUE TITLE
ios  export. M file contains import "XXX /A.h"

### ISSUE THREAD

**Issue by luangaolei** [protocolbuffers/protobuf#6429]
Export objc file, export. M file contains import "XXX /A.h", how to deal with?
For example, the two files a.bobjc.h and a.bobjc.m are exported, and within a.bobjc.m there is the import "XXX/ a.bobjc.h"

**Comment by thomasvl** [comment]
I'm sorry, I'm not really clear what the issue is.  Can you provide some example `.proto` files that show the issue when generated (and the command line used to generate)?

**Comment by luangaolei** [comment]
hi,  @thomasvl How should ios parse data dynamically? For example, if you have an A.proto export file that is A.pbobjc.h and A.pbobjc.m, how can you dynamically know that the pbdata returned by the server is the corresponding data in this A.proto?

**Comment by luangaolei** [comment]
pod 'Protobuf', '~> 3.7.0'

**Comment by luangaolei** [comment]
What I want to do is get directly from the pbdata returned by the server to which file this pbdata belongs to (a.bobjc.h).

**Comment by thomasvl** [comment]
The protobuf binary format doesn't actually capture any type information, so you need to know the types of the messages you are receiving from the server to know what specific message type to parse them as.

Protobuf instead defers this sorta information to what ever higher level protocol you are using to send the messages.  gRPC, etc. take case of that layer/wrapping.  But at the raw message later (network or file), it isn't captured.

**Comment by luangaolei** [comment]
hi, @thomasvl 
Excuse me, the key with "_" is defined for key-value, but the property in pbobjc.h you generated is deleted from "_". For example, if we define a key to be "content_name" and your pbobjc.h file is "contentName", how do we get the value corresponding to "content_name" instead of "contentName"?

And if value is an array, you'll automatically concatenate array after key in.pbobjc.h, for example, if we define an array to be items, you'll automatically concatenate it to itemsArray.
I'm looking at the documentation for you to improve readability,
How can I get an array value from items instead of itemsArray?

I mean not by manually removing the "Array" string from our oc code.

**Comment by thomasvl** [comment]
The objc generated attempt to transform the names from the [protobuf styleguide](https://developers.google.com/protocol-buffers/docs/style) into Apple's naming guidelines for ObjC.

So the underscores are removed and things are CamelCased afterwards to create the property names.

As for repeated fields, the older styleguide didn't call for plurals, it recommended singular form; so _Array_ was appended to make it more clear that it was a array of things and not a single item.  The behavior can't be changed because it would change the code generation and break developers existing code; so _Array_ is still appended.

Only the generated ObjC names are changed, this has no impact on the binary format for protobufs.  ObjC fully interoperates just fine with other protobuf implementations.
