### ISSUE TITLE
RepeatedField uses ArrayPool for improved performance and fewer GCs

### ISSUE THREAD

**Issue by prat0088** [protocolbuffers/protobuf#6529]
**What language does this apply to?**

csharp

**Describe the problem you are trying to solve.**

Both when constructing messages to serialize and deserializing messages...

Reduce memory pressure, reduce pauses from Gen 2 GCs (when array > 85kB), increase performance.

**Describe the solution you'd like**

Use [ArrayPool](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=netstandard-2.1) internally to allocate `array`.

It would be nice to allow the user to set the instance of ArrayPool to use so they have further control over how objects are allocated, but I'm not sure where a good place would be.

**Describe alternatives you've considered**

Allowing the user to pass in the allocated array to use, but that would be terribly messy.  Neither is it realistic because RepeatedField manages the size of `array` and reallocates it as it grows.

**Additional Context**

[A good overview of ArrayPool at Adam Sitnik's blog](https://adamsitnik.com/Array-Pool/)

I am concerned that ArrayPool is slower for arrays less than 1000 bytes, which is why it would be nicer to give the caller control over whether ArrayPool is used.  Perhaps with Google.Protobuf.Options.UseRepeatedFieldArrayPool static... which again feels messy, but I'm not sure where else to put it.

**Comment by jskeet** [comment]
Just a drive-by comment while looking at `RepeatedField`: doesn't this really depend on being able to return the array to the `ArrayPool` when we're done with it? That's fine when we effectively discard an array due to reallocation, but the normal situation of "create a message, populate a repeated field, use the message, then let the garbage collector handle it" doesn't give us anywhere to hook in returning the array to the pool.
