### ISSUE TITLE
How can I assign non-ascii string to a protobuf string field in C++?

### ISSUE THREAD

**Issue by yzhao1012** [protocolbuffers/protobuf#6540]
Given a string field, there is a set_<file_name>() API.
Should I encode the std::wstring as std::string, and then assign with the API above?

**Comment by wangkirin** [comment]
Hi @yzhao1012, the protoc genetate API for set_<field_name> list as below:
```C++
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
```
Since the protoc doesn't generate set_<field_name>() with std::wstring parameter,you'd better encode the std::wstring as std::string or char* before you call the set_<field_name> API.
Another tips for you is: using ```bytes``` instead of ```string``` as proto type in .proto file,because 
```bytes``` may  contain any arbitrary sequence of bytes while ```string``` only support UTF-8 encoded or 7-bit ASCII text.

**Comment by yzhao1012** [comment]
So it appears to me, that essentially, string in C++ API is just a non-forced hint that the data is UTF-8 string, but there is no guarantee that it works such.

**Comment by TeBoring** [comment]
You cannot set non-utf8 string to string field. The encoding method will in the end throw the warning.

**Comment by TeBoring** [comment]
Use bytes field in your case.
