### ISSUE TITLE
Can protobuf-lite be reduced to less than 340 kB?

### ISSUE THREAD

**Issue by r44083** [protocolbuffers/protobuf#6633]
I have noticed that C++ protobuf-lite with ```-Os``` takes about **340 kB** of ROM. It's quite big amount of memory, especially for embedded systems.
**Is it possible to reduce this size?**

I have the following output without generation any sources from .proto files:
```
   text    data     bss     dec     hex filename
 339620   12260    6336  358216   57748 ./out/bin/protobuf-example.exe
```

In case of processing .proto file, ```option optimize_for = LITE_RUNTIME;``` doesn't help a lot.

**Comment by acozzette** [comment]
If you want to get the code size as small as possible, I would recommend statically linking `libprotobuf-lite` into your binary so that you can let the linker remove any unreferenced code. Make sure to compile with `-ffunction-sections` and `-fdata-sections` and link with `-Wl,gc-sections`. Setting `option optimize_for = LITE_RUNTIME;` does also help, but the savings will be roughly proportional to the size of your .proto files. If you have only a small .proto file, then the size of the protobuf runtime (i.e. `libprotobuf` or `libprotobuf-lite`) might dominate over the size of the generated code. I'm not sure offhand how small you can get the code overall, so you might have to experiment with it a bit.

**Comment by acozzette** [comment]
Actually it sounds like you might be using Windows, so I am not sure if the compiler and linker flags I mentioned will work. The important thing is just to enable whichever flags are necessary to allow the most aggressive linker stripping.

**Comment by acozzette** [comment]
If you really need to get the code size down further, you might also want to check out some of the C protobuf implementations such as nanopb, upb, or protobuf-c.

**Comment by r44083** [comment]
I builded protobuf-lite for cortex-m4 using arm-none-eabi-gcc and get **157 kB**.

no rtti, ```std::thread```, ```std::mutex``` and ```std::call_once``` is used.

With ```-Os```, ```-ffunction-sections```, ```-fdata-sections``` and ```-Wl,--gc-sections``` enabled, I get such results:
```
arm-none-eabi-size ./out/bin/protobuf-example.elf
   text    data     bss     dec     hex filename
 157416     940    6856  165212   2855c ./out/bin/protobuf-example.elf
```

This result isn't enough for my requirements. I'll have to think about what to do about it. (I don't really want to use nanopb or protobuf-c instead)

**Comment by acozzette** [comment]
If `main()` is empty and it's still generating that much code then something must be going wrong. It would be interesting to see what code is getting included. You could try using the size profiler [Bloaty](https://github.com/google/bloaty) for this.
