### ISSUE TITLE
Feature Request: Timestamp Wrapper WKT

### ISSUE THREAD

**Issue by veqryn** [protocolbuffers/protobuf#6650]
**What language does this apply to?**
proto3

**Describe the problem you are trying to solve.**
Wrapper types are useful in proto3 to represent a nullable field.
As Well Known Types, they are extra-useful because of their concise and easily understood representation when converted to JSON (ie: they allow "null" as the value in json). This is great especially when used with a gRPC-Gateway.
As of right now, there is not a wrapper for the WKT Timestamp.

**Describe the solution you'd like**
I would like to have a Timestamp Wrapper WKT.

**Describe alternatives you've considered**
A non-WKT timestamp wrapper (ie: just making my own message with a WKT Timestamp nested in it) would not have the WKT advantages, such as the easily understood JSON conversion.

**Comment by mattwelke** [comment]
I don't think we need a wrapper type for any type that is a message, including Timestamp.

> Wrapper types are useful in proto3 to represent a nullable field.

Any field that is a message is nullable, so the WKT Timestamp is already nullable.

> As Well Known Types, they are extra-useful because of their concise and easily understood representation when converted to JSON (ie: they allow "null" as the value in json). This is great especially when used with a gRPC-Gateway.

Because Timestamp is already a WKT, plugins can take advantage of this and use custom representations for JSON. Adding another WKT that is a wrapper wouldn't change the current situation, which is that it's up to plugin implementers to recognize that it's a WKT and make optimized JSON representations.

**Comment by perezd** [comment]
> Any field that is a message is nullable, so the WKT Timestamp is already nullable.

That's correct. We won't be adding this, but thank you for the suggestion!
