### ISSUE TITLE
protoc is not handling non-ASCII paths correctly on windows (when @<filename> "argument file" is used)

### ISSUE THREAD

**Issue by joaoportela** [protocolbuffers/protobuf#6715]
**What version of protobuf and what language are you using?**
Version: 2.23.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
I'm using Grpc.Tools NuGet

**What did you do?**
1. Follow the quickstart tutorial
```
dotnet new grpc -o GrpcGreeter
cd GrpcGreeter
dotnet run
```

**What did you expect to see**
Program builds and runs.

**What did you see instead?**

Build fails with this output:
```
--grpc_out : error : protoc-gen-grpc: The system cannot find the path specified. [D:\dev\GrpcGreeter\GrpcGreeter.csproj]

The build failed. Fix the build errors and run again.
```

**Anything else we should know about your project / environment**
I've reported this issue https://github.com/grpc/grpc-dotnet/issues/559 initially.
They said it should be related to this tools issue: https://github.com/grpc/grpc/issues/17995
Where it is said that the issue [might be in protoc and not grpc tooling](https://github.com/grpc/grpc/issues/17995#issuecomment-475510959).

**Comment by aquamoth** [comment]
I also have this problem. 

I often work on different computers, and Windows automatically creates my AzureAD user profile in _C:\Users\MattiasÅslund\_. So far my only workaround is to create a new local user account on each machine, so I get an "acceptable" path. 

If I keep working with gRpc, this will be _really_ annoying.

**Comment by joaoportela** [comment]
In case someone else ends up here.

My preferred workaround is [changing where global-packages is located](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders).
As described in this issue https://github.com/grpc/grpc/issues/17995#issuecomment-607159949

**Comment by Falco20019** [comment]
The problem is not `protoc` but how windows handles response command files... I also can't find out how to use UTF-8 or unicode in those files.

**Comment by bhaeussermann** [comment]
I also ran into this issue and came here from [grpc/grpc#17995](https://github.com/grpc/grpc/issues/17995).

There is a [PR for Grpc.Tools]((https://github.com/grpc/grpc/pull/22916) which implements a work-around for this issue, but it is currently stale as it might introduce other issues. 

It is mentioned [there](https://github.com/grpc/grpc/pull/22916#issuecomment-656593815) that the issue lies in the fact that protoc is ignoring the BOM when reading the response file. The solution suggested there seems relatively simple. Could someone please look into it?

**Comment by jtattermusch** [comment]
@fowles  this is actually not a problem that's C# specific. Same problem exists for all other languages that use protoc (but C# toolchain happens to use the `@<filename>` commandline argument).

The issue is that when the `@<filename>` cmdline option is used, non-ASCII characters in the input file containing options/arguments are not being processed correctly.

https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/src/google/protobuf/compiler/command_line_interface.cc#L2096

https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/src/google/protobuf/compiler/command_line_interface.cc#L1447

The ExpandArgumentFile function is using `std::ifstream` to read the contents of the argument file and that ends up not working correctly:
https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/src/google/protobuf/compiler/command_line_interface.cc#L1425

[more details here](https://github.com/grpc/grpc/pull/22916#issuecomment-656593815)

**Comment by jtattermusch** [comment]
Basically the rootcause of this is https://github.com/protocolbuffers/protobuf/issues/7474, but I'm not sure if making ExpandArgumentFile support wifstream is feasible.

**Comment by tonydnewell** [comment]
@joaoportela @jtattermusch I think this can now be closed since https://github.com/protocolbuffers/protobuf/issues/7474 is fixed.
