### ISSUE TITLE
to_h generates non-intuitive hash for wrapper types (StringValue, Int32Value, etc)

### ISSUE THREAD

**Issue by damianthe** [protocolbuffers/protobuf#6755]
**What language does this apply to?**

Ruby.

**Describe the problem you are trying to solve.**

The primitive types in Protobuf are non-intuitive to use because of the wrapping primitive value types. There are two areas of impact:
1) When creating message objects from a hash. The caller has to understand that the primitive types must be assigned `{ value: <value> }` rather than the value itself.
2) When converting message objects to a hash. The downstream users of the hash must understand that every primitive type will have the structure `{ value: <value> }`

For example, consider the following message object
```proto
message Customer {
  google.protobuf.StringValue name = 1;
}
```
It requires a value specification on instantiation: 
```ruby
customer = Customer.new(
  name: { value: "Paul" }
)
```
And requires an understanding of the nested value attribute on `to_h`:
```ruby
customer.to_h # { name: { value: "Paul" } }
```

For these primitive types, the underlying implementation is leaking into the callers of the gem API causing dependent code to be more complex.

**Describe the solution you'd like**

Have these primitive types treated in such a way so that the caller only ever has to deal with the "true" ruby hash structure. No more "{ value: <value> }".

With the example above, it looks like this.
```ruby
customer = Customer.new(
  name: "Paul"
)
customer.to_h # { name: "Paul" }
```

**Benefits**:
- callers don't have to know about the underlying nested value attribute
- the API becomes more intuitive, since the input and output hashes can be structured like normal Ruby hashes.

**Describe alternatives you've considered**

None.

cc @TeBoring @thomasvl @acozzette @tobi @sirupsen

**Comment by chrisbloom7** [comment]
+1 to this. This feels particularly frustrating because it is inconsistent with how a Timestamp is interpreted. For instance if you have a Timestamp attribute like so

```protobuf
message Customer {
  google.protobuf.StringValue name = 1;
  google.protobuf.Timestamp created_at = 2;
}
```

Passing in a primitive time value is converted as expected:

```ruby
customer = Customer.new(name: { value: "Paul" }, created_at: Time.now.utc)
# => <Customer: name: <Google::Protobuf::StringValue: value: "Paul">, created_at: <Google::Protobuf::Timestamp: seconds: 1582826050, nanos: 88089000>>
```

**Comment by jez** [comment]
+1. The problem I'm running into is that in our codebase I see people doing a lot of:

```ruby
JSON.load(message.to_json)
```

to get the effect of "convert to a Hash but make strings just be strings, not `{value: "the string"}`"

This is bad for it's own reasons: it means that things like #6251 come into play. Since people aren't using the protobuf-specific JSON decoder, an int64 can turn into a string by round tripping through `JSON.load` (while with `.to_h` it's still a Ruby `Integer` arbitrary-precision object).

**Comment by haberman** [comment]
Wrapper types are now deprecated in favor of true `optional` fields: https://github.com/protocolbuffers/protobuf/issues/1606#issuecomment-618687169 True `optional` fields have the desired behavior.

The behavior change requested in this bug would be a backward-incompatible change now. Since true `optional` fields give the desired behavior, I think we are unlikely to change the behavior of the wrapper types now.
