### ISSUE TITLE
Support using python memoryview for setting bytes data

### ISSUE THREAD

**Issue by wmdrichards** [protocolbuffers/protobuf#6782]
**What language does this apply to?**
Python

**Describe the problem you are trying to solve.**
Protobuf serialization of large byte data from a numpy array requires seemingly unnecessary copies (calling `ndarray.tobytes()`)

**Describe the solution you'd like**
Support setting bytes data using a `memoryview`

**Additional context**
Passing `ndarray.data` to a protobuf class raises `TypeError: <memory at 0x119b1f588> has type memoryview, but expected one of: bytes`

**Comment by fandreuz** [comment]
Hi @acozzette @haberman @zhangskz, I'm reaching out since I see you were active under #8047. I propose to implement `memoryview` support for `bytes` fields only, it should be much more straightforward than having it for repeated scalars.

I have a draft implementation at https://github.com/protocolbuffers/protobuf/commit/821695fa7f57f93032bac821c00762a90fe57d6f, let me know if you feel like such a change would be accepted.
