### ISSUE TITLE
Protobuf is compiled with -g -O2 despite what configure.ac claims

### ISSUE THREAD

**Issue by neongreen** [protocolbuffers/protobuf#6941]
By default, protobuf is compiled with `-O2 -g`, even though `configure.ac` claims it shouldn't be:

https://github.com/protocolbuffers/protobuf/blob/a9f390f44e3d138e1e94fd17046f865517b3b62d/configure.ac#L39-L44

I'm building latest `master` as follows:

```
./autogen.sh
./configure
make
```

Here's a sample compiler invocation during the build:

```
/Library/Developer/CommandLineTools/usr/bin/clang++ -DHAVE_CONFIG_H -I. -I..
  -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare
  -O2 -g -std=c++11 -DNDEBUG -MT google/protobuf/generated_enum_util.lo -MD -MP
  -MF google/protobuf/.deps/generated_enum_util.Tpo 
  -c google/protobuf/generated_enum_util.cc 
  -fno-common -DPIC -o google/protobuf/.libs/generated_enum_util.o
```

What would be the best way to compile protobuf without `-g`? This would help a lot with https://github.com/NixOS/nixpkgs/issues/73919.

**Comment by veprbl** [comment]
Turns out there is some bit of code which has an opposite intention:
https://github.com/protocolbuffers/protobuf/blob/3be9322e28dfcacdb669f646f76fe833fa274107/configure.ac#L85-L101
I'm not aware of what is considered the best practice for handling debug/release builds in autotools, but it seems like, in case of protobuf, downstream needs to explicitly set CXXFLAGS to achieve a release build.
