### ISSUE TITLE
Instead of using RepeatedField<> use List<> for c#

### ISSUE THREAD

**Issue by mokoker** [protocolbuffers/protobuf#6995]
Hi there,
I have been using protobuf with grpc in c# .net core 3.0 and generating collections as repeatedfield is causing lots of trouble for me, swagger is not generating json because they don't have setters and model binders can't bind to repeated fields. I don't want to create new dto objects, and had trouble creating model binders. Is no one passing these protobuf generated collections to web api controllers. 

If I update to .net core 3.1 model binders bind to RepeatedField if its not readonly. Lack of setter is causing the problems with swagger and model binders. 

Anyone knows the reason why there are no setters?

Thanks.

**Comment by mokoker** [comment]
public sealed partial class Test
    {
        public const int ChildrenFieldNumber = 2;
        private static readonly FieldCodec<int> _repeated_children_codec
            = FieldCodec.ForInt32(18);
        private RepeatedField<int> children_ = new RepeatedField<int>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public RepeatedField<int> Children
        {
            get { return children_; }
            set { children_ = value; }
        }
    }

if i put the code above in the partial class everything works flawlessly, what is the problem with readonly and setter.

**Comment by bamancio-futura** [comment]
These fields with no setter make trouble working with GraphQL dotnet.

**Comment by elharo** [comment]
We (Google) used to have mutable protos. Experience taught us this was a very painful mistake. Immutability is a deliberate feature.

**Comment by erdalsivri** [comment]
> We (Google) used to have mutable protos. Experience taught us this was a very painful mistake. Immutability is a deliberate feature.

It is still possible to mutate a `RepeatedField` with `Add` and `AddRange` methods similar to how it is possible to mutate other fields such as primitives or sub-messages. The only thing the current design ensures is that the reference to the list is immutable. Maybe Java uses builders and keeps the proto class immutable but in C# a proto class is definitely not immutable.

```c#
SomeProto proto = new SomeProto();
// Mutate some fields
user.Id = 4;
user.Name = "some name;
```

I am curious why the following doesn't work or what issues it might cause:

```c#
private List<string> _names = new List<string>();
public List<string> Names {
  get => _names;
  set {
    if (value == null) {
      throw new ArgumentNullException();
    }
    _names = value;
  }
}
```

Not having a setter is causing issues with EFCore. We cannot project database results into our proto DTO objects with repeated fields (there is an open [FR](https://github.com/dotnet/efcore/issues/16867) on the EFCore side btw):

For example, the following doesn't work because `Roles` is `RepeatedField` without a setter:

```c#
_users.Select(u => new UserProto {
  Roles = { new RoleProto { ... } },
});
```

**Comment by elharo** [comment]
OK, this is C# which I think does use mutable protos for better or worse. I think the issue may be you need to use addFoo rather than setFooList or something like that. Reassigning to @jskeet for triage.

**Comment by erdalsivri** [comment]
Even though I used `List` in the example, I think `RepeatedField` is fine. It implements `IList` so integrates well with other code. Sorry for the confusion.

However, not having a setter does cause some issues in EFCore projections. I do understand that there might be some internal assumptions that might be broken with a setter so feel free to close this bug. I hope EFCore team supports `MemberMemberBinding` soon: https://github.com/dotnet/efcore/issues/16867. In the meantime, we are projecting first to an anonymous type and then to proto (outside of the LINQ expression) as a workaround:

```c#
var users = dbContext.Users
  .Select(u => new {
    Roles = u.Roles.Select(r => new UserRoleProto {
      // ...
    }).ToList(),
  })
  .AsEnumerable()
  .Select(u => new UserProto {
    Roles = { u.Roles },
  })
  .ToList();
```

**Comment by jskeet** [comment]
@erdalsivri: Right, understood. I'll close this as I can't see us changing it - at least not until we're making other major changes - but it *is* good to hear about the impact of various decisions.

**Comment by mirhagk** [comment]
Is the option of making other major changes on the table? In particular #9352 (inconsistencies between optional and wrapper types). Between this and that there's some major inconveniences with working with the library, essentially disallowing expressions for constructing protos.

That could be what is mentioned with GraphQL above, I'm not as familiar with that, but I've definitely come across the issue with many things that expect to be able to use expressions to map one type to another. EF being the most inconvenient example. This issue and the other turn a simple `foo.Where(someCondition).Select(x=>new FooProto{...})` into a much more awkward version that has to create intermediate objects simply because protobufs can't safely assign a value to a field.

**Comment by jskeet** [comment]
> Is the option of making other major changes on the table?

*Potentially*, but with a very high bar, basically.

**Comment by mirhagk** [comment]
May be worth collecting these with a tag or something rather than closing them outright. Each one individually may not warrant a breaking major version, but enough of them together could.

**Comment by stefandxm** [comment]
This thread serves as good learning material for programmers who wishes to use code from large corporates to save time. Lesson to be learned: They don't give a fuck about you :)
