### ISSUE TITLE
protobuf should support that a integer value is 0 or null (not be set at all)

### ISSUE THREAD

**Issue by omjangir** [protocolbuffers/protobuf#7115]
Currently, protobuf doesn't allow to set a null value. It doesn't give way to generate an integer field as a pointer or without the pointer.

for e.g. protobuf should support that an integer value is 0 or null (not be set at all)
Design decision to not support presence in proto3.  In proto3 there is no "not set" status separate from 0.
https://github.com/golang/protobuf/issues/1024

**What language does this apply to?**
GOLang
If it's a proto syntax change, is it for proto2 or proto3?
proto3
If it's about generated code change, what programming language?
golang
**Describe the problem you are trying to solve.**
In proto3 there is no "not set" status separate from 0.
In communication between 2 systems, if we add a new integer field and for some case's it will be set and for others it will be not set. So, the other system receiving values in this new field should able to differentiate between "not set"/nil and 0. i.e. ignore if its nil and consider only if its value present.

**Describe the solution you'd like**
Protobuf should support that an integer value is 0 or null (not be set at all)

**Describe alternatives you've considered**

**Additional context**
https://github.com/golang/protobuf/issues/1024

**Comment by codebreach** [comment]
You can use Int32Value and Int64Value from the well known types for this - https://godoc.org/github.com/golang/protobuf/ptypes/wrappers

these support being null separate from being 0 (in case of int)

**Comment by jschultz410** [comment]
@omjangir That boat sailed a long time ago and isn't coming back for proto3.  You can try to make your case for proto4 if / when that happens, but I doubt they will listen.  Too much time, work, and reputations have been sunk into their current approach for them to change now.

protobuf does not directly support the notion of null like JSON does.  Your best hope to get something similar is to infer that absence of a field means null within some context.

For example, if you want to update one field of a resource to be null, then in your update pass a FieldMask that names that specific field, but then have the field be absent in your message, and interpret this situation to mean "set that field to null."

For scalars, like string, sint32, etc., protobuf makes even this approach difficult because default values for scalars will always be absent from the serialization.  So, you won't be able to distinguish between 'absent because we want it to be null' and 'absent because we want it to have the default value.'

To get around that roadblock, you have to wrap all of your nullable scalars in wrapper messages (or use singleton oneofs).  Then you can at least detect whether the wrapper is absent or present.  If the wrapper is absent, then interpret that to mean null in the proper context (e.g. - an accompanying FieldMask specifying it).  If the wrapper is present, then interpret the contained value as normal.

You should probably use [google.protobuf.wrappers.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto) for your wrapper types.  These are "Well Known Types" and might get some extra love in the different generated languages than if you used your own.  Unfortunately, there are not wrappers for all the basic scalar types for some reason.

**Comment by devhl-labs** [comment]
Just serialize the class and pass a string over grpc.  Im sure that removes some of the efficiency, but why jump through hoops just to pass a null?

**Comment by kskalski** [comment]
This should be now possible with new presence api, which is implemented (but still experimental) https://github.com/protocolbuffers/protobuf/issues/1606#issuecomment-618687169
docs: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
