### ISSUE TITLE
C# : Why generated code throw exception on null values(.e.g string) instead of just setting default value?

### ISSUE THREAD

**Issue by zeinali0** [protocolbuffers/protobuf#7131]
Why generated code throw exception on null value assignment?
I know in new version of protobuf(v3) you decide to remove optional feature and all field most have value.
But why just don't set default value for some primitive type like string instead of throwing ArgumantNullException? this behavior has conflict with some tools like AutoMapper.
I mean this behavior would affect other part of a program.
if in grpc-area all null value most be replaced with default value so just keep this constraint in grpc-area. throwing a exception for setting null value would cause this constraint flow in other part of program which i think it is not a good practice and it is against cross-cutting concern.

**Comment by jtattermusch** [comment]
I'm not sure I understand the question. Can you provide an example what is the current behavior of Google.Protobuf (code example) is and how it should be changed?

**Comment by zeinali0** [comment]
I mean instead of throwing exception just use default value for strings.


**This is current behavior(which throw ArgumantNullException):**
```
public const int FirstNameFieldNumber = 2;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
```

**This is my suggestion:**

```
public const int FirstNameFieldNumber = 2;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = value ?? "";
      }
    }
```

**Comment by anon17** [comment]
AIU, your code is generated by grpc, not protobuf.

**Comment by anon17** [comment]
You can use [StringValue](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/test_messages_proto3.proto#L216) that is mapped to nullable string. Though tests have stuff like [optional string field](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs#L615), I wonder if string is optional by default.

**Comment by zeinali0** [comment]
Yes, But they forward me here. I asked question there at first(https://github.com/grpc/grpc-dotnet/issues/734)

**Comment by zeinali0** [comment]
> You can use [StringValue](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/test_messages_proto3.proto#L216) that is mapped to nullable string. Though tests have stuff like [optional string field](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs#L615), I wonder if string is optional by default.

Actually i'm not looking for a secondary solution. the problem is throwing Exception on assigning null to a string which affect all other part of our code which they got mapped to a protobuff( or grpc) generated class.
I mean with current behavior all models or mappers should do such a thing **`protobuffClass.StringProp = ourModel.StringProp ?? ""`**  for every single string property because if you dont, you will get ArgumantNullException.

**Comment by anon17** [comment]
Well, yes, if you use the wrapper, you can simply assign the property, see the [generated code](https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs#L1611) - it's simple assignment.

**Comment by jtattermusch** [comment]
I think the answer is as simple as this behavior would be counterintuitive: in proto3 a string field cannot have a value of null, it can only be an empty string. To allow setting a null to a property, but the value being set to "" in actuality seems confusing and dangerous.
I'm going to close as "working as intended".

**Comment by jtattermusch** [comment]
> AIU, your code is generated by grpc, not protobuf.

The code for protobuf messages is actually generated by protobuf, but Grpc.Tools bundles the protoc binary to make things simpler (see src/google/protobuf/compiler/csharp in this repository)

**Comment by uecasm** [comment]
@jtattermusch This code generation makes less sense for proto2 files -- in particular instead of writing the logical code:

    message.Foo = foo;  // from a method parameter

You have to instead write:

    if (foo == null) message.ClearFoo(); else message.Foo = foo;

Or, if you happen to know that `message` is currently clear, you can conditionally perform the assignment:

    if (foo != null) message.Foo = foo;

But still -- for both proto2 and proto3 -- all of these things mean that you cannot use C# [object initialization syntax](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-initialize-objects-by-using-an-object-initializer) -- because there is no way to indicate conditional setting of a property that way.

    return new MyProtoMessage()
    {
        Foo = foo,  // oops, can't do this if it might be null
        // now imagine this with >10 properties that might be individually null
    };

This makes protobuf generated classes counter-intuitive and contrary to best practices in C#.

**Comment by anon17** [comment]
> in proto3 a string field cannot have a value of null, it can only be an empty string

That said, the field can be missing altogether, which I would interpret as a null value. Currently the message serialization omits the field when the string is empty, which feels wrong. I'd say nullable C# types should receive null value when the field is missing, non-nullable types like integers should keep default value (they aren't).

As I understand, current design is influenced by repeated fields and dictionaries, where you can't omit a value to express null?

**Comment by anon17** [comment]
that was (they aren't touched during deserialization when the field is missing)

**Comment by uecasm** [comment]
The protobuf protocol default for an omitted string is an empty string; this is probably influenced by C++ `std::string` not having a null state, only an empty state (albeit that C `char*` does have both).

From this it is reasonable that when you get the property you will get an empty string, not null.  However I do not think that it is correct that (at present) when you set the property it will accept empty string but throw an exception on null.  Even for proto3 it ought to accept null and treat it indistinguishably from empty string.

For proto2, since the underlying wire format supports a null state distinct from empty string (to represent "field not present"), which you can detect by reading the HasX property, setting to null should be equivalent to clearing the value.  This is indeed how it works for message properties, but not for string or bytes properties.

**Comment by anon17** [comment]
Form the looks of it, proto3 has different representations for null and empty values, it's not different from proto2 in that regard, C# can represent both naturally with nullable string, that would be feature parity with the protocol. It's normal for non-nullable strings to not differentiate between null and empty values, C++ can keep doing what it does now, accidentally business logic usually doesn't care about that distinction either.

**Comment by uecasm** [comment]
The wire format does distinguish these, but the proto3 language, by design, treats the two wire formats as identical (interpreted as empty string).  The proto2 language treats them as separate cases, albeit still as reading an empty string if you read the property directly rather than checking the Has* properties.

My point, however, is that it still doesn't seem sensible to throw an exception on null assignment, in either case.

**Comment by Falco20019** [comment]
`null` is an invalid case for proto3 on `string`, as the proto `string` is explicitly non-nullable (as it is with C#8). So I also think it behaves correctly. This special case only occurs because C# was handling string as something between value-type and reference-type, different then all other native types.

In your case, I would also prefer to use `google.protobuf.StringValue` over `string`. This will allow you to assign your property naturally and also say that `null` is a valid value for you. If `null` is not a valid value for your protocol, you naturally have to make the transition from a nullable string to non-nullable string in your code base. And just assuming `null` means `string.Empty` is just that, an assumption, that doesn't hold for everyone using the library.

We in our code base explicitly rely on this feature as expected and correct behavior. And I assume this will become less of a problem if C#8 nullables get a wider adoption, finally cleaning up the mess of not being able to define a non-nullable string.

**Comment by uecasm** [comment]
But when `syntax = "proto2"`, empty string and "absent" are distinguishable, and null string is a natural representation for the latter.  (And it's blocking me from switching from another library, because it expects null == absent, not null == exception.)

**Comment by arthurvaverko-kaltura** [comment]
HI all, reviving in case someone is looking for a quick solution for this.
I have forked the repo and created a small patch for `csharp` client to use suggested solution by @zeinali0 

also made a docker file that will compile the code on Alpine (which is what we need) 
https://github.com/arthurvaverko-kaltura/protobuf/releases/tag/v1.15.8.1

**Comment by Falco20019** [comment]
I understand your point that `string` feels like it‘s meant to be nullable also in proto2. But with the introduction of C# 8 and enabling nullability checks, this would explicitly break since it‘s a `string` and not `string?` and therefore does not allow `null`. So just defining this as default is becoming counter-intuitive.

A better solution would be a helper that get‘s the field you are interested in and the nullable string value, clearing in null and setting on any other value. This makes it a forwards compatible user decision. Another option would be a protoc option so that when compiling, the user can define the behavior explicitly without the writer of the protos having to set this in the files (as it‘s not his intention but the users).

Adding options to protoc is a mess, so I‘m mostly sure that will not be done. So having a helper sounds like the best option here.

**Comment by arthurvaverko-kaltura** [comment]
@Falco20019  I agree with C# 8 nullable types this become a very bad implementation.
I like the suggestion of a flag to allow generating null checks or string empty replacement.

This is something I might pick up if you think it can contribute the main repo as a PR .. 
Otherwise ill keep my fork for our internal use and \ or anyone that is getting same issues with C# > 8  versions..

**Comment by arthurvaverko-kaltura** [comment]
@Falco20019 I think i know how I can add `--csharp_opt` flag .. 
thinkin of `--csharp_opt=allow_null_string=true`, im not happy with the flag name .. so I thought maybe you have other suggestions ?

**Comment by Falco20019** [comment]
I would prefer having the helper route over the compiler option, since I personally compile a bunch of files at the same time and this would change all of those in one run. The helper is less intrusive (compile-wise) and can be used a lot more focused, leading to a cleaner API. But that's just my opinion.

If you still want to go with having `null` clear your field, I would not stop at `string` but do it on any nullable and therefore call the option `clear_field_on_null`.
