### ISSUE TITLE
golang & c# parse int64 field error!

### ISSUE THREAD

**Issue by themoonbear** [protocolbuffers/protobuf#7242]
C# protobuf version is v3.11.4.
The protoc version is 3.11.0.
Golang package is  golang/protobuf@v1.3.3. 

The proto file is
`
message Assets {
    int64 gold = 1;
    int64 diamond = 2;
}
`

In the server, the gold = 200 and diamond = 1, but in the client, the gold = 310475 and diamond = 0.

**Comment by jtattermusch** [comment]
Can you include the serialized form of the message (the raw bytes)? This should be able to tell us whether the problem is on the C# or on the go side.
Also, this problem looks like something that would be easily caught by our unit tests and by conformance tests - so I am a bit skeptical if the problem is real (seeing the raw payload should help).

**Comment by themoonbear** [comment]
Yes, you are right. It is my fault. I did some unnecessary operation.
