### ISSUE TITLE
protobuf-mode.el should derive from prog-mode

### ISSUE THREAD

**Issue by sfllaw** [protocolbuffers/protobuf#7316]
**What version of protobuf and what language are you using?**
Version: 0.3
Language: Emacs

**What operating system (Linux, Windows, ...) and version?**
N/A

**What runtime / compiler are you using (e.g., python version or gcc version)**
N/A

**What did you do?**
1. In Emacs, turn on protobuf-mode
2. `M-x eval-expression RET (derived-mode-p 'prog-mode)`

**What did you expect to see**
`prog-mode`

**What did you see instead?**
`nil`

**Anything else we should know about your project / environment**
`protobuf-mode` is a major mode for a programming language, albeit a restricted one. In fact, it claims to be [derived from CC Mode](https://github.com/protocolbuffers/protobuf/blob/4567a21004db641e974200f20715a2c9ab1f2378/editors/protobuf-mode.el#L41), which it actually isn’t.

That’s tangential though. In order to derive from `prog-mode`, the `defun prog-mode` at: https://github.com/protocolbuffers/protobuf/blob/4567a21004db641e974200f20715a2c9ab1f2378/editors/protobuf-mode.el#L195-L219 should instead read:
``` elisp
;;;###autoload
(define-derived-mode protobuf-mode prog-mode "Protocol-Buffers"  ;; Replace defun with define-derived-mode
  "Major mode for editing Protocol Buffers description language.

The hook `c-mode-common-hook' is run with no argument at mode
initialization, then `protobuf-mode-hook'.

Key bindings:
\\{protobuf-mode-map}"
  (kill-all-local-variables) ;; Remove spurious interactive call
  (set-syntax-table protobuf-mode-syntax-table)
  (setq major-mode 'protobuf-mode
        mode-name "Protocol-Buffers"
        local-abbrev-table protobuf-mode-abbrev-table
        abbrev-mode t)
  (use-local-map protobuf-mode-map)
  (c-initialize-cc-mode t)
  (if (fboundp 'c-make-emacs-variables-local)
      (c-make-emacs-variables-local))
  (c-init-language-vars protobuf-mode)
  (c-common-init 'protobuf-mode)
  (easy-menu-add protobuf-menu)
  (c-run-mode-hooks 'prog-mode-hook 'c-mode-common-hook 'protobuf-mode-hook) ;; Add prog-mode-hook
  (c-update-modeline))
```

**Comment by Alex-David-Hu** [comment]
you must use windows system




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Simon Law"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 上午10:44
收件人:&nbsp;"protocolbuffers/protobuf"<protobuf@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[protocolbuffers/protobuf] protobuf-mode.el should derive from prog-mode (#7316)





 
What version of protobuf and what language are you using?
 Version: 0.3
 Language: Emacs
 
What operating system (Linux, Windows, ...) and version?
 N/A
 
What runtime / compiler are you using (e.g., python version or gcc version)
 N/A
 
What did you do?
 Steps to reproduce the behavior:
  
In Emacs, turn on protobuf-mode
 
M-x eval-expression RET (derived-mode-p 'prog-mode)
  
What did you expect to see
 prog-mode
 
What did you see instead?
 nil
 
Anything else we should know about your project / environment
 protobuf-mode is a major mode for a programming language, albeit a restricted one. In fact, it claims to be derived from CC Mode, which it actually isn’t.
 
That’s tangential though. In order to derive from prog-mode, the defun prog-mode at: https://github.com/protocolbuffers/protobuf/blob/4567a21004db641e974200f20715a2c9ab1f2378/editors/protobuf-mode.el#L195-L219 should instead read:
 ;;;###autoload (define-derived-mode protobuf-mode prog-mode "Protocol-Buffers"  ;; Replace defun with define-derived-mode   "Major mode for editing Protocol Buffers description language.  The hook `c-mode-common-hook' is run with no argument at mode initialization, then `protobuf-mode-hook'.  Key bindings: \\{protobuf-mode-map}"   (kill-all-local-variables) ;; Remove spurious interactive call   (set-syntax-table protobuf-mode-syntax-table)   (setq major-mode 'protobuf-mode         mode-name "Protocol-Buffers"         local-abbrev-table protobuf-mode-abbrev-table         abbrev-mode t)   (use-local-map protobuf-mode-map)   (c-initialize-cc-mode t)   (if (fboundp 'c-make-emacs-variables-local)       (c-make-emacs-variables-local))   (c-init-language-vars protobuf-mode)   (c-common-init 'protobuf-mode)   (easy-menu-add protobuf-menu)   (c-run-mode-hooks 'prog-mode-hook 'c-mode-common-hook 'protobuf-mode-hook) ;; Add prog-mode-hook   (c-update-modeline))

**Comment by canatella** [comment]
While we are at it, why does it run the c mode hook ? It is not C, it run the hook c-mode-common-hook which breaks my editing of protobuf files.

**Comment by sfllaw** [comment]
#9076 and #9572 have addressed this bug.
