### ISSUE TITLE
descriptor.proto missing from protobuf-javalite

### ISSUE THREAD

**Issue by ajasmin** [protocolbuffers/protobuf#7331]
Building an Android project with protobuf-gradle-plugin:0.8.12 and protobufJavaliteVersion:'3.11.4' fails if one of my proto files includes "google/protobuf/descriptor.proto".

Since the fixing of #1889, some proto files such as well-known-types are included in protobuf-javalite but descriptor.proto is still missing.

Even though the java-lite runtime doesn't make use of descriptors, it's possible to have cross-language projects that do.

**Comment by ejona86** [comment]
protobuf-javalite does not include any descriptor support. The earlier missing protos had their generated code available but were lacking the .proto definitions. protobuf-javalite does not even include generated code for descriptor.proto, on purpose. So it isn't a bug that descriptor.proto is missing, but rather a feature request to include generated code for descriptor.proto.

**Comment by robcos** [comment]
Is there a particular reason why the descriptor code is not there? If I remember correctly, it is there in the _nano_ libraries

**Comment by elharo** [comment]
For questions or troubleshooting, please see the protobuf mailing list: https://groups.google.com/forum/#!forum/protobuf or Stack Overflow https://stackoverflow.com/questions/tagged/protocol-buffers

We don't formally monitor stack overflow, but there are a lot of experienced developers there who also use protobuf.

**Comment by jhump** [comment]
@fowles, I meant to bring this up in our chat today. But it's probably minor enough that we can just discuss here in GitHub.

This issue was closed a while ago, but I can't really tell _why_. Is this something that could be added to the lite runtime? We're obviously not looking for real descriptor support (since the whole point of the lite runtime is to omit that in favor of smaller code size). But we do have cases where schemas transitively import `google/protobuf/descriptor.proto` (like an RPC response that includes `google.protobuf.FileDescriptorSet`) and then can't be used at all with the lite runtime: the generated code fails to compile because the classes for this import do not exist.

Would your team entertain the idea of re-opening this?

**Comment by fowles** [comment]
@googleberg can you take a look at this with fresh eyes and make a call?

**Comment by jhump** [comment]
Thanks, @fowles. It's been brought to my attention that `plugin.proto` is in the same boat. Though I can also understand that file being far less likely to appear in an API so maybe an odd thing to put in the Lite runtime. Maybe `descriptor.proto` and `plugin.proto` could be provided in a separate JAR/artifact?

We ran into this in generating Java lite APIs for [our own BSR APIs](https://buf.build/bufbuild/buf/docs/main:buf.alpha.registry.v1alpha1#buf.alpha.registry.v1alpha1.PluginGenerationResponse), for use with Connect Kotlin. Admittedly, an actual mobile client would almost certainly never call these particular endpoints. But they are in the same package as other endpoints. So to get this to generate valid, compiling code, it's much more involved to manually prune the set of protos prior to code generation. Anyhow, I understand if this is an odd request, particularly regarding `plugin.proto`. Our hope is that the request is reasonable since it reduces friction for users that happen to have proto definitions that look like this. And the fact that other users have run into this (i.e. the others that file and commented on this issue and #8697) suggests we're not the only ones.

At the moment, we have a work-around by providing Java-lite-generated code for these in [our own Maven artifact](https://search.maven.org/artifact/build.buf/protobuf-javalite/3.22.3.1/jar?eh=). But since the classes are all named `com.google...`, it's a little squirrelly that they are provided by a bufbuild artifact instead of a google artifact.

**Comment by googleberg** [comment]
While the idea of passing around descriptors in RPCs makes me a little queasy, it's already available to protobuf-core, so making it available in lite seems like a minor trasgression. Same for plugin.proto. I guess I'd rather we provide a single, official version than have several unofficial versions published.

**Comment by kenyee** [comment]
We're trying to use javalite and hitting the problem of com.google.protobuf.ProtocolMessageEnum not being available and I think it's also because Descriptors is missing since the interface uses them:
https://github.com/protocolbuffers/protobuf/blame/d111589bc05f0c11d9d2b0e230bc3217f24feb40/java/core/src/main/java/com/google/protobuf/ProtocolMessageEnum.java#L14

Is the only alternative to use the full proto-java?

**Comment by maikelvdh** [comment]
Is there a plan to release still Maven artifacts for lite packages (kotlin and java) in 3.x range context? In particularly interested in 3.27.x to be able to benefit from the fix for this issue.
