### ISSUE TITLE
C# Generated Files Difference In Versions

### ISSUE THREAD

**Issue by sudeephazra** [protocolbuffers/protobuf#7446]
**What version of protobuf and what language are you using?**
Version: 3.11.4
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Enterprise 64-bit 

**What runtime / compiler are you using (e.g., python version or gcc version)**
C# (Following the guide to create a deserializer for Azure https://docs.microsoft.com/en-us/azure/stream-analytics/custom-deserializer-examples)

**What did you do?**
1. Create a v3 proto file
2. Use the following command to generate the C# code file
```
protoc.exe --csharp_out=. sample_file.proto
```
3. The code file generated from protoc v3.7.x and v3.11.x differ by 2 "null" values as shown in the attachment. 

**What did you expect to see**
I expected to see the same file being generated from both versions of protoc
**What did you see instead?**
The code file generated from protoc v3.7.x and v3.11.x differ by 2 "null" values. These additional values caused the program to into an endless loop and thinking that the field terminator is not available in the binary file
![protobuf_version_difference](https://user-images.githubusercontent.com/642449/80716986-f2111000-8b15-11ea-927e-3508984f89a2.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**
I am planning to use it for a custom deserializer for Azure but the issue pops up even before I have started coding anything.

**Comment by jskeet** [comment]
Just a drive-by question: which version of Google.Protobuf are you using as a dependency? The difference is due to the support for proto2 - a new constructor overload has been added accepting extensions.
So long as you use Google.Protobuf 3.11.4, I'd expect the generated source code to work in both cases.

If you try using Google.Protobuf 3.7.x with source code generated by 3.11.x, I'd expect that to fail.

**Comment by sudeephazra** [comment]
I tried with v3.11 with the binary generated from the same version. The proto binary generated in both versions can be successfully deserialized using the code generated by 3.7 only. The C# code generated with 3.11 fails to process the binary even when the binary is created from 3.11.

**Comment by jskeet** [comment]
Please clarify what you mean by this:

> The C# code generated with 3.11 fails to process the binary even when the binary is created from 3.11.

What sort of failure?  What *exactly* does the code do? When you say "the binary" do you mean the binary *data* file, or the *executable* file? If you could provide a short but complete example that demonstrates the problem, that would make it a lot easier to help you.

**Comment by sudeephazra** [comment]
Regret the delay in responding

> The C# code generated with 3.11 fails to process the binary even when the binary is created from 3.11.

The final .NET deserializer as mentioned below throws out an error saying that the binary has "invalid end-of-file". The code just interprets the binary streaming data in Azure Streaming Analytics and stores it in a database.. 

> I tried with v3.11 with the binary generated from the same version. The proto binary generated in both versions can be successfully deserialized using the code generated by 3.7 only.

The binary here refers to the data file converted into binary using the proto executable.

> If you could provide a short but complete example that demonstrates the problem, that would make it a lot easier to help you.

I am basically trying to implement a step-by-step guide from Microsoft - https://docs.microsoft.com/en-us/azure/stream-analytics/custom-deserializer

**Comment by jskeet** [comment]
> The final .NET deserializer as mentioned below throws out an error saying that the binary has "invalid end-of-file"

So what *exactly* does that error look like? A full stack trace would be helpful here.

> I am basically trying to implement a step-by-step guide from Microsoft - https://docs.microsoft.com/en-us/azure/stream-analytics/custom-deserializer

Okay, so at what stage in that tutorial does it fail? Only when you put everything together? To be honest, with only that tutorial to go on, it's entirely possible that the problem is with the data produced by Azure. I'm not saying that *is* the case, but without a *complete* example, it's very, very hard to help diagnose this any further.

It seems very unlikely to me that this is a bug in Google.Protobuf or the generated code. Again, it's possible, but I'd be surprised.

I'll see if I can create a complete example based on the tutorial, but it would really help if we could separate out the Azure Analytics side of things.

**Comment by sudeephazra** [comment]
Thanks for the prompt response @jskeet 

The error was encountered in a client code deployment and due to compliance constraints, I will not be able to share the exact code. I will put something down on similar lines to help you replicate the issue and update this thread in a day or two.

**Comment by jskeet** [comment]
I've just run through the Azure tutorial, and everything just worked first time, using Google.Protobuf version 3.12.3. I'll wait to hear more information when you get a chance to put together a repro.

**Comment by jskeet** [comment]
Any more information on this?

**Comment by sudeephazra** [comment]
Please feel free to close the issue. We are not pursuing this solution anymore. Appreciate your promptness in responding to the queries. :)
