### ISSUE TITLE
3.12.3 might be wrongly tagged - created from master branch? (C#-release package lose IBufferMessage.cs)

### ISSUE THREAD

**Issue by IllusionCui** [protocolbuffers/protobuf#7637]
3.12.3-C#-release package lose IBufferMessage.cs
3.12.3-source-release package contains IBufferMessage.cs

**Comment by anandolee** [comment]
Jan, can you help to take a look?

**Comment by jtattermusch** [comment]
The 3.12.3 tag indeed contains 
https://github.com/protocolbuffers/protobuf/commits/v3.12.3/csharp/src/Google.Protobuf/IBufferMessage.cs
from this PR
https://github.com/protocolbuffers/protobuf/pull/7351

That is odd because to my knowledge https://github.com/protocolbuffers/protobuf/pull/7351 should only be present in the master branch and it should not be available in any of the releases yet.

@haberman  was the 3.12.3 tag was created wrong (maybe it was tagged off of master branch, not off of 3.12.x branch?)

See history of the release branch vs the history of the tag - they look suspiciously different?
https://github.com/protocolbuffers/protobuf/commits/3.12.x
https://github.com/protocolbuffers/protobuf/commits/v3.12.3

@haberman  can you please take a look?

**Comment by jtattermusch** [comment]
Btw, the 3.12.3 release subtitle says "· 25 commits to master since this release", which also seems to indicate the tag was created off of master branch (other releases say "N commits to 3.x.x since this release"). If the protobuf tags are created manually (same case as with grpc), this is easy to miss because there's just a small dropdown to select the source branch when creating a release.

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.3

**Comment by kevinburkemeter** [comment]
Hi @anandolee, @jtattermusch, do you have an update by any chance? The 3.12.3 release was tagged incorrectly. This is causing major pain for users of the library; see the number of commits tagged to this issue and #7632 that describe reverting and/or pinning to 3.12.2. This situation has persisted for over a month now.

There is a fairly simple solution: create a 3.12.4 Git tag, and upload a new release, even if the contents are identical to 3.12.3.

Is there a chance you could make time to perform that release this week?

**Comment by rozbo** [comment]
+1 
 major pain

**Comment by jtattermusch** [comment]
@dlj-NaN

**Comment by acozzette** [comment]
The 3.12.4 release is now done.
