### ISSUE TITLE
Generated Python protobuffers allow synthetic oneofs in HasField/ClearField/WhichOneof

### ISSUE THREAD

**Issue by henribru** [protocolbuffers/protobuf#7919]
**What version of protobuf and what language are you using?**
Version: master/v3.6.0/v3.5.0 etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript
3.13.0
**What operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04
**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.8
**What did you do?**
1. Compile a proto3 file with optional fields
2. Create an instance of that protobuffer
3. Use the name of the synthetic oneof (i.e. an underscore followed by the name of the field) in `HasField`/`ClearField`/`WhichOneof`

You can see an example of this with `WhichOneof` in a test case: https://github.com/protocolbuffers/protobuf/blob/b7742c51fdfa2f31f6a5f341f6d0b0df586b4ef1/python/google/protobuf/internal/message_test.py#L1716

**What did you expect to see**
The same errors you get when using non-existing fields with these methods. According to https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md#updating-a-code-generator, there shouldn't be accessors for synthetic oneofs.
**What did you see instead?**
It behaves the same way as a regular oneof

**Comment by acozzette** [comment]
Thank you for the bug report, but I think it was actually a deliberate decision to allow `WhichOneof` to work with synthetic oneofs, since it is a quasi-reflective API. Reflection-based logic that doesn't know about proto3 optional fields should still be able to call `WhichOneof` on a synthetic oneof in order to work correctly. @haberman knows more about this and can correct me if I'm wrong.
