### ISSUE TITLE
iOS 8.0 deployment target is no longer supported in Xcode 12

### ISSUE THREAD

**Issue by tinder-owenthomas** [protocolbuffers/protobuf#8007]
**What language does this apply to?**
Swift

**Describe the problem you are trying to solve.**
The latest stable release version is no longer supported on the latest Xcode as it still targets an outdated iOS 8 deployment target. 

**Describe the solution you'd like**
The solution has already been merged but has not been released. Is there a timeline on releasing 4.0.0?

**Describe alternatives you've considered**
Upgrading to the RC2 version of 4.0.0, but we prefer not to use beta software in our production app. Also, RC2 isn't available in Cocoapods for some reason so we cannot upgrade to it.

**Comment by acozzette** [comment]
4.0.0rc2 is actually not the most recent. Sorry for the confusion but we ended up changing our mind on the version number and continued with the 3.x releases instead of going to 4.0. 3.13 is the most current release and I am now working on 3.14.0. However, I don't know anything about the iOS issue. @thomasvl Do you know what is going on with that? If there is a fix then I can try to make sure it gets into 3.14.0.

**Comment by thomasvl** [comment]
#8021 will update the podspec, you just need to include that change in making the release.

**Comment by thomasvl** [comment]
That PR is in (also needed a second commit to fix up some integration tests for cocoapods).

**Comment by acozzette** [comment]
Thanks @thomasvl, I created #8023 to cherry-pick that fix into 3.14.x.
