### ISSUE TITLE
Noisy warnings are printed

### ISSUE THREAD

**Issue by PierrickVoulet** [protocolbuffers/protobuf#8124]
**What version of protobuf and what language are you using?**

Version: 3.14.0, C implementation
Language: PHP 7.2, PHP 7.3 , PHP 7.4

**What operating system (Linux, Windows, ...) and version?**
Linux 64

**What did you do?**

Run any script that uses the library (e.g. [PHPUnit tests](https://travis-ci.org/github/googleads/google-ads-php/jobs/747633837))

**What did you expect to see**

No  `WARNING: file was already added`

**What did you see instead?**

Several `WARNING: file was already added`

**Comment by witchakorn1999** [comment]
> @blowmage

**Comment by gmatkowski** [comment]
Yes i have a same issue which prevents me from running test :-(

**Comment by haberman** [comment]
I was able to reproduce this, thanks to help from @PierrickVoulet.

This warning was due to the same proto descriptor being loaded twice. I believe this was due to it being included in multiple aggregated metadata bundles.

The warning message was very unhelpful, which made it very difficult to track down the root cause. I've fixed it to include the name of the file that was being loaded a second time, and where it is being loaded from.

This change is in https://github.com/protocolbuffers/protobuf/pull/8276.
