### ISSUE TITLE
C# WCF : Protocol buffer object gets modified when its transported using WCF(Has... fields)

### ISSUE THREAD

**Issue by maheshsanthamoorthy** [protocolbuffers/protobuf#8166]
**What version of protobuf and what language are you using?**
Version: v3.14.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763

**What runtime / compiler are you using (e.g., python version or gcc version)**
Visual Studio 2019

**What did you do?**
1. Create a simple server and client which communicates using WCF.
2. Expose a simple operation contract which returns a protocol buffer based object.
3. While returning the proto buff object to client set few props and do not set other props.
4. In the client you can see that all the props which were not set by the server is set to default value which is fine, but the Has... fields are set to true while received in the client but these were false before sending to client in the service.

**What did you expect to see**
I expect to see the same value in the Has... fields in the server and client side.

**What did you see instead?**
I see that the value of the Has... fields is set to true in the client side for the props which were not set in the server side.

**Sample Proto File**
_syntax = "proto2";
package TestProto;

message ErrorDetail
{
	required int32 s32_errorId = 1;
	optional int32 s32_errorNo = 2;
}_

**Comment by jskeet** [comment]
Closing this as obsolete - it was reported over 18 months ago, and we don't have enough detail to actually reproduce the issue.

If the bug is in Google.Protobuf, I'd expect it to be demonstrable without WCF getting involved. @maheshsanthamoorthy if you're able to reproduce it in a minimal example, I'm happy to have a look - please add a comment and I can reopen the issue.
