### ISSUE TITLE
[csharp] Allow for unsealed message output to be generated

### ISSUE THREAD

**Issue by mwpowellhtx** [protocolbuffers/protobuf#8169]
Hello, based on experience working with Google.OrTools, I have a couple of instances where I want to adapt `RoutingModelParameters` and `RoutingSearchParameters` for configuration purposes with a _CSharp_ wrapper framework, and it would be incredibly useful for the message to not be `sealed` when they land opposite the `protoc` invocation. i.e. that is, they land as:

```C#
public sealed class RoutingModelParameters
{
}
```

And:

```C#
public sealed class RoutingSearchParameters
{
}
```

Respectively.

I can workaround the limitation, somewhat; but the effort would be reduced significantly, I think, by perhaps 75-85% with unsealed classes.

Is this an option in the `protoc` compiler as it stands today? Or can it be implemented without much difficulty?

Thank you...

**Comment by jskeet** [comment]
We try to keep the number of protoc options pretty small - I would definitely prefer not to do this. I would suggest that a practical solution to this would be to post-process the generated classes if you really want to. (It shouldn't be terribly hard to do so; the generated output is very predictable.)

@fowles are you happy for this to be closed, or do you think it should be kept open and considered more internally?

**Comment by mwpowellhtx** [comment]
@jskeet Well, that's kind of the point, isn't it? The code is _*GENERATED*_, so best practice suggests you don't want to go mucking around in that code. But if you can extend it, _or even augment it_, i.e. it was `partial`, that might be another thing entirely, correct? Anyway, I let experience be my guide there. I know it is best practice, experientially.

**Comment by jskeet** [comment]
> But if you can extend it, or even augment it, i.e. it was partial, that might be another thing entirely, correct?

It *is* partial. That's my point. You don't need to extend the class in order to augment it.

And yes, I agree that all other things being equal, it's best not to have to modify generated code - but all other things *aren't* equal here, as providing the option to generate unsealed classes introduces not only complexity in terms of more options, but also in terms of working out how inheritance affects every other aspect of protobuf. (When one message contains a field of another message type, how would deserialization know whether to create an instance of the base type or some derived type? If you only ever end up with instances of the base type when you want derived types, that introduces yet more complexity.)

**Comment by mwpowellhtx** [comment]
It is `partial`? It's been a bit since I last reviewed the generated code...

Well, in terms of serialization, usually you do that with explicit knowledge of the thing you want to deserialize, i.e. its type; i.e.

```csharp
class A {}
class B : A {}
```

If you serialized `A`, then you want `A` back in response. But if you serialized `B`, then you get `B` back in response; which also happens to be an `A`, but you had the forward type information, i.e.

```csharp
sender.Send<A>(a); // generic type for illustration purposes
// ...
receiver.Get<A>();
```

Now if somehow you are throwing _data shapes_ around without said forward knowledge, that's another thing entirely, i.e. hoping against hope that both sides have a message that agrees with that shape, but I do not know that is the case when we are discussing messaging frameworks such as this one. AFAIK, usually you know the type information of the payload involved at design time. Usually. Either of which is perfectly fine, if that was the dev's intention; neither of which is that offensive or mutually exclusive of one another, i.e. if you wanted `A` or `B`.

What else am I missing here?

**Comment by jskeet** [comment]
Yes, we've generated partial classes forever as far as I remember (even in my previous proto2 implementation).

I very specifically called out the case where one message contains a field of another message type, because that's where the caller *doesn't* specify the type. For example:

```proto
message Outer {
    Inner inner = 1;
}

message Inner {
    int32 x = 1;
}
```

```csharp
var outer = new OuterDerived
{
    Inner = new InnerDerived { X = 1 }
};
```

Protobuf has no notion of inheritance, so while it could (potentially) be fine to serialize and deserialize as:

```csharp
var bytes = outer.ToByteArray();
OuterDerived parsed = OuterDerived.Parser.ParseFrom(bytes);
```

... what would the execution-time type of `parsed.Inner` be? There's no standard way to serialize the additional information that you'd want it to be deserialized as an `InnerDerived`.

This is the sort of complexity that is completely side-stepped by sealing the classes - there's just no question of which type to deserialize as.

**Comment by mwpowellhtx** [comment]
Not as far as I can remember, or I would not have posted; i.e. the code I found generated was just that. It seemed a bit strange they were `sealed` and not `partial` as is sometimes the case with generated code like this, like we've discussed. Anyway, good to know, thank you, from a _Protobuf_ perspective.

**Comment by jskeet** [comment]
We've never generated code exactly like that - aside from anything else, all our message types implement `IMessage<T>`. I don't know which generator you were using, but protoc definitely generates partial classes unconditionally. See https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/csharp/csharp_message.cc#L125

If you think you may have been using a different generator, it's probably worth finding out which - because it could be that *that* generator's maintainers would be willing to support unsealed classes (or may indeed support them now). If you're sure you were using protoc, I'd ask you to have another look at the generated code. If you've really got a way of generating non-partial classes, that's a bug and I'd like to fix it.

**Comment by mwpowellhtx** [comment]
Possible? I don't recall hundred percent. It was in the context of _Google.OrTools_, IIRC. In that context, last time I checked they were also leveraging `Protobufs v2`, and not `v3+`, which was a whole other can of worms, to be honest. At the time, I didn't seem to think there was much of any customization of the generators involved, but I could be wrong. Anyway, thanks for the response.
