### ISSUE TITLE
proto3_optional allows optional keyword for extensions and produces incorrect descriptor

### ISSUE THREAD

**Issue by jhump** [protocolbuffers/protobuf#8234]
**What version of protobuf and what language are you using?**
Version: 3.14.0

**What operating system (Linux, Windows, ...) and version?**
OS X

**What did you do?**
1. Create a source file as follows named `test.proto`:
    ```proto
    syntax = "proto3";

    import "google/protobuf/descriptor.proto";

    extend google.protobuf.MessageOptions {
      optional string foo = 50001;
    }
    ```
2. Compile with protoc:
    ```
    protoc -I . --experimental_allow_proto3_optional -o test.protoset test.proto
    ```

**What did you expect to see**
I expected the compilation to fail since optional is historically disallowed in syntax "proto3" for extensions. And it does not make sense to allow it as "proto3 optional" since that implies that the field goes into a oneof, which is not supported for extensions.

**What did you see instead?**
The compile succeeded.

I inspected the descriptor with this command:
```
protoc --decode google.protobuf.FileDescriptorSet google/protobuf/descriptor.proto < test.protoset 
```

This showed the following output from the compiler:
```
file {
  name: "test.proto"
  dependency: "google/protobuf/descriptor.proto"
  extension {
    name: "foo"
    extendee: ".google.protobuf.MessageOptions"
    number: 50001
    label: LABEL_OPTIONAL
    type: TYPE_STRING
    json_name: "foo"
    proto3_optional: true
  }
  syntax: "proto3"
}
```

Not only did compilation succeed, but `protoc` even marked the extension with `proto3_optional: true`, which must be a bug since a proto3 optional will implicitly exist in a single-field oneof (which this extension clearly does not and, in fact, cannot).

**Comment by haberman** [comment]
Great catch. Extensions should be effectively always `optional`, and we should definitely not be putting extensions into a synthetic oneof.

**Comment by rauanmayemir** [comment]
Oh my, that will be unfortunate.

I thought proto3 optional is just a matter of field presence and internal usefulness when proto reflect would give explicit presence information instead of defaulting to empty values.

Without synthetic oneof there will be no way of understanding which field options were set (especially when I do want to set it to the default value).

**Comment by rauanmayemir** [comment]
> Extensions should be effectively always optional, and we should definitely not be putting extensions into a synthetic oneof.

@haberman Oh, wait. Does that mean proto reflect will give correct information about the presence of the extension?

**Comment by haberman** [comment]
I can't speak to proto reflect. In protobuf extensions inherently have presence, eg. you can always call `msg.HasExtension(foo_extension)` and get a meaningful answer, even if the extension was defined in a proto3 file.

**Comment by jhump** [comment]
IIUC, in all runtimes that support proto2, all fields in a proto2 message provide explicit presence information (unlike proto3). Furthermore, all extendable messages are proto2 messages (while you can define extensions in proto3, the extended message can only be defined in proto2). So it follows that all extensions behave the desired way and that the `proto3_optional` element on the field descriptor should always be false.

@haberman, I think I could put up a PR to fix this. But before doing so, I wonder what you think the fix looks like. My personal opinion is that the `optional` keyword should simply be disallowed for extensions in proto3 files, since it could be confusing that fields labeled thusly are different than normal fields with that label (since normal fields will be `proto3_optional`).

But an alternate "fix" would be to allow the keyword but effectively ignore it -- or rather treat is as if in a proto2 source file. So it's a normal optional field (not `proto3_optional`), just as if the label were absent (with maybe the only observable difference being that source code info could include a source location for the label).

**Comment by haberman** [comment]
> and that the proto3_optional element on the field descriptor should always be false

I agree with all of your analysis up to here. But it's not clear to me that this point follows from the rest.

In an ideal world, we would have required that all extensions defined in a proto3 file explicitly specify `optional` or `repeated`, because as you note, the proto3 "singular field" semantic does not exist for proto2 messages or their extensions.

However that did not happen, and it would be a breaking change to enforce it now. So we have to live with extensions in proto3 files that are declared without any label, and know that they behave as if `optional` had been written.

Now that `optional` is supported in proto3, it seems we should allow it in extensions, because otherwise extensions in proto3 would be inconsistent with everything else (this is from a pure language level, not considering the descriptor). The true semantics of extensions in proto3 are `optional`, so we should let users write the keyword there in a way that matches proto2 and other proto3 optional fields.

When it comes to the descriptor, it can be useful to know if the `.proto` file did actually contain the `optional` keyword. And there is a method on `FieldDescriptor` for checking this: [FileDescriptor::has_optional_keyword()](https://github.com/protocolbuffers/protobuf/blob/a530dbe50c8295bf7b19e245b9be8525e235e6cb/src/google/protobuf/descriptor.h#L704-L706). Ideally this method will work even for extensions in a proto3 file, otherwise the semantic of that method becomes more complicated. The method could be useful for eg. implementing a linter that suggests that an explicit `optional` be added to bare extensions in a proto3 file.

For these reasons, I would advocate that:

1. We allow, but do not require, the `optional` keyword on extensions declared in a proto3 file.
2. We set the `FieldDescriptorProto.proto3_optional` field for extensions with an explicit `optional` keyword in proto3. This gives a signal that [FileDescriptor::has_optional_keyword()](https://github.com/protocolbuffers/protobuf/blob/a530dbe50c8295bf7b19e245b9be8525e235e6cb/src/google/protobuf/descriptor.h#L704-L706) can use to return the right answer.
3. We clarify the documentation to specify that synthetic oneofs are are only required when `proto3_optional` appears on a regular field, *not* for extensions. In practice this is the behavior that is already implemented.

(1) and (2) are the behavior that is already implemented. So I think this may end up being a documentation change only.

**Comment by jhump** [comment]
@haberman if you mean to suggest that extensions _should_ allow the `optional` keyword in proto3 (now, thanks to proto3 optional support) and that the generated descriptor _should_ have the `proto3_optional` flag set to true, then I guess there is nothing to be done here... except perhaps document the expectations more clearly? The doc I had read lead me to believe that `proto3_optional` means the field will have a synthetic oneof, which clearly isn't the case with an extension.

Maybe we should close this issue?

**Comment by perezd** [comment]
@haberman is there more to do here?

**Comment by haberman** [comment]
I think this bug requires no further action.
