### ISSUE TITLE
Deprecation warnings when compiling on JDK > 9: Integer(int) in Integer has been deprecated and marked for removal

### ISSUE THREAD

**Issue by cushon** [protocolbuffers/protobuf#8449]
The use of `new Integer(int)` [here](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/Descriptors.java#L1761-L1763) is deprecated in JDK 9 and marked for removal, see [Deprecation of Boxed Primitive Constructors](https://www.oracle.com/java/technologies/javase/9-deprecated-features.html#JDK-8065614).

```
        // Note: We must use "new Integer(number)" here because we don't want
        // these Integer objects to be cached.
        Integer key = new Integer(number);
```

```
java/core/src/main/java/com/google/protobuf/Descriptors.java:1763: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
        Integer key = new Integer(number);
                      ^
```

**Comment by elharo** [comment]
Deprecated yes. Scheduled for removal? I'm not so sure.

It's uncommon but in this and many other cases the use of the constructor is deliberate and we do want new and different Integer objects. I don't think Oracle can remove this without breaking too much existing code.

 We should probably just suppress the warning. Otherwise we could use the string constructor that also returns a new instance: "With the exception of Character, the box classes also have constructors that take a String argument. These parse and convert the string value and return a new instance of the box class. A valueOf overload taking a String is the equivalent static factory method for this constructor."

**Comment by elharo** [comment]
I no longer see this code. I assume it got removed at some point, possibly as a result of other changes.
