### ISSUE TITLE
Ruby `.decode_json` behavior change for oneof fields in 3.15.0

### ISSUE THREAD

**Issue by ob-stripe** [protocolbuffers/protobuf#8464]
**What version of protobuf and what language are you using?**
Version: v3.15.0
Language: Ruby

**What operating system (Linux, Windows, ...) and version?**
macOS Catalina 10.15.7

**What runtime / compiler are you using (e.g., python version or gcc version)**
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**What did you do?**
Run the following Ruby script:
```ruby
require "google/protobuf"
require "json"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("foo.proto", :syntax => :proto3) do
    add_message "Foo" do
      oneof :details do
        optional :bar, :string, 1
        optional :baz, :string, 2
      end
    end
  end
end

Foo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Foo").msgclass

p Foo.new(bar: 'hello')
p Foo.new(bar: 'hello', baz: nil)
p Foo.decode_json({bar: 'hello'}.to_json)
p Foo.decode_json({bar: 'hello', baz: nil}.to_json)
```

**What did you expect to see**
With google-protobuf 3.14.0, the script returns:
```
<Foo: bar: "hello", baz: "">
<Foo: bar: "hello", baz: "">
<Foo: bar: "hello", baz: "">
<Foo: bar: "hello", baz: "">
```

**What did you see instead?**
With google-protobuf 3.15.0, the script returns:
```
<Foo: bar: "hello">
<Foo: bar: "hello">
<Foo: bar: "hello">
Traceback (most recent call last):
	1: from test.rb:20:in `<main>'
test.rb:20:in `decode_json': Error occurred during parsing: Error parsing JSON @1:21: More than one field for this oneof. (Google::Protobuf::ParseError)
```

The new behavior is arguably more correct, but it is sort of a breaking change :/

@haberman Curious to hear what you think about this. It seems like `.decode_json` now distinguishes between "absent" and "present but nil" for oneof fields, and raises an exception in the latter case.

**Anything else we should know about your project / environment**
N/A

**Comment by haberman** [comment]
Hi @ob-stripe,

Sorry for the trouble. 3.15 did indeed move onto a new JSON parser that is more spec compliant than the parser used previously.

This is an interesting case. The spec and our conformance tests do clearly say that we must reject JSON if multiple oneof fields are set, see: https://github.com/protocolbuffers/protobuf/blob/0ef575beff5a627a4a1e8e15e462039d3aed2ad3/conformance/binary_json_conformance_suite.cc#L2329-L2331

However it's less clear whether this applies if one of the fields is `null`. In protobuf JSON `null` doesn't clear the field, it just means "default." So this is a grey area that the spec doesn't specifically cover.

Let me write a quick test to see what the other languages do for this case. We try to make sure that every language accepts/rejects the same things. If other languages accept this, we should definitely make Ruby accept it also. If other languages are rejecting it, it would be harder to change, since we would need to change all languages accordingly.

**Comment by ob-stripe** [comment]
Makes sense! Thanks for looking into it.

**Comment by ob-stripe** [comment]
@haberman Sorry for the ping, but have you had a chance to compare the behavior with other languages?

**Comment by haberman** [comment]
Hi @ob-stripe, sorry for the delay. I was able to try this and Java and C++ both allow this. So I think we should allow it in Ruby too.

**Comment by ob-stripe** [comment]
Hi @haberman, no worries and thanks for looking into this! Is there anything I can do help fixing this? I took a peek at the C extension code that throws the error: https://github.com/protocolbuffers/protobuf/blob/069f989b483e63005f87ab309de130677718bbec/ruby/ext/google/protobuf_c/ruby-upb.c#L7649-L7652
and I wonder simply moving the null check below: https://github.com/protocolbuffers/protobuf/blob/069f989b483e63005f87ab309de130677718bbec/ruby/ext/google/protobuf_c/ruby-upb.c#L7654-L7658
so that it happens before would be enough to fix the issue.

**Comment by haberman** [comment]
@ob-stripe, yes indeed, that code comes from here so I submitted a PR there first: https://github.com/protocolbuffers/upb/pull/387

**Comment by ob-stripe** [comment]
Wonderful! Thanks for the quick fix. We're eager to update to 3.15 :)

**Comment by ob-stripe** [comment]
@haberman Sorry to bother you again, but do you have a timeline for releasing this fix?

**Comment by haberman** [comment]
@ob-stripe Sorry for the delay, I have been prioritizing the PHP memory leak in https://github.com/protocolbuffers/protobuf/issues/8525

This will release somewhere in the 3.17 series, I expect within the next two weeks or so.

**Comment by ob-stripe** [comment]
Thanks for the update!
