### ISSUE TITLE
No documentation on the text representation format

### ISSUE THREAD

**Issue by davidgiven** [protocolbuffers/protobuf#8636]
There is no (that I can find) documentation on the syntax of the text protobuf format on the developer site (https://developers.google.com/protocol-buffers). As working with text files is one of the main ways in which end users will interact with them when protobufs are being used for, e.g, configuration files, it'd be good to go into some detail about this; I'd expect there to be a document similar to https://developers.google.com/protocol-buffers/docs/reference/proto2-spec describing the precise syntax. A more human-readable reference describing things like comment characters, continuation characters, string escapes etc would also be nice.

See also https://stackoverflow.com/questions/18873924/what-does-the-protobuf-text-format-look-like.

**Comment by fowles** [comment]
You are sadly correct that this is missing a formal specification.

**Comment by jvolkman** [comment]
@fowles what about go/textformat-spec? I'm not at G anymore, but I assume it or a derivative still exists (I was the original author). Can it be released? 

Not only is text format useful on its own, it's also a subset of the .proto language in the form of custom options. People working on .proto tooling are often unaware of the full scope of these options (e.g., https://github.com/devkanro/intellij-protobuf-plugin/issues/25)

**Comment by qa-swaneet-sahoo** [comment]
I would also love to have this documented officially.

The benefit of the text format is it's 1:1 correspondence with the wire-format - whereas JSON has quite a few implicit conversions the user needs to know about (for instance timestamp.proto).

For my open source project [protocurl](https://github.com/qaware/protocurl), I made a [bare minimum documentation](https://github.com/qaware/protocurl#protobuf-text-format, as otherwise users could not use the simpler text format there. From my own user experience with it, the text format does offer some level of easier usage in contrast to JSON.

Is there need or a wish for support here, since there was no progress in the past year on this?

**Comment by fowles** [comment]
David is working on this.  It turns out that our documentation needed a lot of love and this is part of the overall effort he is leading to improve it.

**Comment by acozzette** [comment]
We now have a text format spec here: https://developers.google.com/protocol-buffers/docs/text-format-spec It may not be perfect but should be fairly close.
