### ISSUE TITLE
Improve Kotlin Builder DSL

### ISSUE THREAD

**Issue by bjoernmayer** [protocolbuffers/protobuf#8708]
Heyho,

IMO the Kotlin Builder DSL can be improved.

Imagine this proto:
```proto
message Parent {
    repeated Child children = 1;
    Car car = 2;
}

message Child {
    string name = 1;
}

message Car {
    string brand = 1;
}
```

In the current form the Kotlin builder for this would look like this:
```kotlin
parent {
    children.add(
        child {
            name = "Rick Astley"
        }
    )

    car = car {
        brand = "Tesla"
    }
}
```

IMO this could be reduced to 
```kotlin
parent {
    addChildren {
        name = "Rick Astley"
    }

    car {
        brand = "Tesla"
    }
}
```

Basically you would need to provide shortcuts to access the current builder Dsl.

The inspiration for this request:
https://kroto-plus.readme.io/docs/protobuf-message-dsl

**Comment by lowasser** [comment]
This was deliberately left out of the API.  Here's why: imagine those three protos were defined in three separate .proto files in three separate projects/compilation units/BUILD targets, whatever.  So `parent.proto` depends on `child.proto` and `car.proto`.

What happens if `car.proto` does not have a Kotlin DSL generated for it?  The compilation of `parent.proto` can't even necessarily _tell_ that `car.proto` doesn't have a Kotlin DSL.  Maybe `Car` is defined in a Java-only dependency library that `Parent` is using.  We specifically want to support that use case, where not all your proto dependencies have opted into Kotlin code generation.

We could maybe support this feature if the messages _are_ defined in the same proto file, but that seems likely to lead to chaos if there's a later refactoring.  At least with `option java_multiple_files = true`, pulling a proto message out to its own file is currently a safe change, and this would make that no longer a safe change.
