### ISSUE TITLE
SourceCodeInfo in Java generated code descriptor

### ISSUE THREAD

**Issue by augi** [protocolbuffers/protobuf#8728]
**What language does this apply to?**
Java, but maybe it could be applied also to others.

**Describe the problem you are trying to solve.**
We are using gRPC and [Reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md), for example with [grpcurl](https://github.com/fullstorydev/grpcurl) and [grpcui](https://github.com/fullstorydev/grpcurl) tools, and more. Unfortunately, if we get descriptors from the Reflection endpoint exposed by a Java gRPC service, the returned descriptors don't contain _source code info_ (we would like to read comments).

Also, see [this issue](https://github.com/fullstorydev/grpcui/issues/50) that there is another use-case that requires having the _source code info_ included in the descriptors.

**Describe the solution you'd like**
There is a new `include_source_code_info` (intentionally the same name as existing `protoc` switch) `opt` for `java` plugin. Default value is `false`. If set to `true`, the generated code contains _source code info_ in the `descriptorData` field (as generated [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/java/java_shared_code_generator.cc#L136)).
Consider a similar solution for other built-in plugins.

**Describe alternatives you've considered**
[scalapb](https://scalapb.github.io/docs/customizations) offers `retain_source_code_info` that works like a charm. We are able to get also comments from the Reflection endpoint exposed by a ScalaPB-base application. But this is not usable for pure Java projects.

**Additional context**
The `descriptorData` field is printed [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/java/java_shared_code_generator.cc#L136). Hopefully, it could be as easy as the current code for exporting protosets with _source code info_, see [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc#L2500). So just `file_->CopySourceCodeInfoTo(&file_proto);`

For Python, exactly the same change would be required [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/python/python_generator.cc#L336).

**Comment by perezd** [comment]
If you turn this flag on when calling protoc directly do you get what you'd expect from Java generated code? I'm having a hard time discerning if this is a grpc-java issue or a java proto generator issue.

**Comment by perezd** [comment]
cc'ing @ejona86 for their opinion here as well.

**Comment by augi** [comment]
> If you turn this flag on when calling protoc directly do you get what you'd expect from Java generated code? I'm having a hard time discerning if this is a grpc-java issue or a java proto generator issue.

Yes, I tried to enable that flag but the serialized descriptor in Java generated code still didn't contain comments. The descriptor exported to a new file did contain the comments. 
That is exactly what I expected after I read the source code.

The change is definitely required in the Java generator but you're right that maybe it requires the same change also in the gRPC Java generator. I expected that it just reuse the descriptors from Java generated code so I didn't check it.

**Comment by ejona86** [comment]
I think this is mostly a protobuf issue as grpc-java just dumps whatever Descriptors protobuf has available.

I guess dsc files already contain the comments, since that is needed by code generators already. I'm normally strongly against codegen options because they "fork" the ecosystem. _Maybe_ this could be okay, but it isn't clear. Protos owned by the project using them are mostly okay, but I do think there would be tension for projects pulled in transitively to 1) be small and 2) include comments, which are contradictory. It might also cause trouble if you want comments to manage your backends but you ship a (non-mobile) fat client to customers and you _don't_ want comments included; there's no real way to manage that. Really, for _any_ client this would just be "code bloat."

**Comment by perezd** [comment]
Yeah, I'm inclined to agree with @ejona86 here, I don't think this is something that we'd generally want to provide/endorse, this is already accessible through `--descriptor_set_out` and `--include_source_info` at compile time, and baking this into generated code would rarely be a good practice.

**Comment by augi** [comment]
> I think this is mostly a protobuf issue as grpc-java just dumps whatever Descriptors protobuf has available.

Can confirm this, the `descriptorData` field is in the code produced by Java Protobuf plugin only. The gRPC plugin generated code just _ships_ it via Reflection API.

> I guess dsc files already contain the comments, since that is needed by code generators already.

Yes, if you use `--descriptor_set_out` and also `--include_source_info` switches then the _exported_ descriptors contain the comments. And the _source code info_ is IMHO sent to all the plugins (for example plugins for documentation generating rely on this).

> I'm normally strongly against codegen options because they "fork" the ecosystem. _Maybe_ this could be okay, but it isn't clear. Protos owned by the project using them are mostly okay, but I do think there would be tension for projects pulled in transitively to 1) be small and 2) include comments, which are contradictory. It might also cause trouble if you want comments to manage your backends but you ship a (non-mobile) fat client to customers and you _don't_ want comments included; there's no real way to manage that. Really, for _any_ client this would just be "code bloat."

I absolutely agree that codegen-specific options could "fork" the ecosystem but it seems that it could be trivial to add support for this option to all the built-in generators, or even introduce it as a new `protoc` switch.

Speaking about fat clients. My idea was that I would use the new option only when generating code for server implementation. When building a fat client to distribute, I wouldn't enable that option, because the generated code already contains the comments.

**Comment by augi** [comment]
Thank you all for your feedback and time! 🙏 

I feel that I didn't explain the motivation and potential use-cases thoroughly. Generally speaking, I see the Reflection API as a **machine-readable live documentation of the service**. This is the main reason why I think it makes sense to have comments included in this API, and the only missing piece to make it happen is to **allow** not to strip source code info from the descriptors in the generated code.

It would enable the following use-cases:
* [grpcui](https://github.com/fullstorydev/grpcui) (or other [UIs](https://github.com/grpc-ecosystem/awesome-grpc#gui) using Reflection API) could render the comments. This would be very useful when exploring a new API.
* Reflection API is sufficient for on-fly proxies (without seeing the original proto files). With the comments included, we would be able to generate also full-featured documentation on-fly. Now, as the comments are available in the protos only, the server implementor is responsible for documentation generating. So each consumer could generate the documentation how they want, not relying on the server implementor.

So I believe this feature could be vital for the gRPC community 🙏

**Comment by ejona86** [comment]
> I absolutely agree that codegen-specific options could "fork" the ecosystem but it seems that it could be trivial to add support for this option to all the built-in generators, or even introduce it as a new protoc switch.

I'm not concerned about "forking" the codegen options. I'm concerned about forking _which options are used_ between different usages. In many languages you _must not_ include the generated code for a proto twice in your binary, otherwise you get runtime failures. The only manageable solution to that is to have "canonical" generated code for each proto. The moment you have two pieces of generated code for the same proto you now put a rift in the ecosystem as you must ensure that both copies are not both present _anywhere_ in the dependency tree.

> Speaking about fat clients. My idea was that I would use the new option only when generating code for server implementation. When building a fat client to distribute, I wouldn't enable that option, because the generated code already contains the comments.

That can mostly work for 1st party protos. But it fails horribly for protobuf-using libraries. You can say, "oh, we don't care about that case," but should protobuf itself use the include_source_code_info option for well-known protos?

> It would enable the following use-cases:

I see the value in grpcui and other human-poking-at-running-server usages. I do think it would be really neat, so the problem isn't "is it useful?" The problem is, "how can the person generating the code make a decision about including the docs, since the same generated code is used for multiple contrary purposes?"

Passing options to plugins used to be much more common, but then we learned the hard way that it produces untold pain. We then swapped to including options in the .proto itself as it guarantees the generated code is built consistently. But this documentation use-case doesn't fit well into the options-in-the-proto framework, as some users want it and some don't. We've certainly seen cases like that before, but we either 1) killed the feature, 2) turned it on for everyone, or 3) figured out an alternative. The solution was not "use a protoc plugin option."

**Comment by jhump** [comment]
One option I am considering is to create a separate, custom plugin that _only_ emits the source info, in a way that is linked into the target library (similar to how the primary plugins link in the descriptors). My concrete case is Go, but the approach described below could be extended to other languages.

With this feature _not_ existing in the core runtimes, it means I will have to write a separate runtime API to re-hydrate the descriptors. This API will be used to load the source info, registered by generated code from this other plugin, and merge it into the descriptor defined by the generated code from the primary language plugin.

An approach like this allows the source code info to be a separate artifact (with its own canonical location: class name, package, file name, whatever, all derived from the location of the main artifact). This could be managed as a separate dependency.

If this feature were part of the core protobuf project, the various language runtime libraries could provide the source info in this fashion for the well-known protos, publish in a separate module/package/artifact. Only users that care about the source info would link it in.

Having it be part of the core runtimes also means that it can be automatically incorporated into the gRPC reflection service: the reflection service implementation could look for source info (in presumably the same way it discovers the descriptors) and fallback to just excluding that if the source info dependencies are not linked in. (With my approach, an external plugin and library, I will have to fork or wrap the existing gRPC reflection service in order to augment the descriptors with the source info.)

Anyhow, I understand this idea might not be super-compelling as an innate feature in protobuf and gRPC, but I certainly wish it were. Even if it never makes it as a first-class feature, the approach can serve as a pattern that 3rd-party developers can use to provide this capability via a bolt-on library.
