### ISSUE TITLE
 Nullable types - TimestampValue and DurationValue

### ISSUE THREAD

**Issue by zs-dima** [protocolbuffers/protobuf#8822]
It is nice to have Int32Value, StringValue and etc nullable type for the int32, string and etc non-nullable types.

But TimestampValue and DurationValue nullable types are missing - so it confusing many developers:
https://github.com/grpc/grpc-dart/issues/502

Could I kindly ask you to implement TimestampValue and DurationValue nullable types ?

**Comment by mattwelke** [comment]
These types actually already have support for nullability. In proto3, any type that is a message has built in support for nullability. Because Timestamp and Duration are messages, it works out of the box.

Example: https://github.com/mattwelke/dart-proto-example

Here's my test message, based on the official Dart getting started guide:

```proto3
syntax = "proto3";
package tutorial;

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

message Person {
  string                      first_name      = 1;
  google.protobuf.StringValue last_name       = 2;
  google.protobuf.Timestamp   graduation_date = 3;
}
```

I use a string and a `StringValue` to demonstrate the difference between a string, which is a primitive, and does not support nullability, and a `StringValue` which because it's a message (a wrapper message), does support it.

In the `main.dart` file:

```dart
import 'google/protobuf/timestamp.pb.dart';
import 'google/protobuf/wrappers.pb.dart';
import 'person.pb.dart';

void main() {
  final john = new Person(firstName: "John");
  print("John has last name: ${john.hasLastName()}");
  print("John is graduate: ${john.hasGraduationDate()}\n");

  final jane =
      new Person(firstName: "Jane", lastName: new StringValue(value: "Doe"));
  print("Jane has last name: ${jane.hasLastName()} (${jane.lastName.value})");
  print("Jane is graduate: ${jane.hasGraduationDate()}\n");

  final jim = new Person(
      firstName: "Jim",
      lastName: new StringValue(value: "Doe"),
      graduationDate: new Timestamp());
  print("Jim has last name: ${jim.hasLastName()} (${jim.lastName.value})");
  print(
      "Jim has graduated: ${jim.hasGraduationDate()} (${jim.graduationDate.seconds})\n");
}

When you run it with `dart run lib/src/main.dart`, this is the output:

```
John has last name: false
John is graduate: false

Jane has last name: true (Doe)
Jane is graduate: false

Jim has last name: true (Doe)
Jim has graduated: true (0)
```

Note that despite the lack of a "TimestampValue" wrapper type existing, you still get the `hasGraduationDate` instance method generated. All message fields will get either these "has" functions generated (Java is another example I can think of) or you can compare the field with the language's "null" value (Go and C# come to mind). It's up the implementer of the language's Protobuf plugin. In this case, the implementers of the Dart plugin went with the "has method" approach.

This is why Google only created wrapper messages for `double`, `float`, `int64`, `uint64`, `int32`, `uint32`, `bool`, `string`, and `bytes`. They're Protobuf primitives, so it's impossible for any implementation to generate either the "has methods" or the comparisons to the null value. So Google stepped in to make the wrapper types so that people wouldn't have to. This is nice because now a StringValue in one project is the same type as a StringValue in another project, even if they're from different parties. That saves the parties from having to write glue code if we wanted to assign the value of one field in one message to another field in another message.

A bit off topic, but note that since release 3.15, the "optional" keyword came back, and you can use that for nullable primitives without having to use the wrapper type. See the accepted answer at https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3?rq=1.

**Comment by zs-dima** [comment]
@mattwelke thanks a lot for reply and looking into
as you could see Dart command reply to the issue https://github.com/grpc/grpc-dart/issues/502

you could not create `Person` in this way currently:

```dart
  final jim = new Person(
      firstName: "Jim",
      lastName: new StringValue(value: "Doe"),
      graduationDate: null);
```

and `new Timestamp()` has duration == 0 so it is not replacement for `null` value.

However optional and required keywords looks promising, lets wait till they will be supported in dart to close this issue.

**Comment by mattwelke** [comment]
@zs-dima In my example, to create a `Person` who explicitly had no `graduationDate`, instead of writing the following code:

```dart
  final jim = new Person(
      firstName: "Jim",
      lastName: new StringValue(value: "Doe"),
      graduationDate: null);
```

You would write the following code:

```dart
  final jim =
      new Person(firstName: "Jim", lastName: new StringValue(value: "Doe"));
```

That's why I had three `Person`s being created in the example. I wanted to demonstrate that just like how one can omit `lastName` (because it is a `StringValue` - a message) to indicate no last name, one can omit `graduatedDate` for the same purpose. You'll end up having `false` returned by `hasGraduationDate`, so you can check whether there is one or not when you use the message, the same way one would do, for example, in JavaScript with an object:

```js
if (jim.graduationDate) {
  // they have a graduation date
}
```

As for why I used an example with seconds: 0, that's just because I'm not very familiar with Dart at the moment, so I couldn't figure out how to create a `Timestamp` for my example. I just encountered your question and wanted to help you out because I was familiar with the fact that every message type has built in support for nullability. Plus I thought it'd be a neat way to learn some more Dart.

**Comment by zs-dima** [comment]
@mattwelke thanks for reply

but you could not just skip arguments specially for data mappers
therefore you have to pass something as graduationDate/graduationDuration/etc

and it is not possible in the dart at least right now:

```dart
  final jim = new Person(
      firstName: "Jim",
      lastName: new StringValue(value: "Doe"),
      graduationDate: ???);
```

**Comment by zs-dima** [comment]
@mattwelke for example you have 30 fields in some object and most of them are nullable dates or durations.

It is not possible to solve it in a way you described.

But it is main use for proto messages objects to be mapped into app businesses objects and back.

**Comment by mattwelke** [comment]
Ahh I see the problem you're getting at. I actually ran into that a few weeks ago using Protobuf in Java. I wanted to use a map method in a functional programming style, but the problem was I had to omit a message field if a certain condition in the source data was true. I got it to work by changing from an immutable style to a mutable style as I produced the new object.

I'll use JS for pseudocode here:

```js
const newData = oldData.map(o => {
  const new = {
    a: o.a,
  };
  
  if (o.someCondition) {
    new.b = someValue,
  };

  return new;
});
```

It's not as concise as other ways of writing a mapping function, but it works. I was able to omit setting the Protobuf message field when the source data's condition was met.

**Comment by zs-dima** [comment]
@mattwelke thanks for idea but it looks just Java specific solution and will not help with other languages.
Specially with Dart businesses objects where immutable are required for the app architecture

**Comment by fowles** [comment]
I suspect this has already been fixed for C#, but kicking it to you to verify

**Comment by jskeet** [comment]
I don't believe `optional` has any effect on message fields, at least in C#. There's no difference between "absent because it was never specified" and "absent because it was set to null".

Any `Duration` and `Timestamp` fields *are* nullable in C# - it's fine to set the properties to null. Is that all that's required here? I think so, but I may be missing something (partly due to not understanding Dart...)

**Comment by jskeet** [comment]
(Reassigned so that @fowles can potentially close if I've understood the question correctly, basically.)

**Comment by mattwelke** [comment]
@jskeet The new `optional` in proto3 is something each language implementation has to opt into, right? My understanding of the proto2 vs. proto3 thing was that the maintainers decided that in proto3, everything should be optional and they recommended those `StringValue` etc wrapper types as a workaround for folks who want to be more explicit that an absence of a value has meaning. But then they re-introduced proto3 due to popular demand, and right now it's up to the implementations to add support for it if they think it's worth it.

**Comment by fowles** [comment]
In most languages `optional` in proto3 means "A `hasFoo` method is generated to expose whether the presence bit is set".  Additionally, fields that are set explicitly to their default value get serialized onto the wire.  @jskeet

**Comment by jskeet** [comment]
@fowles: There's no need for a separate method here though for *message* fields in C# - you just say `if (message.Foo == null)` or `if (message.Foo != null)`. And for other languages, don't *all* message fields have that?

> Additionally, fields that are set explicitly to their default value get serialized onto the wire.

Again, I don't *think* that really applies to message fields, does it?

**Comment by fowles** [comment]
@jskeet as long as it is testable.  Other languages don't expose null on things so they need a has method.
