### ISSUE TITLE
how to use this protobuf lib for transfer .proto file to java file without protoc.

### ISSUE THREAD

**Issue by sodaRyCN** [protocolbuffers/protobuf#8949]
use protoc tool , i could transfer .proto file to java file ,but the java file is too complex。

i just want transfer a simple java file without like protoc‘s  builder。

e.g

pb:  message dto{string id=1,int32 age=2}
transfer java : pulic class/interface Dto {privte sting id;private age;  getter/setter....}

**Comment by perezd** [comment]
You could write a custom plugin to protoc if you are unhappy with the default. Here's an example of someone doing that in Python: https://expobrain.net/2015/09/13/create-a-plugin-for-google-protocol-buffer/


Otherwise, for questions or troubleshooting, please see the protobuf mailing list: https://groups.google.com/forum/#!forum/protobuf or Stack Overflow https://stackoverflow.com/questions/tagged/protocol-buffers

We don't formally monitor stack overflow but there are a lot of smart coders there who also use protobuf.
