### ISSUE TITLE
Support for Generated Classes to be Immutable

### ISSUE THREAD

**Issue by shaileshpjoshi** [protocolbuffers/protobuf#9016]
**What language does this apply to?**
C#

If it's a proto syntax change, is it for proto2 or proto3?
proto3

If it's about generated code change, what programming language?
Yes. C#

**Describe the problem you are trying to solve.**
In our Heavily Multi-Threaded Application, we use Immutable Objects for safety.
These objects also get persisted. The current auto-generated code doesn't have
any public setters and has constructors that accepts all the parameters at the instantiation
time.

As soon as the object is deserialized, the object immediately becomes immutable. Any
change to the objects needs cloning with modifications.

The generated Protobuf classes always have public setters.

**Describe the solution you'd like**
We would like an option during code generation that can generate the Protobuf classes
to be immutable either using

1. Classes with private-only setters and constructor to take all parameters
2. OR use the C# 9 language feature for "records"

**Describe alternatives you've considered**

We have considered second level of transformation on the generated code. But,
don't have enough expertise to understand if it would have any implication on deserialization.

If there are any easy alternatives, happy to try those out while the feature lands.

**Additional context**

**Comment by jskeet** [comment]
We have discussed this internally as well - you're certainly not alone in finding immutability attractive. (And indeed my *original* project supporting C# for proto2 followed the same pattern as Java, with builders.) When designing the C# support for proto3, we decided that the usability of mutable classes outweighed the benefits of immutability, particularly with respect to making API calls (where requests are usually created, sent and then discarded). Back then, record types weren't available - if they had been, that might well have made a difference.

At the moment we don't have the bandwidth to support two different generators and either two different support libraries or a single support library which is able to expose both mutable and immutable code. (It gets even more complicated when you consider the possibility of mixing - what happens if a mutably-generated class refers to an immutably-generated class or vice versa?)

Also note that just using private setters would still expose the "merge" operations which would mutate the existing object - basically I suspect that trying to retrofit immutability onto the existing generated code is a non-starter. If this is purely for your own internal use, you might *consider* creating your own generator using record types, potentially using Google.Protobuf for serialization primitives - but if you need external users to work with the code as well, I suspect it would get really complicated, really quickly.

It's definitely something we'll keep considering internally, but we don't expect to implement this any time soon. (And to be clear, I mean it's not even on the medium-term horizon - unless there are other intervening factors, I'd be very surprised to see this implemented as a feature and launched within the next two years...) I know that's not the answer you want to hear, but I hope it at least provides some clarity.

I'll close this issue now, as I'm not expecting any changes in this repo any time soon - but please understand that's in no way a rejection of the idea itself; just a pragmatic reflection of limited resources (and the tradeoff between the simplicity of supporting just the current approach, and the complexity of providing more options).
