### ISSUE TITLE
protobuf compiler creates deprecated code

### ISSUE THREAD

**Issue by jonathanl-telenav** [protocolbuffers/protobuf#9088]
**What version of protobuf and what language are you using?**
Version: proto3, 3.11.4
Language: Java

**What operating system (Linux, Windows, ...) and version?**

MacOS 11.6

**What runtime / compiler are you using (e.g., python version or gcc version)**

Java 16

**What did you do?**

1. Go to https://cl1p.net/microservicegrcpmessage
2. Examine lines 48 and 49

To reproduce from scratch:
1. Install https://github.com/Telenav/kivakit by instructions
2. Switch to branch feature/microservice-grpc
3. Build with kivakit-build.sh
4. Examine the generated files in kivakit-extensions/kivakit-microservice/target

**What did you expect to see**

No warnings when compiling compiled .proto file

**What did you see instead?**

/Users/jonathan/Workspaces/kivakit-1.1/feature/kivakit-extensions/kivakit-microservice/target/generated-sources/protobuf/java/com/telenav/kivakit/microservice/grpc/MicroserviceGrpcMessage.java:49:59
java: **com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner** in com.google.protobuf.Descriptors.FileDescriptor **has been deprecated**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

No.

**Comment by fowles** [comment]
3.11.4 is a very old release.  Does this repro on 3.18.1 ?

**Comment by jonathanl-telenav** [comment]
It seems to. Do you see it with this flag use on the maven compiler plugin?

     <compilerArgument>-Xlint:deprecation</compilerArgument>

**Comment by deannagarcia** [comment]
I can reproduce this, but it's working as intended. You can see that deprecated method [here](https://github.com/protocolbuffers/protobuf/blob/aa22c5e0de189b74271335eea179e5321d88768e/java/core/src/main/java/com/google/protobuf/Descriptors.java#L368). We still use it in our code but we deprecated it because other users shouldn't use that. While it would be optimal if we cleaned up our code to not use this deprecated code, I don't see it happening soon as it would require a pretty big rewrite.
