### ISSUE TITLE
EBNF grammar is wrong and incomplete

### ISSUE THREAD

**Issue by d-frey** [protocolbuffers/protobuf#9126]
I was reading https://developers.google.com/protocol-buffers/docs/reference/proto3-spec to implement the grammar in our library. The linked page says it's EBNF, but it is not. EBNF requires a comma `,` for concatenation, which the proto3 grammar doesn't use. Besides this technicality, which might not be too relevant in practice, there is no clear specification given for spaces. As spaces can also be comments, the grammar leaves open multiple questions. For example looking at [this rule](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#package):

`package = "package" fullIdent ";"`

the page then gives an example:

`package foo.bar;`

Since there is no space required between `fullIdent` and `";"`, does this mean that no space is required between `"package"` and `fullIdent` either? So would `packagefoo.bar;` also be valid? (Probably not, but the grammar does not specify where zero spaces are allowed and where at least one space must occur).

Mix comments into the bag and the question becomes whether `package/*comment*/foo.bar;` is valid.

**Comment by JasonPolisAdmin** [comment]
It's missing the "optional"  label for fields, and the syntax for comments.

I've posted a railroad diagram here: 
https://openstandards.plus/wp-content/uploads/2021/07/ProtoBuf3-GoOgle-specEBNF.zip

**Comment by jhump** [comment]
FWIW, I wrote a spec based on my own re-implementation of protoc in Go (an implementation that I'm fairly confident is closer to protoc than any other tool).

I didn't try to incorporate the whitespace and comment-handling into the main grammar because it _really_ complicates things, especially trying to define the message literal syntax (since the places where whitespace separators are optional or required make it hard to decompose the rules into sane productions). So I took the route that most language specs I've read use (including Java and Go), and that is to define lexical analysis separate from the main grammar.

I'm curious what folks think of this:
https://github.com/jhump/protocompile/tree/master/grammar
