### ISSUE TITLE
Comparison of protobufs with objects of other types is broken (e.g., mock.ANY)

### ISSUE THREAD

**Issue by pkch** [protocolbuffers/protobuf#9173]
```
from unittest import mock
# Suppose msg is some protobuf message
# This assertion passes, as expected
self.assertEqual(mock.ANY, msg)
# I was hoping that this assertion will pass as well, but it doesn't
self.assertEqual(msg, mock.ANY)
```
Presumably this is due to incorrectly returning `False` from `__eq__` in [here](https://github.com/malthe/google-protobuf/blob/ca3abfb7340b1c5dddf1ab18482b668bb409be59/python/google/protobuf/internal/python_message.py#L685), but I haven't verified this. If so, it would be a similar issue to https://github.com/googleapis/google-cloud-python/issues/3455. 

In general, `return False` instead of `return NotImplemented` when rhs is of a different type is a common error, and there many instances of that in the google-protobuf. Which of them are worth fixing (and whether it's safe to do so) is unknown to me.

**Comment by elharo** [comment]
Funny, I'd expect both of these to fail.

**Comment by barbacbd** [comment]
I think that this is expected behavior. Mock.Any will always return true. But Any does not have the matching type nor features of a protobuf message. Even if you decide to try to make this true you would be stuck adding in a hack to check if the type is Mock.Any and just pass it. A fix you can try is to create a mock object that inherits from or is very similar to a protobuf message so that all of the attributes are the same and the type is masked as a PB message.

**Comment by elharo** [comment]
Equality *should* be symmetric for logical reasons. If that's not true, then something is broken here, perhaps deeply. The issue might not be in protobuf though.
