### ISSUE TITLE
What's the difference between release version and source code?

### ISSUE THREAD

**Issue by BoltzmannZhaung** [protocolbuffers/protobuf#9229]
I had a problem that there are some difference between  release version and source code. Let's say, protobuf-3.17.3. In release version(that downloads from https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3), In file **src/google/protobuf/wire_format_lite.h** This a type named UInt32Size. But source code(git clone https://github.com/protocolbuffers/protobuf.git), In file **src/google/protobuf/wire_format_lite.h** the Type named UInt32SizePlusOne, and I think this UInt32SizePlusOne is coresponding to UInt32Size.
that will orrur a compiling error.

**Comment by deannagarcia** [comment]
Source code lives at head and is constantly being updated. The releases are snapshots of what the code was like at intervals that we performed releases. The difference in code is just because between the release and now a developer made a change. If there's a specific error here, please file another bug.
