### ISSUE TITLE
Improve FileDescriptor.BuildFromByteStrings in C#

### ISSUE THREAD

**Issue by xoofx** [protocolbuffers/protobuf#9431]
Hello!

**What language does this apply to?**

C#

**Describe the problem you are trying to solve.**

The following API `FileDescriptor.BuildFromByteStrings` is relatively impractical to use directly:

https://github.com/protocolbuffers/protobuf/blob/41e22cde8d8a44c35127a26c19e08b180e0b30a4/csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs#L486-L521

The underlying code forces the input byte strings to be ordered. In order to order them, you need to load them in proto class instead, re-order them by their dependencies and re-serialize back to ByteString. This is quite inefficient.

I had to workaround this while developing [grpc-curl](https://github.com/xoofx/grpc-curl):

https://github.com/xoofx/grpc-curl/blob/f7bbe35af79713f278150b96ce51817807a06581/src/DynamicGrpc/DynamicFileDescriptorSet.cs#L139-L163

**Describe the solution you'd like**

* This API should handle the re-order. We are already loading the proto from the loop. We can resolve them in the same go to properly order them before initializing the `FileDescriptor`.
* A new API could be added to also allow to load from `FileDescriptorProto` directly.

**Describe alternatives you've considered**

The workaround is described above and is inefficient.

**Additional context**
none

**Comment by jasonmreding** [comment]
I ran into this recently as well, and it is indeed a pain. It doesn't help that the [C# service implementation](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Reflection/ReflectionServiceImpl.cs#L141) also doesn't return things in dependency order since it uses a HashSet internally. Fixing that would help alleviate the need for this improvement, but it would only help when communicating with services implemented in C#. I'm not sure what other language implementations typically do here, but to be safe, the dependency order checking is probably still needed. If nothing else, have the server return things in the proper order would at least prevent worst case search performance in the work around code linked above.

**Comment by Xpl0itR** [comment]
This is still an issue.
