### ISSUE TITLE
Why is there a Java 4.0.0-rc-2 release?

### ISSUE THREAD

**Issue by daveyostcom** [protocolbuffers/protobuf#9455]
I have been searching and cannot find any explanation for the existence of the 4.0.0-rc-2 version of Protocol Buffers [listed](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/4.0.0-rc-2) in the Maven repository.

It’s old (Jul 21, 2020) and it’s been stuck at that futuristic release-candidate version while the apparently real releases have been progressing from 3.12.14 to 3.19.3.

It sure seems odd.  An explanation would be welcome, published somewhere.

**Comment by elharo** [comment]
Because Maven central doesn't allow us to delete anything since published, and prioritize later unstable versions over smaller stable version numbers or more recently published artifacts with lower version numbers. I am sorry this shows up as the first release. It shouldn't.  That effort is no longer in progress, and if there ever is a 4.0.0 for Java it will not be derived from that.

**Comment by daveyostcom** [comment]
Perhaps you could annotate the release on Maven Central do people would know?

**Comment by elharo** [comment]
How might one do that? If there are instructions somewhere, I can take a look. My understanding is that Maven Central is very close to a write-once repo.
