### ISSUE TITLE
Generated Python code is unidiomatic

### ISSUE THREAD

**Issue by danieleades** [protocolbuffers/protobuf#9489]
It's been pointed out in many tickets that the generated Python code is unidiomatic, and not IDE-friendly.

I think it's best summed up in the [better-proto](https://github.com/danielgtaylor/python-betterproto) README (which i'm paraphrasing here)

- No typing support or code completion/intelligence (requires additional mypy plugin)
- No `__init__.py` module files get generated
- Output is not importable
    - Import paths break in Python 3 unless you mess with sys.path
- Bugs when names clash (e.g. codecs package)
- Generated code is not idiomatic
   - Completely unreadable runtime code-generation
   - Much code looks like C++ or Java ported 1:1 to Python
   - Capitalized function names like HasField() and SerializeToString()
   - Uses SerializeToString() rather than the built-in __bytes__()
   - Special wrapped types don't use Python's None
   - Timestamp/duration types don't use Python's built-in datetime module

**I think most of this has been pointed out in various ways and in various tickets. What I haven't seen is whether there's any plan or roadmap to address this?**

**Comment by haberman** [comment]
Hi @danieleades,

Our overall strategy here is:

1. Provide IDE completion with `.pyi` files.
2. Potentially add native support for the [proto plus](https://github.com/googleapis/proto-plus-python) API, with a few extra enhancements.

Going through your list:

> - No typing support or code completion/intelligence (requires additional mypy plugin)

This should be addressed by our `.pyi` generator.

> - No `__init__.py` module files get generated

This is unfortunately [fundamentally incompatible](https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-883735797) with parallel compilation. If two different projects use the same protobuf package and run `protoc` separately, it will break.

> - Output is not importable
>  - - Import paths break in Python 3 unless you mess with sys.path

I wrote up a solution for this in [the related bug](https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-1022571406). I know some folks are still unsatisfied with this.

@sbrother has [a great idea for making `setup.py` do the right thing](https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-1022757287), so that dependent protos can be installed with `pip install`. This should avoid the need to change `PYTHONPATH`.

> - Bugs when names clash (e.g. codecs package)

I don't know what this means.

> - Generated code is not idiomatic
> - Much code looks like C++ or Java ported 1:1 to Python
> - Capitalized function names like HasField() and SerializeToString()

These issues should all be addressed if/when we adopt [proto plus](https://github.com/googleapis/proto-plus-python).

> - Completely unreadable runtime code-generation

Going forward, our intention is:

1. The `_pb2.py` files are primarily optimized for fast loading speed. They offer no pretense of readability, they are designed only to import as fast as possible, which can matter if you have hundreds or thousands of protos you are importing (as can happen if your protos have lots of imports).
2. The `_pb2.pyi` files offer full typing hints, to show exactly the effective API of each generated type, and provide full code completion for IDEs.

> - Timestamp/duration types don't use Python's built-in datetime module

We will endeavor to offer very easy conversion between `Timestamp`/`Duration` and Python's types. But we can't use the Python types directly as the native storage, because the Python types only offer microsecond precision and our types need nanosecond.

> - Uses SerializeToString() rather than the built-in `__bytes__()`
> - Special wrapped types don't use Python's None

I like both of these; we should be able to do these with [proto plus](https://github.com/googleapis/proto-plus-python).

**Comment by sbrother** [comment]
I just commented this in the linked centithread, copying it here too:

> OK, I just made a [custom setuptools command](https://github.com/sbrother/protobuf-custom-build) and an example protobuf repository that implements it: https://github.com/sbrother/python-protobuf-repo-example. This solves the use case I've run into most frequently where I want to have a separate, shared schema module with protobuf definitions, which I then want to compile into generated code in several different services.

> The idea is that you can just include these python packaging artifacts (pyproject.toml, setup.py, setup.cfg) that call out to the custom rule, and then moving forward you can install working Python generated library with `pip install /path/to/your/protobuf/repo` (it will also work hosted on GitHub or a PyPI server). It uses the awesome protoletariat library @cpcloud mentioned above to do the heavy lifting; so thanks again for that!
