### ISSUE TITLE
[C#] MethodOptions.GetExtension cast exception

### ISSUE THREAD

**Issue by JamesNK** [protocolbuffers/protobuf#9626]
I get a cast exception from `GetExtension` when trying to get `HttpRule`.

Imagine we have two projects:

Project 1 has a gRPC service that uses http extension. It passes http.proto to protoc: 

```xml
<Protobuf Include="..\Proto\greet.proto" GrpcServices="Server"  ProtoRoot="..\Proto\" Link="greet.proto"/>
<Protobuf Include="..\Proto\google\api\annotations.proto" GrpcServices="Server"  ProtoRoot="..\Proto\" Link="google\api\annotations.proto"/>
<Protobuf Include="..\Proto\google\api\http.proto" GrpcServices="Server"  ProtoRoot="..\Proto\" Link="google\api\http.proto"/>
```

Project 2 tries to get `HttpRule` from gRPC service in Project 1. Project 1 references the `Google.Api.CommonProtos` package which contains a different copy of `HttpRule`:

```xml
<PackageReference Include="Google.Api.CommonProtos" Version="2.2.0" />
```

Code:

```cs
var options = methodDescriptor.GetOptions();
var http = options?.GetExtension(AnnotationsExtensions.Http);
```

Error message:

> [A]Google.Protobuf.ExtensionValue1[Google.Api.HttpRule] cannot be cast to [B]Google.Protobuf.ExtensionValue1[Google.Api.HttpRule].
> Type A originates from 'Google.Protobuf, Version=3.18.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' in the context 'Default' at location 'C:\Development\Temp\GrpcHttpApiIssueSample\Service_Api_Reference\bin\Debug\net6.0\Google.Protobuf.dll'.
> Type B originates from 'Google.Protobuf, Version=3.18.1.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604' in the context 'Default' at location 'C:\Development\Temp\GrpcHttpApiIssueSample\Service_Api_Reference\bin\Debug\net6.0\Google.Protobuf.dll'.

I understand why this happens. There are two copies of `AnnotationsExtensions.Http` and the copy being used to get `HttpRule` in Project 2 isn't the one that the gRPC service was compiled with in Project 1.

And a fix is for Project 1 to not compile its own copy of http.proto and instead reference the `Google.Api.CommonProtos` package.

What I'd like is to make this problem disappear so people don't need to worry. When Project 2 attempts to get the extension:
* GetExtension recognizes this situation and parses the proto data with the different copy of the type
* Or there is an API that exposes raw bytes that lets the caller do this

cc @jtattermusch @jskeet

**Comment by jskeet** [comment]
Will look at this tomorrow.

**Comment by JamesNK** [comment]
FYI this is the real world example of this problem: https://github.com/grpc/grpc-dotnet/issues/167#issuecomment-1065268763

(the library in this case was using the old `descriptor.CustomOptions.TryGetMessage` which silently returns null. When I updated the code to use `descriptor.GetOptions().GetExtension` then I saw the new error).

**Comment by JamesNK** [comment]
I wonder if a non-generic way to get the extension message would be a solution?

e.g. a GetExtension method that returns `IMessage`. If the extension type isn't expected then the caller could convert the message into a byte array and then reparse the bytes using the known type.

**Comment by jskeet** [comment]
FYI: this is still definitely on my plate, but I didn't get to it today. It's really unfortunate that the error message looks non-sensical due to the difference being in the type argument (`Google.Api.HttpRule`) rather than in the `ProtobufExtensionValue<>`.

Thanks for the link to the repro - that should make it easier for me to understand. I'm afraid my brain always takes a while to get back into extensions.

A method that returns `IMessage` *might* be feasible - for message-based extensions, of course. (It would have to fail for string-based ones.) Will prototype a bunch of options.

At the very least I'd like to detect the problem and provide a more descriptive error message :)

**Comment by JamesNK** [comment]
> A method that returns `IMessage` _might_ be feasible - for message-based extensions, of course. (It would have to fail for string-based ones.) Will prototype a bunch of options.

I didn't know there are string extensions. A method returning object is also fine.

**Comment by jskeet** [comment]
To save anyone else reading this from issue-hopping, @JamesNK has now provided a nicely-minimal repro here: https://github.com/JamesNK/ProtobufExtensionBug

One thing to note before I really delve into what's possible: this isn't so different from how the rest of .NET behaves. If I were to define my own `HttpClient` class and then try to use `IServiceProvider.GetService<HttpClient>()` after calling `services.AddHttpClient()`, then it wouldn't find that, either... and I wouldn't expect the ASP.NET Core DI folks to try to find something with "the same type name but in a different assembly".

This isn't to say I don't think we should do anything - just that "two types with the same name but in different assemblies aren't interchangeable" has been a fact of life since the beginning of .NET. Protobuf just brings an extra dimension of "same proto compiled into different assemblies" - much as you could have the same C# source compiled into different assemblies. We'll need to think carefully about how we resolve this.

(Returning `object` would allow the caller to get a bit further, for sure - but then if they tried to cast it to their expected type, it would still have a problem. And I'd be worried about trying *too* hard to assume that two proto-based types were actually identical, based on the FQN - they could easily be different versions of the same original proto.)

Much to ponder.

**Comment by JamesNK** [comment]
> (Returning object would allow the caller to get a bit further, for sure - but then if they tried to cast it to their expected type, it would still have a problem. And I'd be worried about trying too hard to assume that two proto-based types were actually identical, based on the FQN - they could easily be different versions of the same original proto.)

I think automatically changing type is probably too magical. But I think a non-generic method that returns the value as object gives the caller flexibility. If that was supported then I'd have consumer code that is something like:

```cs
const int HttpRuleFieldId = 72295728;

object extension = descriptor.GetOptions().NonGenericGetMethod(HttpRuleFieldId);
if (extension is HttpRule r)
{
    // typed value matches expected type
    return r;
}
else if (extension is IMessage m)
{
    // typed value is different. convert to bytes and parse using expected type
    byte[] payload = m.ToByteArray();
    return HttpRule.Descriptor.Parse(payload);
}
else
{
    return null;
}
```

**Comment by jskeet** [comment]
Okay, I've implemented this now as a proof of concept (#9635), and it works fine. The `HttpRuleChecker` code becomes:

```csharp
public static class HttpRuleChecker
{
    public static HttpRule? GetHttpRule(MethodDescriptor methodDescriptor)
    {
        var options = methodDescriptor.GetOptions();
        object? extension = options?.GetExtensionValue(AnnotationsExtensions.Http.FieldNumber);
        return extension switch
        {
            HttpRule rule => rule,
            IMessage message => HttpRule.Parser.ParseFrom(message.ToByteArray()),
            _ => null
        };
    }

    public static bool HasHttpRule(MethodDescriptor methodDescriptor) =>
        GetHttpRule(methodDescriptor) is not null;
}
```

The code is simple, it works, and it definitely addresses this specific use case. My only question is how frequently this use case will actually occur, or whether it is useful in any other situations. I suspect that any time there are multiple generated versions of the same proto, you could easily run into other problems anyway - so if those are avoidable (in this case e.g. by changing the documentation) then I think that would be preferable.

In terms of other situations, I can imagine non-generic access being useful if we exposed the extension registry more widely. For example, you could then say:

```csharp
foreach (var extension in MethodOptions.Parser.Extensions)
{
    Console.WriteLine(options.GetExtensionValue(extension.FieldNumber));
}
```

Is that a sufficiently-compelling use case to drive this? I'm not sure. I'm happy to be convinced that the use case that prompted this is actually going to be wide-spread in "otherwise correct" scenarios, but I'm not sure about making the change if we really don't want users to ever get into the situation of needing this anyway.

**Comment by JamesNK** [comment]
That looks like it solves my immediate problem. However, does it matter that the new method isn't on `IExtendableMessage<T>`? I'm not using that interface at all so I don't really know.

The existing generic methods should probably have some type checking so they can provide a better error message. That can be a separate piece of work.

**Comment by jskeet** [comment]
> However, does it matter that the new method isn't on IExtendableMessage<T>? I'm not using that interface at all so I don't really know.

Hmm... that's slightly irritating. We can't add to `IExtendableMessage<T>` as adding a method to an interface is a breaking change (and we can't use default methods due to targets). Given that this is already very much a corner case, I think even if we *do* go ahead, we could probably not worry about putting it into the interface, at least to start with.

> The existing generic methods should probably have some type checking so they can provide a better error message. That can be a separate piece of work.

I'd definitely be happy to do that, regardless of whether we take any other actions. Mind you, it probably needs to stay as the same exception *type* to make it less of a breaking change. It'll probably be more about changing just the message rather than anything else.

**Comment by JamesNK** [comment]
Your changes made me think about how `GetExtension` works. Here is a hacky idea that allows the caller to declare their own `Extension` that returns object: https://github.com/JamesNK/protobuf/pull/3

The pro is no new public API. Con is it is a hack and is an extremely non-obvious workaround to this issue.

**Comment by jskeet** [comment]
I'm not sure that it's a problem for it to be non-obvious if it's a *massively* corner case which hardly anyone will ever see - which is still my expectation. To put it another way: if you hadn't run into this with the gRPC/REST transcoding example which can be fixed with a documentation change (which makes the instructions simpler rather than more complicated, if I've understood correctly), would you expect to see this problem anywhere else?

**Comment by ShadyHarbinger** [comment]
This problem still exists. Just saying. gRPC is totally useless if protos are in another project.
