### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

### ISSUE THREAD

**Issue by shubhambagwari** [protocolbuffers/protobuf#9627]
I trained the model and saved it, now I am trying to load but unable to do. I have seen in previous post as well, but reference links are not working.

**Code**

```
`#load model

with tf.io.gfile.GFile(args.model, "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())

# with tf.Graph().as_default() as graph:
generated_image_1, generated_image_2, generated_image_3, = tf.graph_util.import_graph_def(
        graph_def, 
        input_map={'input_image' : input_tensor, 'short_edge_1' : short_edge_1, 'short_edge_2' : short_edge_2, 'short_edge_3' : short_edge_3}, 
        return_elements=['style_subnet/conv-block/resize_conv_1/output:0', 'enhance_subnet/resize_conv_1/output:0', 'refine_subnet/resize_conv_1/output:0'],  
        producer_op_list=None
    )`
```

**Error:**

```
`Traceback (most recent call last):
  File "stylize.py", line 97, in <module>
    main()
  File "stylize.py", line 57, in main
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'`
```

Note: I am using,
python = 3.7.6
Tried on both Tensorflow-gpu=1.15  and 2.7
tensorboard=1.15.0
protobuf =3.19.4

**Comment by haberman** [comment]
From the protobuf side, all I can tell you is that the parse is failing because the data is not a valid protobuf.

This suggests that the file in `args.model` is not valid protobuf data. But it's impossible to know why that is without knowing where that data came from.

This question is probably better to ask TensorFlow; they would be better equipped to help with TensorFlow APIs.
