### ISSUE TITLE
PHP: The mirror repository used to host protobuf for packagist has not been synced

### ISSUE THREAD

**Issue by dwsupplee** [protocolbuffers/protobuf#9746]
This is causing an issue with installations via composer, [as it is allowing PHP 5.5/5.6](https://github.com/protocolbuffers/protobuf-php/blob/master/composer.json#L9) to install versions such as v3.20.0 which [actually require PHP >=7.0](https://github.com/protocolbuffers/protobuf/blob/main/php/composer.json#L9).

For example, due to the inclusion of return type hinting:
```
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /tmpfs/src/github/google-cloud-php/vendor/google/protobuf/src/Google/Protobuf/Internal/RepeatedField.php on line 240
```

**Comment by macckenzie** [comment]
any temporary fix for this issue?

**Comment by bshaffer** [comment]
cc @haberman 
Unfortunately this one is breaking anyone using protobuf on < PHP 7.0. This is because the [latest versions](https://github.com/protocolbuffers/protobuf-php/blob/v3.20.1RC1/composer.json#L9) say they support PHP 5.5 but they're actually only compatible with PHP 7+.

We need to fix `composer.json` to be correct and then remove those tags (because composer will _always_ pull them in for PHP 5.5 / 5.6 even after we fix `composer.json` because they will be seen as the latest compatible versions of this library for those PHP versions).

Until we do that, protobuf will be completely broken for anyone on PHP 5.5 and 5.6

**Comment by perezd** [comment]
@haberman is this something that we missed as part of a release step?

**Comment by bshaffer** [comment]
I am submitting https://github.com/googleapis/gax-php/pull/382 to exclude the broken version of protobuf until we can get this resolved

**Comment by bshaffer** [comment]
We are also looking at [php/release.sh](https://github.com/protocolbuffers/protobuf/blob/main/php/release.sh), because this doesn't seem to be getting called

**Comment by haberman** [comment]
I think the underlying problem was fixed in https://github.com/protocolbuffers/protobuf/pull/9832 (with a related fix in https://github.com/protocolbuffers/protobuf/pull/9819).

Separately, we need to yank the 3.20.0 release since it advertises compatibility with PHP 5.5 but is not actually compatible.
