### ISSUE TITLE
extreme performance degradation on M1 with python

### ISSUE THREAD

**Issue by cbcmg** [protocolbuffers/protobuf#9839]
Hi, I'm not a protobuf user directly, but ran into this using pulumi.

On a Mac M1 Max, python3.9 arm64 build, trying to serialize roughly 8k of yaml from a Struct, takes a very, very long time. I give up after 10 minutes or so, not sure if it ever completes. The exact same code on Linux (running in an arm64 VM on the Mac) completes instantly. 

```python
# !pip install protobuf==3.19.4 pyyaml

import time
import yaml
from google.protobuf.struct_pb2 import Struct
import urllib.request

k8s_yaml = urllib.request.urlopen('https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml')

y = list(yaml.load_all(k8s_yaml, Loader=yaml.Loader))[2]

x = Struct()
x.update(y)

# uncomment to complete script in < 1s
# x['spec']['versions'][0]['schema']['openAPIV3Schema']['properties']['spec']['properties']['solver']['properties'].Clear()

t = time.time()

# this line is very, very, slow.
x.SerializeToString()

print(f'serialize={time.time() - t:.4f}')
```

**Comment by haberman** [comment]
You are probably getting the pure-Python implementation on the Mac, instead of the C++ accelerated version you are seeing on Linux.

I do not believe we are publishing aarch64 binaries for Mac at the moment. You can compile one yourself using the instructions posted here: https://github.com/protocolbuffers/protobuf/issues/8820#issuecomment-961552604

**Comment by cbcmg** [comment]
ok, that was the reason. I did do a local build of the gprcio package, but that clearly didn't build the protobuf extension as well. Thank you. Two questions, if I may. When is the M1 support coming? And shouldn't the pure python version still work in a reasonable fashion? How is it possible that it is so non-functional, at least in my use case? Thanks again.

**Comment by haberman** [comment]
> When is the M1 support coming?

The next release of Python will have a completely rewritten C extension. This should ship sometime next month, and I expect that it will ship with aarch64 binaries.

> And shouldn't the pure python version still work in a reasonable fashion?

The pure-Python implementation is very slow, just due to the performance limitations of Python as a language. Still, 10 minutes for an 8k payload seems excessive.

What do you get if you do `print(x.ByteSize())` with the C extension?

**Comment by cbcmg** [comment]
> What do you get if you do print(x.ByteSize()) with the C extension?
58225

> The pure-Python implementation is very slow
Python can be slow, but not this slow. There must be either a bug in the pure python code, or something O(n2) going on.

**Comment by cbcmg** [comment]
Another data point. Disabling the extension in Linux also causes the above test code to never finish:

```bash
$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python test.py
```

**Comment by haberman** [comment]
> Disabling the extension in Linux also causes the above test code to never finish:

It is expected that the pure-Python implementation on Linux and Mac would give similar results.

> Python can be slow, but not this slow. There must be either a bug in the pure python code, or something O(n2) going on.

I agree this is an extreme result. We probably won't be able to prioritize a diagnosis and fix of this anytime soon, because performance-wise we focus on the C/C++ extensions. We would welcome PRs for this though.
