### ISSUE TITLE
When the protoc.exe path has Chinese, the file cannot be found

### ISSUE THREAD

**Issue by sixsixsix516** [protocolbuffers/protobuf#9875]
![image](https://user-images.githubusercontent.com/45815935/165677892-b7093eb5-04c4-4c49-96e2-60a91b671a02.png)
The folder exists, but it prompts that the folder cannot be found

Then I removed the Chinese in the path and replaced it with English, so it can be used

So it cannot be used when the path has Chinese,
Is it possible to solve this problem?

Thanks

**Comment by snnn** [comment]
On Windows we say some programs are ANSI programs, some programs are Unicode programs. Unicode programs only use wide char(UTF-16) strings. If every sting is unicode, then the same code works for all languages that Windows can support.  Otherwise it would be less ideal. If you need to run any ANSI program with localized language support, you should set your system's display language and system locale  to the language. Here I saw your UI is english, but you want to use Chinese. It is fine for Unicode programs, but it is not good for ANSI program.
