### ISSUE TITLE
Atomic detection fails incorrectly for clang on windows

### ISSUE THREAD

**Issue by kalj** [protocolbuffers/protobuf#9879]
**What version of protobuf and what language are you using?**
Version: main etc.
Language: C++/Java/Python/C#/Ruby/PHP/Objective-C/Javascript

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
clang 11.0.1
python 3.9.1
ninja 1.10.2
cmake 3.22.2

**What did you do?**
1. Clone protobuf repo
2. Run:
   ```
   CC=clang CXX=clang++ cmake -S . -B build-dir -G Ninja --debug-trycompile
   ```

**What did you expect to see**
```
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Success
```

**What did you see instead?**

```
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Failed
```

Contents of `build-dir/CMakeFiles/CMakeError.log`:
```
Run Build Command(s):C:/PROGRA~1/Ninja/ninja.exe cmTC_458fb && [1/2] Building CXX object CMakeFiles/cmTC_458fb.dir/src.cxx.obj
FAILED: CMakeFiles/cmTC_458fb.dir/src.cxx.obj
C:\PROGRA~1\LLVM\bin\CLANG_~1.EXE -Dprotobuf_HAVE_BUILTIN_ATOMICS  -std=c++11 -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_458fb.dir/src.cxx.obj -MF CMakeFiles\cmTC_458fb.dir\src.cxx.obj.d -o CMakeFiles/cmTC_458fb.dir/src.cxx.obj -c C:/kod/protobuf/buildd/CMakeFiles/CMakeTmp/src.cxx
In file included from C:/kod/protobuf/buildd/CMakeFiles/CMakeTmp/src.cxx:2:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\atomic:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xatomic.h:13:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\type_traits:12:
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include\xstddef:283:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
_NODISCARD constexpr auto _Unfancy(_Ptrty _Ptr) noexcept { // converts from a fancy pointer to a plain pointer
                     ^
1 error generated.
ninja: build stopped: subcommand failed.


Source file was:

    #include <atomic>
    int main() {
      return std::atomic<int64_t>{};
    }
```

Reverting this change makes it work again since it gets the right C++ standard:
 https://github.com/protocolbuffers/protobuf/pull/6350/files

**Comment by dlj-NaN** [comment]
Hmm, this is a somewhat strange corner case... this build is using Clang, but building against the MS STL. The MS toolchain (including the STL) always assumes some minimum C++ version, so forcing Clang to use C++11 is problematic when that minimum is above 11 (which is has been for ages now).

The reason we force C++11 is because the `check_cxx_source_compiles` function doesn't forward `CMAKE_CXX_STANDARD` and friends, so other platforms (notably, recent macOSes, but also older supported compilers) will fail due to an old language version.

@kalj How exactly did you get to this configuration? This is almost certainly a shortcoming in the CMake module, because minimum language versions tend to be important in conditional compilation :-) ... but before doing too much, I'd like to understand how common this scenario might be.

**Comment by dlj-NaN** [comment]
One other possibility... I think that using [clang-cl](https://clang.llvm.org/docs/UsersManual.html#clang-cl) instead of the plain `clang` driver should be enough to convince CMake that you are doing an MSVC build. That would skip the libatomic check entirely.
