### ISSUE TITLE
Allow invoking the plugin of `protoc --plugin` with arguments

### ISSUE THREAD

**Issue by sigurdm** [protocolbuffers/protobuf#9953]
Currently the `protoc --help` says this:

```
  --plugin=EXECUTABLE         Specifies a plugin executable to use.
                              Normally, protoc searches the PATH for
                              plugins, but you may specify additional
                              executables not in the path using this flag.
                              Additionally, EXECUTABLE may be of the form
                              NAME=PATH, in which case the given plugin name
                              is mapped to the given executable even if
                              the executable's own name differs.
```

And EXECUTABLE is limited to name an executable.

I suggest that EXECUTABLE be replaced with a full command (including arguments)

Context:
This is coming from dart-specific view-point, but I think the solution has more general applicability:

Currently the [suggested](https://github.com/google/protobuf.dart/tree/master/protoc_plugin#how-to-build) way to use the dart protoc_plugin is to do `dart pub global acticivate protoc_plugin` because that will create a "binstub"  (a small executable script that invokes the dart vm with protoc_plugin.dart`) on the PATH.

**Ideally** we'd like to be able to install protoc_plugin as a local dependency in your project, and run it from there. But that will not give you a single executable to run.

 and then invoke 

`protoc --plugin='dart=dart run protoc_plugin' --dart_out=...`

Currently this can be done by making one's own shell/batch script that invokes `dart run protoc_plugin` but that is somewhat cumbersome.

**Comment by deannagarcia** [comment]
Unfortunately this is the only way to use plugins and we will probably not be prioritizing this work soon, since there is a simple workaround.

**Comment by WGH-** [comment]
This might be useful for Go as well. Go 1.24 introduces [managing per-project tool dependencies](https://tip.golang.org/doc/modules/managing-dependencies#tools) in `go.mod` so they can be run with `go tool github.com/<whatever>`, without messing with `PATH`, temporary directories, etc. If  `protoc` supported plugin arguments, it could look like this:
```bash
protoc --plugin=protoc-gen-go="go tool google.golang.org/protobuf/cmd/protoc-gen-go" ...
```

(you can already do this - `--plugin=protoc-gen-go="$(go tool -n google.golang.org/protobuf/cmd/protoc-gen-go)"` - but due to https://github.com/golang/go/issues/72824 it's currently semi-broken)
