### ISSUE TITLE
UInt and ULong in protobuf kotlin

### ISSUE THREAD

**Issue by Clement-Jean** [protocolbuffers/protobuf#9971]
**What language does this apply to?**

It is related to Kotlin generated code.

**Describe the problem you are trying to solve.**

I'm trying to get support for unsigned integers in Kotlin without having to additional checks with if clauses.

**Describe the solution you'd like**

- uint32 would map to UInt
- uint64 would map to ULong

**Additional context**

I'd be happy to contribute to this if this gets accepted. I understand that this could cause breaking changes but I believe this is pretty important and more idiomatic.

**Comment by elharo** [comment]
This requires a Tier 2 review. @deannagarcia is this worthe pursuing?

**Comment by deannagarcia** [comment]
Right now the Kotlin implementation is very dependent on the Java implementation. Since Java doesn't have unsigned data types, converting to UInt/ULong in Kotlin would require us to decouple the Java and Kotlin implementations. At least in the short-term I don't think that's a step that the protobuf team would want to take.
